### ISSUE TITLE
EventHub serializes incorrectly

### ISSUE THREAD

**Issue by jeffhollan** [Microsoft/azure-maven-plugins#100]
We have this bug in .NET as well, but in v2 the property `path` is renamed `eventHubName`.  [Need to rename it here as well](https://github.com/Microsoft/azure-maven-plugins/blob/ff16cefa8f4ccd530d866c8b9b33c688759ac0da/azure-functions-maven-plugin/src/main/java/com/microsoft/azure/maven/function/bindings/EventHubBinding.java#L40) so that the function.json has `eventHubName` property.

Mitigation today is you have to manually modify the generated function.json post-package

**Comment by selvasingh** [comment]
I am seeing the same issue .. I am manually editing function.json

**Comment by jdneo** [comment]
Fixed.
