### ISSUE TITLE
consumption type pricingTier cannot display the status of availablity on the portal

### ISSUE THREAD

**Issue by Elvira-sxr** [microsoft/azure-maven-plugins#1002]
### Plugin name and version
1.4.1-SNAPSHOT Azure Functions
### Expected behavior
![image](https://user-images.githubusercontent.com/51812626/72334859-fc3f0800-36f8-11ea-8eef-ea302850f780.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/51812626/72335042-47591b00-36f9-11ea-8867-900709b4f4d8.png)

### Steps to reproduce the problem
1. Configure pom.xml
2. Run mvn clean package
3. Run mvn azure-functions:deploy

**Comment by wangmingliang-ms** [comment]
it should be portal's problem.
