### ISSUE TITLE
Same account / Multiple tenants

### ISSUE THREAD

**Issue by SledgeHammer01** [microsoft/azure-maven-plugins#1003]
Using:

				<groupId>com.microsoft.azure</groupId>
				<artifactId>azure-webapp-maven-plugin</artifactId>
				<version>1.9.0</version>

When I went to deploy, it said I was not logged in as expected.  So I issued:

.\mvnw com.microsoft.azure:azure-maven-plugin:0.1.0:login

This logs in successfully, but I have access to 2 tenants. From the documentation, it doesn't seem possible to select the tenant? I tried updating the tenantId in azure-secret.json, but that didn't work either. It still can't see the subscription in the 2nd tenant.

**Comment by andxu** [comment]
the first version of `com.microsoft.azure:azure-maven-plugin:0.1.0:login` doesn't support multiple tenants(version 0.1.0 indicates that), for work-around, you can use `az login --tenant`,  the coming version of maven auth plugin(com.microsoft.azure:azure-auth-maven-plugin:0.1.0:login) will support multiple tenants.

**Comment by SledgeHammer01** [comment]
> the first version of `com.microsoft.azure:azure-maven-plugin:0.1.0:login` doesn't support multiple tenants(version 0.1.0 indicates that), for work-around, you can use `az login --tenant`, the coming version of maven auth plugin(com.microsoft.azure:azure-auth-maven-plugin:0.1.0:login) will support multiple tenants.

Hi,

I did az logout and :logout on the plugin, then did az login --tenant, but when you do a select-subscription, it says I'm not logged in. So then I have to use :login which of course goes to the wrong tenant. Can you explain your work-around?

**Comment by andxu** [comment]
Hi @SledgeHammer01, now `com.microsoft.azure:azure-maven-plugin:0.1.0:login` is deprecated. And you can `az login --tenant` through azure cli and our plugin will work on all the subscriptions on all tenants in your account (you need to specify the subscriptionId in pom.xml), please try newest version '2.1.0' and provide us the result, thank you.
