### ISSUE TITLE
<webContainer> does not act as expected when <packaging> is set to jar

### ISSUE THREAD

**Issue by paddy74** [microsoft/azure-maven-plugins#1012]
### Plugin name and version

azure-webapp-maven-plugin

### Plugin configuration in your `pom.xml`

The following correctly sets 'Java' as the Java container using an _unlisted option_:
```xml
...
<packaging>jar</packaging>
...
  <runtime>
      <os>windows</os>
      <javaVersion>11</javaVersion>
      <webContainer>java 11</webContainer>
  </runtime>
...
```

Based on [the documentation](https://github.com/microsoft/azure-maven-plugins/wiki/Azure-Web-App:-Configuration-Details#webcontainer) the following `<webContainer>` should be ignored and the above should still be set as long as `<packaging>` is set to `jar`:
`<webContainer></webContainer>`
`<webContainer>tomcat 8.0</webContainer>`
and so forth (including the absence of `<webContainer>`).

### Expected behavior

Based on the documentation found [HERE](https://github.com/microsoft/azure-maven-plugins/wiki/Azure-Web-App:-Configuration-Details#webcontainer), the maven plugin should deploy the project to the corresponding runtime/`<javaVersion>` due to `<packaging>` being set to `jar` regardless as to the setting or presence of `<webContainer>`.

### Actual behavior

If `<webContainer>`  is empty or omitted:
```
The configuration <webContainer> in pom.xml is not correct.
```

If `<webContainer>` is set to any of the supported values listed in the documentation then the relevant container is set (i.e. `tomcat 8.5` or `jetty 9.3`). However, the wording of the documentation under "Note2" implies that if `<packaging>` is set to `jar` then the setting or presence of `<webContainer>` is not considered.

### Proposed Solution

The solution is to either to correct the documentation by removing "Note2" and adding the Java SE container options to the "The supported Value for web App on windows" table _or_ edit the plugin to ignore `<webContainer>` when `<packaging>` is set to `jar`.

**Comment by Flanker32** [comment]
@paddy74 Thanks a lot for your report, we didn't update the wiki after the new release of webapp maven plugin. For old versions, we use a workaround for jar projects, which based on IIS instead of web container, and now Azure provide pure Java SE environment for windows java app services so the workaround has been removed. 

Will update the wiki soon, thanks again for your report.

**Comment by paddy74** [comment]
It looks like the documentation has been updated appropriately.
