### ISSUE TITLE
Azure Maven Plugin deployment does not work behind a proxy

### ISSUE THREAD

**Issue by oakieoaktree** [microsoft/azure-maven-plugins#1025]
### Plugin name and version
azure-webapp-maven-plugin
1.9.0

### Plugin configuration in your `pom.xml`
```
  <plugin> 
	<groupId>com.microsoft.azure</groupId>  
	<artifactId>azure-webapp-maven-plugin</artifactId>  
	<version>1.9.0</version>  
	<configuration>
	  <schemaVersion>V2</schemaVersion>
	  <resourceGroup>...</resourceGroup>
	  <appName>...</appName>
	  <pricingTier>F1</pricingTier>
	  <region>westeurope</region>
	  <runtime>
		<os>linux</os>
		<javaVersion>java11</javaVersion>
		<webContainer>java11</webContainer>
	  </runtime>
	  <deployment>
		<resources>
		  <resource>
			<directory>${project.basedir}/target</directory>
			<includes>
			  <include>*.jar</include>
			</includes>
		  </resource>
		</resources>
	  </deployment>
	</configuration>
  </plugin> 
```

### Expected behavior
Deployment behind a proxy with password should work if maven settings.xml is configured with proxy details and credentials in `<proxies></proxies>` as follows:
`mvn azure-webapp:deploy`

### Actual behavior
Running
`mvn azure-webapp:deploy`
fails with:
```
[INFO] Auth Type : AZURE_AUTH_MAVEN_PLUGIN, Auth Files : [C:\path\to\azure-secret.json]
[INFO] [Correlation ID: ....] Instance discovery was successful
[ERROR] [Correlation ID: ...] Execution of class com.microsoft.aad.adal4j.AcquireTokenCallable failed.
java.net.UnknownHostException: login.microsoftonline.com
```

### Steps to reproduce the problem
Run following from behind a proxy:
`mvn azure-webapp:deploy`

Deployment suceeds when running with identical setup from a free internet connection.

**Comment by pan1394** [comment]
append proxy conf like this.
mvn azure-webapp:deploy -DproxySet=true -DproxyHost=xxx.xxx.x.x -DproxyPort=xx

**Comment by oakieoaktree** [comment]
> mvn azure-webapp:deploy -DproxySet=true -DproxyHost=xxx.xxx.x.x -DproxyPort=xx

Thank you for this. Are there parameters for proxy user name and password (for a password protected proxy)?

**Comment by pan1394** [comment]
> > mvn azure-webapp:deploy -DproxySet=true -DproxyHost=xxx.xxx.x.x -DproxyPort=xx
> 
> Thank you for this. Are there parameters for proxy user name and password (for a password protected proxy)?

all these are java system properties, 
I think this post in stackoverflow can help u.
https://stackoverflow.com/questions/1626549/authenticated-http-proxy-with-java

**Comment by Flanker32** [comment]
@pan1394  Thanks a lot for your help.

@oakieoaktree really sorry for the late reply, is there anything more questions?
