### ISSUE TITLE
There is no artifact to deploy in staging directory

### ISSUE THREAD

**Issue by dharm187** [microsoft/azure-maven-plugins#1032]
### Plugin name and version
azure-webapp-maven-plugin 1.9.0

### Plugin configuration in your `pom.xml`
`<plugin> 
        <groupId>com.microsoft.azure</groupId>  
        <artifactId>azure-webapp-maven-plugin</artifactId>  
        <version>1.9.0</version>  
        <configuration>
          <schemaVersion>V2</schemaVersion>  
          <resourceGroup>XXXX</resourceGroup>  
          <appName>XXXX</appName>  
          <region>australiasoutheast</region>  
          <pricingTier>P1V2</pricingTier>  
            
          <appSettings> 
            <property> 
              <name>JAVA_OPTS</name>  
              <value>-Dserver.port=80</value> 
            </property> 
          </appSettings>  
            
          <runtime> 
            <os>linux</os>  
            <javaVersion>jre8</javaVersion>  
            <webContainer>TOMCAT 8.5</webContainer> 
          </runtime>  
          <deployment> 
            <resources> 
              <resource> 
                <directory>${project.basedir}/target</directory>
                <targetPath>/test/xyz</targetPath>
                <includes> 
                  <include>*.war</include> 
                </includes> 
              </resource> 
            </resources> 
          </deployment>
        </configuration> 
      </plugin> `

### Expected behavior
War should be deployed
### Actual behavior
Gettting error as below:
[ERROR] Failed to execute goal com.microsoft.azure:azure-webapp-maven-plugin:1.9.0:deploy (default-cli) on project XXXXX: There is no artifact to deploy in staging directory: 'C:\ABC\XYZ\target\azure-webapp\xxxx-4734d985-9074-4867-bd18-f3cd647512f9' -> [Help 1]
### Steps to reproduce the problem
Include the target Path in the pom.xml. Without targetPath the deployment is successful

**Comment by Flanker32** [comment]
@dharm187 Thanks for your report, we have fixed this issue and release webappp maven plugin 1.9.1, you may find the [release note](https://github.com/microsoft/azure-maven-plugins/releases/tag/azure-webapp-maven-plugin-1.9.1) here, sorry for the inconvenience.
