### ISSUE TITLE
How could I resolve to Failed to execute goal com.microsoft.azure:azure-webapp-maven-plugin

### ISSUE THREAD

**Issue by ntelsbschoi** [microsoft/azure-maven-plugins#1042]
### Plugin name and version

azure-webapp-maven-plugin 1.4.1

### Plugin configuration in your `pom.xml`

			<plugin>
				<groupId>com.microsoft.azure</groupId>
				<artifactId>azure-webapp-maven-plugin</artifactId>
				<version>1.4.1</version>
				<configuration>
			              <resourceGroup>${azure.resourceGroup}</resourceGroup>
			              <appName>${azure.appName}</appName>
			              <region>${azure.region}</region>
			              <deploymentType>war</deploymentType>
			
			              
			              <javaVersion>1.8</javaVersion>
			              <javaWebContainer>tomcat 8.5</javaWebContainer>
			 
			              <warFile>${project.basedir}/target/ROOT.war</warFile>
			              <path>/</path>
			              <deploymentSlot><name>${azure.appName}-slot-one</name></deploymentSlot>
			               
			     
                   			              
				</configuration>
			</plugin>            
        </plugins>
    </build>

    <profiles>
    	<profile>
    		<id>local</id>
    		<properties>
    			<spring.profiles.avtive>local</spring.profiles.avtive>
    			<server.mode>local</server.mode>
    		</properties>
    		<activation>
    			<activeByDefault>true</activeByDefault>
    		</activation>
    	</profile>
    	<profile>
    		<id>dev</id>
    		<properties>
    			<spring.profiles.avtive>dev</spring.profiles.avtive>
    			<server.mode>dev</server.mode>
    			<azure.resourceGroup>SKT-PCC-DEV</azure.resourceGroup>
    			<azure.appName>pcc-dev-api-v001-core</azure.appName>
    			<azure.region>koreasouth</azure.region>
    		</properties>
    	</profile>
    	<profile>
    		<id>stg</id>
    		<properties>
    			<spring.profiles.avtive>stg</spring.profiles.avtive>
    			<server.mode>stg</server.mode>
    			<azure.resourceGroup>SKT-PCC-STG</azure.resourceGroup>
    			<azure.appName>pcc-stg-api-v001-core</azure.appName>
    			<azure.region>koreasouth</azure.region>
    		</properties>
    	</profile>
    	<profile>
    		<id>prd</id>
    		<properties>
    			<spring.profiles.avtive>prd</spring.profiles.avtive>
    			<server.mode>prd</server.mode>
    			<azure.resourceGroup>SKT-PCC-PRD</azure.resourceGroup>
    			<azure.appName>pcc-prd-api-v001-core</azure.appName>
    			<azure.region>koreasouth</azure.region>
    		</properties>
    	</profile>
    </profiles>

### Expected behavior

normal deploy

### Actual behavior

[ERROR] Failed to execute goal com.microsoft.azure:azure-webapp-maven-plugin:1.4.1:deploy (default-cli) on project core: The Web App specified in pom.xml does not exist. Please make sure the Web App name is correct. -> [Help 1]

### Steps to reproduce the problem

[DEBUG] Configuring mojo com.microsoft.azure:azure-webapp-maven-plugin:1.4.1:deploy from plugin realm ClassRealm[plugin>com.microsoft.azure:azure-webapp-maven-plugin:1.4.1, parent: sun.misc.Launcher$AppClassLoader@7d4991ad]
[DEBUG] Configuring mojo 'com.microsoft.azure:azure-webapp-maven-plugin:1.4.1:deploy' with basic configurator -->
[DEBUG]   (f) allowTelemetry = true
[DEBUG]   (f) appName = pcc-dev-api-v001-core
[DEBUG]   (f) buildDirectory = /var/lib/jenkins/workspace/PCC-DEV-CORE/target
[DEBUG]   (s) name = pcc-dev-api-v001-core-slot-one
[DEBUG]   (f) deploymentSlotSetting = com.microsoft.azure.maven.webapp.configuration.DeploymentSlotSetting@637a28b4
[DEBUG]   (f) deploymentType = war
[DEBUG]   (f) failsOnError = true
[DEBUG]   (f) httpProxyPort = 80
[DEBUG]   (f) javaVersion = 1.8
[DEBUG]   (f) javaWebContainer = tomcat 8.5
[DEBUG]   (f) path = /
[DEBUG]   (f) plugin = Component Descriptor: role: 'org.apache.maven.plugin.Mojo', implementation: 'com.microsoft.azure.maven.webapp.DeployMojo', role hint: 'com.microsoft.azure:azure-webapp-maven-plugin:1.4.1:deploy'
role: 'org.apache.maven.plugin.Mojo', implementation: 'com.microsoft.azure.maven.webapp.HelpMojo', role hint: 'com.microsoft.azure:azure-webapp-maven-plugin:1.4.1:help'
---
[DEBUG]   (f) pricingTier = S1
[DEBUG]   (f) project = MavenProject: com.skt:core:1.0.0-BUILD-SNAPSHOT @ /var/lib/jenkins/workspace/PCC-DEV-CORE/pom.xml
[DEBUG]   (f) region = koreasouth
[DEBUG]   (f) resourceGroup = SKT-PCC-DEV
[DEBUG]   (s) runtime = com.microsoft.azure.maven.webapp.configuration.RuntimeSetting@6d8a6ca
[DEBUG]   (f) session = org.apache.maven.execution.MavenSession@5c10285a
[DEBUG]   (f) settings = org.apache.maven.execution.SettingsAdapter@deeb390
[DEBUG]   (f) skip = false
[DEBUG]   (f) stopAppDuringDeployment = false
[DEBUG]   (f) warFile = /var/lib/jenkins/workspace/PCC-DEV-CORE/target/ROOT.war
[DEBUG] -- end configuration --
AI: INFO 18-03-2020 08:27, 1: Configuration file has been successfully found as resource
AI: INFO 18-03-2020 08:27, 1: Configuration file has been successfully found as resource
[INFO] Authenticate with Azure CLI 2.0
Please login in Azure CLI and press any key to continue after you've successfully logged in.
[INFO] --> GET https://management.azure.com/subscriptions/50a28d1a-676b-4200-913c-f7bc9fb2210c/resourceGroups/SKT-PCC-DEV/providers/Microsoft.Web/sites/pcc-dev-api-v001-core?api-version=2018-02-01
[INFO] Accept-Encoding: gzip
[INFO] accept-language: en-US
[INFO] Authorization: Bearer null
[INFO] Connection: Keep-Alive
[INFO] Content-Type: application/json; charset=utf-8
[INFO] Host: management.azure.com
[INFO] User-Agent: azure-webapp-maven-plugin/1.4.1 installationId:6c424859f7643a9bf68d508c78675fed9f4db8705c60dd019caf6f285fa0e0d5 sessionId:9f551d97-4f33-4a8d-a624-656a4ed46012 Azure-SDK-For-Java/1.15.1 OS:Linux/4.15.0-1057-azure MacAddressHash:78ec16205d2d67b7652bc650bb16628939a327b53b2b71bee1637755adbbf1a7 Java:1.8.0_242 (WebSiteManagementClient, 2018-02-01)
[INFO] x-ms-client-request-id: 0ce2fd14-88b3-4ef9-84b2-4018c56398b6
[INFO] <-- 401 Unauthorized https://management.azure.com/subscriptions/50a28d1a-676b-4200-913c-f7bc9fb2210c/resourceGroups/SKT-PCC-DEV/providers/Microsoft.Web/sites/pcc-dev-api-v001-core?api-version=2018-02-01 (14 ms, 88-byte body)
[INFO] Cache-Control: no-cache
[INFO] Connection: close
[INFO] Content-Length: 88
[INFO] Content-Type: application/json; charset=utf-8
[INFO] Date: Wed, 18 Mar 2020 08:27:40 GMT
[INFO] Expires: -1
[INFO] Pragma: no-cache
[INFO] Strict-Transport-Security: max-age=31536000; includeSubDomains
[INFO] WWW-Authenticate: Bearer authorization_uri="https://login.windows.net/1dff78d1-287c-4cbe-9cda-240bb1f54c46", error="invalid_token", error_description="The access token is invalid."
[INFO] X-Content-Type-Options: nosniff
[INFO] x-ms-correlation-request-id: 41e14463-30fa-4ec7-a457-f91944fde6dc
[INFO] x-ms-failure-cause: gateway
[INFO] x-ms-request-id: 41e14463-30fa-4ec7-a457-f91944fde6dc
[INFO] x-ms-routing-request-id: KOREASOUTH:20200318T082740Z:41e14463-30fa-4ec7-a457-f91944fde6dc
[INFO] 88-byte body:
{"error":{"code":"InvalidAuthenticationToken","message":"The access token is invalid."}}
[INFO] <-- END HTTP
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 20.261 s
[INFO] Finished at: 2020-03-18T08:27:41+00:00
[INFO] Final Memory: 67M/427M
[INFO] ------------------------------------------------------------------------

**Comment by Flanker32** [comment]
@ntelsbschoi Thanks for your report and sorry for the late reply, this seems to be an auth issue according to the log, and webapp maven plugin will use azure cli credential by default. Could you please try `az login` in the deploy machine and try again?
