### ISSUE TITLE
Azure Function Maven Plugin fails to package

### ISSUE THREAD

**Issue by graemerocher** [microsoft/azure-maven-plugins#1051]
### Plugin name and version

`azure-functions-maven-plugin` version `1.3.4`

### Plugin configuration in your `pom.xml`

```xml
<plugin>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-functions-maven-plugin</artifactId>
    <version>${azure.functions.maven.plugin.version}</version>
</plugin>
```

### Expected behavior

Should package. The equivalent Gradle plugin doesn't exhibit the problem.

### Actual behavior

Fails to package with:

```
[ERROR] Failed to execute goal com.microsoft.azure:azure-functions-maven-plugin:1.3.4:package (package-functions) on project azure-functions-example: Can't resolve member named invoke for class example.Function -> [Help 1]
[ERROR]
```

The stacktrace is:

```
Caused by: org.reflections.ReflectionsException: Can't resolve member named invoke for class example.Function
	at org.reflections.util.Utils.getMemberFromDescriptor(Utils.java:94)
	at org.reflections.util.Utils.getMethodsFromDescriptors(Utils.java:101)
	at org.reflections.Reflections.getMethodsAnnotatedWith(Reflections.java:482)
	at com.microsoft.azure.maven.function.handlers.AnnotationHandlerImpl.findFunctions(AnnotationHandlerImpl.java:50)
	at com.microsoft.azure.maven.function.PackageMojo.findAnnotatedMethods(PackageMojo.java:135)
	at com.microsoft.azure.maven.function.PackageMojo.doExecute(PackageMojo.java:87)
	at com.microsoft.azure.maven.AbstractAzureMojo.execute(AbstractAzureMojo.java:309)
```

### Steps to reproduce the problem

```
git clone git@github.com:micronaut-projects/micronaut-azure.git
cd examples/azure-functions-example
./mvnw clean package azure-functions:run
```

Note the error. Now try:

```
../gradlew clean azureFunctionsRun
```

Note that with Gradle the problem doesn't exist.

**Comment by graemerocher** [comment]
Seems the root cause is a `java.lang.ClassNotFoundException: io.micronaut.servlet.http.ServletHttpHandler` which is in one of the dependent projects. Could be that the plugin is not using the complete classpath when trying to load the method.

**Comment by graemerocher** [comment]
yes it seems that the plugin is using `compile` scope only dependencies to build the classpath and not including runtime dependencies which seems to be unsafe for what it is trying to do.

**Comment by graemerocher** [comment]
I was able to workaround the issue by declaring an additional dependency in `compile` scope but this shouldn't be necessary as it isn't necessary for Gradle:

https://github.com/micronaut-projects/micronaut-azure/commit/68f97be40f8a57c0589535d6f175fbd58f7c1eb4#diff-4eacb021ef330b901adfb2cd27e1252dR74

**Comment by Flanker32** [comment]
@graemerocher Thanks a lot for your contribution and sorry for the late reply, we will review the pr and fix it soon.

**Comment by graemerocher** [comment]
Thanks! Do you know when the next release will be?

**Comment by Flanker32** [comment]
@graemerocher We planed to release the new version in our next sprint (Around third week of May),
