### ISSUE TITLE
Azure Functions supporting JDK 11

### ISSUE THREAD

**Issue by muneeba-mughal** [microsoft/azure-maven-plugins#1052]
I would really like to know if there is already a support for JDK 11. The issues regarding this do not have any update or follow through which is unfortunate.

### Plugin name and version
azure-functions-maven-plugin:1.3.2

### Plugin configuration in your `pom.xml`
1.3.2

### Actual behavior
<img width="1680" alt="Screenshot 2020-04-09 at 11 16 12" src="https://user-images.githubusercontent.com/49693041/78879039-a22db480-7a53-11ea-8beb-bd0139746e3e.png">

### Steps to reproduce the problem
- Add azure-functions-kotlin-archeype:1.23 to IntelliJ IDEA
- Generate an Azure Functions archetype
- Add the corresponding trigger function
- Run function host locally
- Trigger functions

**Comment by Flanker32** [comment]
@muneeba-mughal Thanks for your support, Java 11 function is not supported yet, but we have planed this item and will update here once there are updates.

**Comment by Flanker32** [comment]
@muneeba-mughal Thanks for your support, Java 11 Function has been supported now, you may get the release notes [here](https://github.com/microsoft/azure-maven-plugins/releases/tag/azure-functions-maven-plugin-1.6.0); besides, please update the function-core-tools to the latest version for running function locally, you may find the guidance [here](https://github.com/Azure/azure-functions-core-tools#installing)
