### ISSUE TITLE
Why changes to Maven Java archetype???

### ISSUE THREAD

**Issue by TurtleBeach** [microsoft/azure-maven-plugins#1053]
### Steps to reproduce the problem Simply create new Java HTTP trigger template:
`mvn archetype:generate -DarchetypeGroupId=com.microsoft.azure -DarchetypeArtifactId=azure-functions-archetype`

Almost 1 year ago, after I thought the maven archetype was finally stable, I made (and documented, so others in our small group who were new to functions could use it) a simple batch file that started maven archetype generation). At the time, the process displayed Region and Function App Name for confirmation and they could be changed from the default values; if changes were made, they were reflected in the final pom. Meaning, open Visual Studio Code and begin working on substance, without needing to manually edit the pom. (And I use the batch file because even using latest VS Code makes generating a basic template even more aggravating when deploying the first time).

Now (and I am not sure when it changed) those two properties are set to default values, meaning the pom that is produced has to be manually edited if defaults are wrong (and for me they are ALWAYS wrong).

I do not understand why MS continually finds it necessary to change processes for no apparent reason, I at least casually follow these maven threads, and I do not recall EVER seeing ANYONE asking for something to be removed. I DO however see lots of requests to expose various options so that users have more control.

So who decided that allowing Region and App Name to be set when the function template is created should be removed, and why??

Somebody had to consciously and deliberately remove code that worked. It boggles the mind,
Jack AKA TurtleBeach.

**Comment by Flanker32** [comment]
@TurtleBeach Thanks for your support, we sync with the service team and decide to reduce the parameters in archetype to reduce the steps in archetype creation, really sorry for the inconvenience caused by the archetype change, could you please try `-DarchetypeVersion` to specify the archetype version in batch job?

**Comment by Flanker32** [comment]
@TurtleBeach We have released new version of function archetype which add the Azure back as batch parameters, you may get the release notes [here](https://github.com/microsoft/azure-maven-archetypes/releases/tag/azure-functions-archetype-1.27)
