### ISSUE TITLE
Documentation error for the Azure Spring Cloud Maven plugin

### ISSUE THREAD

**Issue by jdubois** [microsoft/azure-maven-plugins#1059]
As this is in the Wiki, I (sadly) cannot send you a PR.

On page https://github.com/microsoft/azure-maven-plugins/wiki/Azure-Spring-Cloud:-Deploy

You have an example with `<runtimeVersion>8</runtimeVersion>`. This will cause a warning when running the plugin.

The correct option is `<runtimeVersion>Java8</runtimeVersion>`.

Besides, you should add in the documentation that there are 2 available options, `Java8` and `Java11`.

It's important as they are different from the ones you have when using the `az spring-cloud` command line (it's `java_8` and `java_11` when using the command line).

**Comment by Flanker32** [comment]
@jdubois Thanks a lot for your help, has updated the document!
