### ISSUE TITLE
Allow for specification of resource group name during setup and in pom.xml

### ISSUE THREAD

**Issue by JonathanGiles** [Microsoft/azure-maven-plugins#109]
There should be tooling support when using Maven to create a new function to specify the resource group name. This could be asked as part of the archetype setup process, and offer a default of the existing 'java-functions-group'. I note that there is already support for specifying the resource group in the generated pom.xml file, so extending this to ask during the archetype setup should hopefully not be too burdensome.

I ask because when I create a few test projects I quickly end up with a mess of services all in the ‘java-functions-group’, and it makes it very hard to tell which resources belong to which function.

**Comment by jdneo** [comment]
@JonathanGiles Thanks for the feedback. Since this is an issue related with the archetype. Would you mind to create a new issue at https://github.com/Microsoft/azure-maven-archetypes?

**Comment by jdneo** [comment]
Hi @JonathanGiles . Thanks for the feedback. I'll close this issue since its an archetype issue and we already have an issue tracking on that.

Please feel free to reopen it if you have other request.

**Comment by JonathanGiles** [comment]
Thanks for the link - I missed that when searching.
