### ISSUE TITLE
Create more human-friendly names for associated services

### ISSUE THREAD

**Issue by JonathanGiles** [microsoft/azure-maven-plugins#110]
Can we get better default naming for the associated services? E.g. if I create a function with name ‘cda-dash-20180306183328080’, it’s annoying that the app service plan and storage account have hexadecimal names (e.g. 4d6a4bec396242779c5e), rather than something more sane, e.g. ‘cda-dash-20180306183328080-storage’.
 
The nice thing about this is that if a standard naming scheme was in practice, I wouldn’t have to upload my function using maven, wait to see what the hex names are, and then re-upload my app so that it can use the storage account – I could reasonably guess it in advance.

**Comment by jdneo** [comment]
Yes, I agree that with standard naming scheme, user can easily guess it in advance. But it will also increase the posibility of creation failure because of the duplicated dns name. Could you please help describe more about the usage scenario?

@hexiaokai What do you think about this?

**Comment by JonathanGiles** [comment]
I thought there might be a concern about naming collisions. Is it possible for you to query if the name exists, and if it does create the service with a -1, -2, etc?

**Comment by jdneo** [comment]
Emm, in the plugin code, we pass the app name to the Azure ava SDK to provision the resource:

https://github.com/Microsoft/azure-maven-plugins/blob/master/azure-functions-maven-plugin/src/main/java/com/microsoft/azure/maven/function/DeployMojo.java#L123

I'm not sure if it is possible to specify the appservice plan name now in the Azure Java SDK.

**Comment by PramodValavala-MSFT** [comment]
There was a similar request at MicrosoftDocs/azure-docs#19298 for which I found that there is a provision to use an **existing** App Service Plan by setting this configuration to the maven plugin as mentioned in the [README](https://github.com/Microsoft/azure-maven-plugins/blob/develop/azure-functions-maven-plugin/README.md)
```xml
<appServicePlanName>${functionAppServicePlanName}</appServicePlanName>
```
assuming a property with the same name is defined in `pom.xml`

Currently, the code at this [line](https://github.com/Microsoft/azure-maven-plugins/blob/master/azure-functions-maven-plugin/src/main/java/com/microsoft/azure/maven/function/DeployMojo.java#L89) creates a new app service plan if the above configuration is not set.
But if it is set, it tries to use an existing plan without really checking if it exists.

Unfortunately, looking at the Java SDK, the [functions](https://github.com/Azure/azure-libraries-for-java/blob/master/azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/implementation/FunctionAppImpl.java#L158) / [appservice](https://github.com/Azure/azure-libraries-for-java/blob/master/azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/implementation/AppServiceBaseImpl.java#L398) implementation doesn't allow for passing a name when creating the app service plan **but** is possible in general as evident from this [code](https://github.com/Azure/azure-libraries-for-java/blob/master/azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/implementation/AppServiceBaseImpl.java#L376).

On the bright side, storage account does seem to be possible as available [here](https://github.com/Azure/azure-libraries-for-java/blob/master/azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/implementation/FunctionAppImpl.java#L180) for new storage accounts with name and also existing ones.

**Comment by PramodValavala-MSFT** [comment]
Here is a [workaround](https://github.com/MicrosoftDocs/azure-docs/issues/30626#issuecomment-489511754) for this until its officially supported

> As a workaround, you could use the maven plugin just for building and then use `func` to deploy.
> 
> > I assume you've already created a function app as documented in the [Azure CLI Quickstart](https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-azure-function-azure-cli).
> 
> 1. Build the app
> 
> ```shell
> mvn clean package
> ```
> 
> 1. Use `func` to publish
> 
> ```shell
> # Change to the staging directory
> cd target/azure-functions/<appName>
> # Would be something like this - cd target/azure-functions/<artifactId>-20190506045816127
> 
> # Deploy using func
> func azure functionapp <FunctionAppName>
> ```
