### ISSUE TITLE
Register resource providers before function create

### ISSUE THREAD

**Issue by jeffhollan** [microsoft/azure-maven-plugins#1101]
People using the maven extension to create their first function have reported hitting errors about Microsoft.Insights not being a registered resource provider: https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-providers-and-types

Would be good if the mvn command to create a function checked and registered for this type if it hasn’t already been.  It’s possible other resource providers may need to be registered (Microsoft.Storage, Microsoft.Web), but this is the one people report first and foremost

**Comment by jdubois** [comment]
Thanks @jeffhollan - I have linked my original issue above.
