### ISSUE TITLE
Required class missing when executing "mvn clean package azure-functions:run"

### ISSUE THREAD

**Issue by ssampigegithub** [microsoft/azure-maven-plugins#1102]
### Plugin name and version
azure-functions-maven-plugin version 1.6.0

### Plugin configuration in your `pom.xml`
See attached zip file that contains full source

### Expected behavior
Function should have run successfully as per example in - https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-azure-function-azure-cli?tabs=bash%2Cbrowser&pivots=programming-language-java

### Actual behavior
------------------------
I get the following error
[DEBUG]   (f) session = org.apache.maven.execution.MavenSession@7048f722
[DEBUG]   (f) settings = org.apache.maven.execution.SettingsAdapter@1ea930eb
[DEBUG]   (f) skip = false
[DEBUG] -- end configuration --
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  18.732 s
[INFO] Finished at: 2020-07-14T16:55:29-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.microsoft.azure:azure-functions-maven-plugin:1.6.0:package (package-functions) on project helloworldfunction: Execution package-functions of goal com.microsoft.azure:azure-functions-maven-plugin:1.6.0:package failed: A required class was missing while executing com.microsoft.azure:azure-functions-maven-plugin:1.6.0:package: com/microsoft/applicationinsights/internal/channel/common/ApacheSenderFactory
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.microsoft.azure:azure-functions-maven-plugin:1.6.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/C:/Users/ssampige/.m2/repository/com/microsoft/azure/azure-functions-maven-plugin/1.6.0/azure-functions-maven-plugin-1.6.0.jar
[ERROR] urls[1] = file:/C:/Users/ssampige/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
[ERROR] urls[2] = file:/C:/Users/ssampige/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.0/org.eclipse.sisu.inject-0.3.0.jar
[ERROR] urls[3] = file:/C:/Users/ssampige/.m2/repository/org/apache/maven/maven-builder-support/3.3.3/maven-builder-support-3.3.3.jar
[ERROR] urls[4] = file:/C:/Users/ssampige/.m2/repository/org/eclipse/aether/aether-util/1.0.2.v20150114/aether-util-1.0.2.v20150114.jar
[ERROR] urls[5] = file:/C:/Users/ssampige/.m2/repository/org/sonatype/sisu/sisu-guice/3.2.5/sisu-guice-3.2.5-no_aop.jar
[ERROR] urls[6] = file:/C:/Users/ssampige/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
[ERROR] urls[7] = file:/C:/Users/ssampige/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.21/plexus-interpolation-1.21.jar
--------------------------------

### Steps to reproduce the problem

set JAVA_HOME=C:\apps\jdk1.8.0_111
mvn -e -X azure-webapp:deploy

Source code attached if you want to try it. Note that the project was created by following the example https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-azure-function-azure-cli?tabs=bash%2Cbrowser&pivots=programming-language-java 

[helloworldfunction.zip](https://github.com/microsoft/azure-maven-plugins/files/4922143/helloworldfunction.zip)

**Comment by Flanker32** [comment]
@ssampigegithub I run try to reproduce this issue by `mvn clean package azure-functions:run` but it works fine, it seems that the dependency library is broken, could you please try clean up the application insights library in your .m2 repository `${user.home}\.m2\repository\com\microsoft\azure\applicationinsights-core` and try again?

**Comment by ssampigegithub** [comment]
Thanks. That worked.
