### ISSUE TITLE
Receiving issue when doing mvn clean package or other steps

### ISSUE THREAD

**Issue by rrbbss77** [microsoft/azure-maven-plugins#1103]
Tried to follow this: https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-vs-code?pivots=programming-language-java

I checked all version of JAVA and Maven and they all look good.

[ERROR] Failed to execute goal com.microsoft.azure:azure-functions-maven-plugin:1.6.0:package (package-functions) on project myFunction: Execution package-functions of goal com.microsoft.azure:azure-functions-maven-plugin:1.6.0:package failed: A required class was missing while executing com.microsoft.azure:azure-functions-maven-plugin:1.6.0:package: org/reflections/Configuration
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.microsoft.azure:azure-functions-maven-plugin:1.6.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/Users/rajat/.m2/repository/com/microsoft/azure/azure-functions-maven-plugin/1.6.0/azure-functions-maven-plugin-1.6.0.jar
[ERROR] urls[1] = file:/Users/rajat/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
[ERROR] urls[2] = file:/Users/rajat/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.0/org.eclipse.sisu.inject-0.3.0.jar
[ERROR] urls[3] = file:/Users/rajat/.m2/repository/org/apache/maven/maven-builder-support/3.3.3/maven-builder-support-3.3.3.jar
[ERROR] urls[4] = file:/Users/rajat/.m2/repository/org/eclipse/aether/aether-util/1.0.2.v20150114/aether-util-1.0.2.v20150114.jar
[ERROR] urls[5] = file:/Users/rajat/.m2/repository/org/sonatype/sisu/sisu-guice/3.2.5/sisu-guice-3.2.5-no_aop.jar
[ERROR] urls[6] = file:/Users/rajat/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
[ERROR] urls[7] = file:/Users/rajat/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.21/plexus-interpolation-1.21.jar
[ERROR] urls[8] = file:/Users/rajat/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[9] = file:/Users/rajat/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[10] = file:/Users/rajat/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[11] = file:/Users/rajat/.m2/repository/org/codehaus/plexus/plexus-utils/3.3.0/plexus-utils-3.3.0.jar
[ERROR] urls[12] = file:/Users/rajat/.m2/repository/com/microsoft/azure/azure-maven-plugin-lib/1.2.16/azure-maven-plugin-lib-1.2.16.jar
[ERROR] urls[13] = file:/Users/rajat/.m2/repository/org/apache/commons/commons-collections4/4.4/commons-collections4-4.4.jar
[ERROR] urls[14] = file:/Users/rajat/.m2/repository/org/apache/maven/shared/maven-filtering/3.0.0/maven-filtering-3.0.0.jar
[ERROR] urls[15] = file:/Users/rajat/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.0.0/maven-shared-utils-3.0.0.jar
[ERROR] urls[16] = file:/Users/rajat/.m2/repository/com/google/code/findbugs/jsr305/2.0.1/jsr305-2.0.1.jar
[ERROR] urls[17] = file:/Users/rajat/.m2/repository/org/sonatype/plexus/plexus-build-api/0.0.7/plexus-build-api-0.0.7.jar
[ERROR] urls[18] = file:/Users/rajat/.m2/repository/com/microsoft/azure/applicationinsights-core/2.6.1/applicationinsights-core-2.6.1.jar
[ERROR] urls[19] = file:/Users/rajat/.m2/repository/com/microsoft/azure/azure-tools-common/0.4.0/azure-tools-common-0.4.0.jar
[ERROR] urls[20] = file:/Users/rajat/.m2/repository/com/microsoft/azure/applicationinsights/v2015_05_01/azure-mgmt-insights/1.0.0-beta/azure-mgmt-insights-1.0.0-beta.jar
[ERROR] urls[21] = file:/Users/rajat/.m2/repository/com/microsoft/azure/azure/1.35.0/azure-1.35.0.jar
[ERROR] urls[22] = file:/Users/rajat/.m2/repository/com/microsoft/azure/azure-client-runtime/1.7.0/azure-client-runtime-1.7.0.jar
[ERROR] urls[23] = file:/Users/rajat/.m2/repository/com/microsoft/azure/azure-mgmt-resources/1.35.0/azure-mgmt-resources-1.35.0.jar
[ERROR] urls[24] = file:/Users/rajat/.m2/repository/io/reactivex/rxjava/1.3.8/rxjava-1.3.8.jar
[ERROR] urls[25] = file:/Users/rajat/.m2/repository/com/microsoft/azure/azure-mgmt-storage/1.35.0/azure-mgmt-storage-1.35.0.jar
[ERROR] urls[26] = file:/Users/rajat/.m2/repository/com/microsoft/azure/azure-mgmt-network/1.35.0/azure-mgmt-network-1.35.0.jar
[ERROR] urls[27] = file:/Users/rajat/.m2/repository/com/microsoft/azure/azure-mgmt-compute/1.35.0/azure-mgmt-compute-1.35.0.jar
[ERROR] urls[28] = file:/Users/rajat/.m2/repository/com/microsoft/azure/azure-mgmt-graph-rbac/1.35.0/azure-mgmt-graph-rbac-1.35.0.jar
[ERROR] urls[29] = file:/Users/rajat/.m2/repository/com/microsoft/azure/azure-mgmt-keyvault/1.35.0/azure-mgmt-keyvault-1.35.0.jar
[ERROR] urls[30] = file:/Users/rajat/.m2/repository/com/microsoft/azure/azure-keyvault/1.0.0/azure-keyvault-1.0.0.jar
[ERROR] urls[31] = file:/Users/rajat/.m2/repository/com/microsoft/azure/azure-keyvault-webkey/1.0.0/azure-keyvault-webkey-1.0.0.jar
[ERROR] urls[32] = file:/Users/rajat/.m2/repository/com/microsoft/azure/azure-mgmt-batch/1.35.0/azure-mgmt-batch-1.35.0.jar
[ERROR] urls[33] = file:/Users/rajat/.m2/repository/com/microsoft/azure/azure-mgmt-trafficmanager/1.35.0/azure-mgmt-trafficmanager-1.35.0.jar
[ERROR] urls[34] = file:/Users/rajat/.m2/repository/com/microsoft/azure/azure-mgmt-dns/1.35.0/azure-mgmt-dns-1.35.0.jar
[ERROR] urls[35] = file:/Users/rajat/.m2/repository/com/microsoft/azure/azure-mgmt-redis/1.35.0/azure-mgmt-redis-1.35.0.jar
[ERROR] urls[36] = file:/Users/rajat/.m2/repository/com/microsoft/azure/azure-mgmt-appservice/1.35.0/azure-mgmt-appservice-1.35.0.jar
[ERROR] urls[37] = file:/Users/rajat/.m2/repository/com/microsoft/azure/azure-storage/6.1.0/azure-storage-6.1.0.jar
[ERROR] urls[38] = file:/Users/rajat/.m2/repository/com/microsoft/azure/azure-keyvault-core/0.8.0/azure-keyvault-core-0.8.0.jar
[ERROR] urls[39] = file:/Users/rajat/.m2/repository/com/microsoft/azure/azure-mgmt-locks/1.35.0/azure-mgmt-locks-1.35.0.jar
[ERROR] urls[40] = file:/Users/rajat/.m2/repository/javax/xml/bind/jaxb-api/2.3.0/jaxb-api-2.3.0.jar
[ERROR] urls[41] = file:/Users/rajat/.m2/repository/com/microsoft/azure/azure-mgmt-eventhub/1.35.0/azure-mgmt-eventhub-1.35.0.jar
[ERROR] urls[42] = file:/Users/rajat/.m2/repository/com/microsoft/azure/azure-mgmt-cdn/1.35.0/azure-mgmt-cdn-1.35.0.jar
[ERROR] urls[43] = file:/Users/rajat/.m2/repository/com/microsoft/azure/azure-mgmt-sql/1.35.0/azure-mgmt-sql-1.35.0.jar
[ERROR] urls[44] = file:/Users/rajat/.m2/repository/com/microsoft/azure/azure-mgmt-containerinstance/1.35.0/azure-mgmt-containerinstance-1.35.0.jar
[ERROR] urls[45] = file:/Users/rajat/.m2/repository/com/microsoft/azure/azure-mgmt-containerregistry/1.35.0/azure-mgmt-containerregistry-1.35.0.jar
[ERROR] urls[46] = file:/Users/rajat/.m2/repository/com/microsoft/azure/azure-mgmt-containerservice/1.35.0/azure-mgmt-containerservice-1.35.0.jar
[ERROR] urls[47] = file:/Users/rajat/.m2/repository/com/microsoft/azure/azure-mgmt-cosmosdb/1.35.0/azure-mgmt-cosmosdb-1.35.0.jar
[ERROR] urls[48] = file:/Users/rajat/.m2/repository/com/microsoft/azure/azure-mgmt-search/1.35.0/azure-mgmt-search-1.35.0.jar
[ERROR] urls[49] = file:/Users/rajat/.m2/repository/com/microsoft/azure/azure-mgmt-msi/1.35.0/azure-mgmt-msi-1.35.0.jar
[ERROR] urls[50] = file:/Users/rajat/.m2/repository/com/microsoft/azure/azure-mgmt-monitor/1.35.0/azure-mgmt-monitor-1.35.0.jar
[ERROR] urls[51] = file:/Users/rajat/.m2/repository/com/microsoft/azure/azure-mgmt-servicebus/1.35.0/azure-mgmt-servicebus-1.35.0.jar
[ERROR] urls[52] = file:/Users/rajat/.m2/repository/com/microsoft/azure/azure-mgmt-batchai/1.35.0/azure-mgmt-batchai-1.35.0.jar
[ERROR] urls[53] = file:/Users/rajat/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.9.10/jackson-dataformat-yaml-2.9.10.jar
[ERROR] urls[54] = file:/Users/rajat/.m2/repository/org/yaml/snakeyaml/1.23/snakeyaml-1.23.jar
[ERROR] urls[55] = file:/Users/rajat/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.9.10/jackson-core-2.9.10.jar
[ERROR] urls[56] = file:/Users/rajat/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.9.10.3/jackson-databind-2.9.10.3.jar
[ERROR] urls[57] = file:/Users/rajat/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.9.10/jackson-annotations-2.9.10.jar
[ERROR] urls[58] = file:/Users/rajat/.m2/repository/commons-io/commons-io/2.7/commons-io-2.7.jar
[ERROR] urls[59] = file:/Users/rajat/.m2/repository/com/google/errorprone/error_prone_core/2.4.0/error_prone_core-2.4.0.jar
[ERROR] urls[60] = file:/Users/rajat/.m2/repository/com/google/errorprone/error_prone_annotation/2.4.0/error_prone_annotation-2.4.0.jar
[ERROR] urls[61] = file:/Users/rajat/.m2/repository/com/google/errorprone/error_prone_type_annotations/2.4.0/error_prone_type_annotations-2.4.0.jar
[ERROR] urls[62] = file:/Users/rajat/.m2/repository/com/google/errorprone/error_prone_check_api/2.4.0/error_prone_check_api-2.4.0.jar
[ERROR] urls[63] = file:/Users/rajat/.m2/repository/com/googlecode/java-diff-utils/diffutils/1.3.0/diffutils-1.3.0.jar
[ERROR] urls[64] = file:/Users/rajat/.m2/repository/com/github/kevinstern/software-and-algorithms/1.0/software-and-algorithms-1.0.jar
[ERROR] urls[65] = file:/Users/rajat/.m2/repository/com/github/ben-manes/caffeine/caffeine/2.8.0/caffeine-2.8.0.jar
[ERROR] urls[66] = file:/Users/rajat/.m2/repository/org/checkerframework/checker-qual/2.10.0/checker-qual-2.10.0.jar
[ERROR] urls[67] = file:/Users/rajat/.m2/repository/org/pcollections/pcollections/2.1.2/pcollections-2.1.2.jar
[ERROR] urls[68] = file:/Users/rajat/.m2/repository/com/google/auto/auto-common/0.10/auto-common-0.10.jar
[ERROR] urls[69] = file:/Users/rajat/.m2/repository/com/google/code/findbugs/jFormatString/3.0.0/jFormatString-3.0.0.jar
[ERROR] urls[70] = file:/Users/rajat/.m2/repository/org/checkerframework/dataflow-shaded/3.1.2/dataflow-shaded-3.1.2.jar
[ERROR] urls[71] = file:/Users/rajat/.m2/repository/com/google/errorprone/javac/9+181-r4173-1/javac-9+181-r4173-1.jar
[ERROR] urls[72] = file:/Users/rajat/.m2/repository/com/google/auto/value/auto-value-annotations/1.7/auto-value-annotations-1.7.jar
[ERROR] urls[73] = file:/Users/rajat/.m2/repository/com/google/errorprone/error_prone_annotations/2.4.0/error_prone_annotations-2.4.0.jar
[ERROR] urls[74] = file:/Users/rajat/.m2/repository/com/google/protobuf/protobuf-java/3.4.0/protobuf-java-3.4.0.jar
[ERROR] urls[75] = file:/Users/rajat/.m2/repository/com/google/auto/service/auto-service-annotations/1.0-rc6/auto-service-annotations-1.0-rc6.jar
[ERROR] urls[76] = file:/Users/rajat/.m2/repository/org/threeten/threeten-extra/1.5.0/threeten-extra-1.5.0.jar
[ERROR] urls[77] = file:/Users/rajat/.m2/repository/org/zeroturnaround/zt-zip/1.14/zt-zip-1.14.jar
[ERROR] urls[78] = file:/Users/rajat/.m2/repository/org/apache/commons/commons-lang3/3.10/commons-lang3-3.10.jar
[ERROR] urls[79] = file:/Users/rajat/.m2/repository/com/google/code/gson/gson/2.8.6/gson-2.8.6.jar
[ERROR] urls[80] = file:/Users/rajat/.m2/repository/com/github/java-json-tools/json-schema-validator/2.2.14/json-schema-validator-2.2.14.jar
[ERROR] urls[81] = file:/Users/rajat/.m2/repository/com/github/java-json-tools/jackson-coreutils-equivalence/1.0/jackson-coreutils-equivalence-1.0.jar
[ERROR] urls[82] = file:/Users/rajat/.m2/repository/com/github/java-json-tools/jackson-coreutils/2.0/jackson-coreutils-2.0.jar
[ERROR] urls[83] = file:/Users/rajat/.m2/repository/com/github/java-json-tools/msg-simple/1.2/msg-simple-1.2.jar
[ERROR] urls[84] = file:/Users/rajat/.m2/repository/com/github/java-json-tools/btf/1.3/btf-1.3.jar
[ERROR] urls[85] = file:/Users/rajat/.m2/repository/com/github/java-json-tools/json-schema-core/1.2.14/json-schema-core-1.2.14.jar
[ERROR] urls[86] = file:/Users/rajat/.m2/repository/com/github/java-json-tools/uri-template/0.10/uri-template-0.10.jar
[ERROR] urls[87] = file:/Users/rajat/.m2/repository/org/mozilla/rhino/1.7.7.2/rhino-1.7.7.2.jar
[ERROR] urls[88] = file:/Users/rajat/.m2/repository/com/sun/mail/mailapi/1.6.2/mailapi-1.6.2.jar
[ERROR] urls[89] = file:/Users/rajat/.m2/repository/joda-time/joda-time/2.10.5/joda-time-2.10.5.jar
[ERROR] urls[90] = file:/Users/rajat/.m2/repository/com/googlecode/libphonenumber/libphonenumber/8.11.1/libphonenumber-8.11.1.jar
[ERROR] urls[91] = file:/Users/rajat/.m2/repository/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
[ERROR] urls[92] = file:/Users/rajat/.m2/repository/com/microsoft/azure/azure-arm-client-runtime/1.7.5/azure-arm-client-runtime-1.7.5.jar
[ERROR] urls[93] = file:/Users/rajat/.m2/repository/com/microsoft/rest/client-runtime/1.7.5/client-runtime-1.7.5.jar
[ERROR] urls[94] = file:/Users/rajat/.m2/repository/com/squareup/retrofit2/retrofit/2.6.4/retrofit-2.6.4.jar
[ERROR] urls[95] = file:/Users/rajat/.m2/repository/com/squareup/okhttp3/okhttp/3.12.12/okhttp-3.12.12.jar
[ERROR] urls[96] = file:/Users/rajat/.m2/repository/com/squareup/okio/okio/1.15.0/okio-1.15.0.jar
[ERROR] urls[97] = file:/Users/rajat/.m2/repository/com/squareup/okhttp3/logging-interceptor/3.12.12/logging-interceptor-3.12.12.jar
[ERROR] urls[98] = file:/Users/rajat/.m2/repository/com/squareup/okhttp3/okhttp-urlconnection/3.12.12/okhttp-urlconnection-3.12.12.jar
[ERROR] urls[99] = file:/Users/rajat/.m2/repository/com/squareup/retrofit2/converter-jackson/2.6.4/converter-jackson-2.6.4.jar
[ERROR] urls[100] = file:/Users/rajat/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-joda/2.10.1/jackson-datatype-joda-2.10.1.jar
[ERROR] urls[101] = file:/Users/rajat/.m2/repository/com/squareup/retrofit2/adapter-rxjava/2.6.4/adapter-rxjava-2.6.4.jar
[ERROR] urls[102] = file:/Users/rajat/.m2/repository/commons-net/commons-net/3.6/commons-net-3.6.jar
[ERROR] urls[103] = file:/Users/rajat/.m2/repository/com/microsoft/azure/azure-auth-helper/0.5.0/azure-auth-helper-0.5.0.jar
[ERROR] urls[104] = file:/Users/rajat/.m2/repository/com/microsoft/azure/azure-maven-plugin-common/0.2.0/azure-maven-plugin-common-0.2.0.jar
[ERROR] urls[105] = file:/Users/rajat/.m2/repository/org/eclipse/jetty/jetty-server/9.4.20.v20190813/jetty-server-9.4.20.v20190813.jar
[ERROR] urls[106] = file:/Users/rajat/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar
[ERROR] urls[107] = file:/Users/rajat/.m2/repository/org/eclipse/jetty/jetty-http/9.4.20.v20190813/jetty-http-9.4.20.v20190813.jar
[ERROR] urls[108] = file:/Users/rajat/.m2/repository/org/eclipse/jetty/jetty-util/9.4.20.v20190813/jetty-util-9.4.20.v20190813.jar
[ERROR] urls[109] = file:/Users/rajat/.m2/repository/org/eclipse/jetty/jetty-io/9.4.20.v20190813/jetty-io-9.4.20.v20190813.jar
[ERROR] urls[110] = file:/Users/rajat/.m2/repository/org/eclipse/jetty/jetty-servlet/9.4.20.v20190813/jetty-servlet-9.4.20.v20190813.jar
[ERROR] urls[111] = file:/Users/rajat/.m2/repository/org/eclipse/jetty/jetty-security/9.4.20.v20190813/jetty-security-9.4.20.v20190813.jar
[ERROR] urls[112] = file:/Users/rajat/.m2/repository/org/apache/httpcomponents/httpclient/4.5.9/httpclient-4.5.9.jar
[ERROR] urls[113] = file:/Users/rajat/.m2/repository/org/apache/httpcomponents/httpcore/4.4.11/httpcore-4.4.11.jar
[ERROR] urls[114] = file:/Users/rajat/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
[ERROR] urls[115] = file:/Users/rajat/.m2/repository/commons-codec/commons-codec/1.11/commons-codec-1.11.jar
[ERROR] urls[116] = file:/Users/rajat/.m2/repository/io/jsonwebtoken/jjwt/0.9.1/jjwt-0.9.1.jar
[ERROR] urls[117] = file:/Users/rajat/.m2/repository/com/microsoft/azure/azure-client-authentication/1.7.5/azure-client-authentication-1.7.5.jar
[ERROR] urls[118] = file:/Users/rajat/.m2/repository/com/microsoft/azure/adal4j/1.6.4/adal4j-1.6.4.jar
[ERROR] urls[119] = file:/Users/rajat/.m2/repository/com/nimbusds/oauth2-oidc-sdk/6.5/oauth2-oidc-sdk-6.5.jar
[ERROR] urls[120] = file:/Users/rajat/.m2/repository/com/sun/mail/javax.mail/1.6.1/javax.mail-1.6.1.jar
[ERROR] urls[121] = file:/Users/rajat/.m2/repository/javax/activation/activation/1.1/activation-1.1.jar
[ERROR] urls[122] = file:/Users/rajat/.m2/repository/com/github/stephenc/jcip/jcip-annotations/1.0-1/jcip-annotations-1.0-1.jar
[ERROR] urls[123] = file:/Users/rajat/.m2/repository/net/minidev/json-smart/2.3/json-smart-2.3.jar
[ERROR] urls[124] = file:/Users/rajat/.m2/repository/net/minidev/accessors-smart/1.2/accessors-smart-1.2.jar
[ERROR] urls[125] = file:/Users/rajat/.m2/repository/org/ow2/asm/asm/5.0.4/asm-5.0.4.jar
[ERROR] urls[126] = file:/Users/rajat/.m2/repository/com/nimbusds/lang-tag/1.5/lang-tag-1.5.jar
[ERROR] urls[127] = file:/Users/rajat/.m2/repository/com/nimbusds/nimbus-jose-jwt/8.19/nimbus-jose-jwt-8.19.jar
[ERROR] urls[128] = file:/Users/rajat/.m2/repository/com/microsoft/azure/azure-annotations/1.10.0/azure-annotations-1.10.0.jar
[ERROR] urls[129] = file:/Users/rajat/.m2/repository/jakarta/xml/bind/jakarta.xml.bind-api/2.3.2/jakarta.xml.bind-api-2.3.2.jar
[ERROR] urls[130] = file:/Users/rajat/.m2/repository/jakarta/activation/jakarta.activation-api/1.2.1/jakarta.activation-api-1.2.1.jar
[ERROR] urls[131] = file:/Users/rajat/.m2/repository/org/glassfish/jaxb/jaxb-runtime/2.3.2/jaxb-runtime-2.3.2.jar
[ERROR] urls[132] = file:/Users/rajat/.m2/repository/org/glassfish/jaxb/txw2/2.3.2/txw2-2.3.2.jar
[ERROR] urls[133] = file:/Users/rajat/.m2/repository/com/sun/istack/istack-commons-runtime/3.0.8/istack-commons-runtime-3.0.8.jar
[ERROR] urls[134] = file:/Users/rajat/.m2/repository/org/jvnet/staxex/stax-ex/1.8.1/stax-ex-1.8.1.jar
[ERROR] urls[135] = file:/Users/rajat/.m2/repository/com/sun/xml/fastinfoset/FastInfoset/1.2.16/FastInfoset-1.2.16.jar
[ERROR] urls[136] = file:/Users/rajat/.m2/repository/com/microsoft/azure/functions/azure-functions-java-library/1.3.1/azure-functions-java-library-1.3.1.jar
[ERROR] urls[137] = file:/Users/rajat/.m2/repository/org/reflections/reflections/0.9.11/reflections-0.9.11.jar
[ERROR] urls[138] = file:/Users/rajat/.m2/repository/com/google/guava/guava/20.0/guava-20.0.jar
[ERROR] urls[139] = file:/Users/rajat/.m2/repository/org/javassist/javassist/3.21.0-GA/javassist-3.21.0-GA.jar
[ERROR] urls[140] = file:/Users/rajat/.m2/repository/com/github/zafarkhaja/java-semver/0.9.0/java-semver-0.9.0.jar
[ERROR] urls[141] = file:/Users/rajat/.m2/repository/junit/junit/4.13/junit-4.13.jar
[ERROR] urls[142] = file:/Users/rajat/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
[ERROR] urls[143] = file:/Users/rajat/.m2/repository/org/jacoco/org.jacoco.agent/0.8.5/org.jacoco.agent-0.8.5-runtime.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------
[ERROR] : org.reflections.Configuration
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException

**Comment by rrbbss77** [comment]
I think I solved it with by adding the following dependency in POM.xml

  <dependency>
                        <groupId>org.reflections</groupId>
                        <artifactId>reflections</artifactId>
                        <version>0.9.10</version>
                    </dependency>


=========================
Here is the plugin portion in the POM:

  <plugin>
                <groupId>com.microsoft.azure</groupId>
                <artifactId>azure-functions-maven-plugin</artifactId>
                <version>${azure.functions.maven.plugin.version}</version>
                <configuration>
                    
                    <appName>${functionAppName}</appName>
                    
                    <resourceGroup>java-functions-group</resourceGroup>
                    
                    <appServicePlanName>java-functions-app-service-plan</appServicePlanName>
                    
                    
                    <region>westus</region>
                    
                    
                    
                    
                    
                    
                    
                    <runtime>
                        
                        <os>windows</os>
                        <javaVersion>8</javaVersion>
                        
                        
                        
                        
                    </runtime>
                    <appSettings>
                        <property>
                            <name>FUNCTIONS_EXTENSION_VERSION</name>
                            <value>~3</value>
                        </property>
                    </appSettings>
                </configuration>
                <dependencies>
                    
                    <dependency>
                        <groupId>org.reflections</groupId>
                        <artifactId>reflections</artifactId>
                        <version>0.9.10</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <id>package-functions</id>
                        <goals>
                            <goal>package</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

**Comment by Flanker32** [comment]
@rrbbss77 Thanks a lot for your report, i tried to reproduce this issue by create a function project in VSCode and run `mvn clean package` but it works fine, which seems like the library reflections in your local .m2 is broken, could you please try clean up it in `${user.home}\.m2\repository\org\reflections\reflections` and try again?
