### ISSUE TITLE
azure-functions:deploy failing with "OnError while emitting onNext value: retrofit2.Response.class"

### ISSUE THREAD

**Issue by ssampigegithub** [microsoft/azure-maven-plugins#1104]
### Plugin name and version
azure-functions-maven-plugin  1.6.0
### Plugin configuration in your `pom.xml`
See attached source code
### Expected behavior
Expect function to deploy successfully per sample in https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-azure-function-azure-cli?tabs=bash%2Cbrowser&pivots=programming-language-java
### Actual behavior
--------
[INFO] [Correlation ID: 4d4ddcc1-5957-4e10-89da-3daff36c5e70] Instance discovery was successful
[DEBUG] [Correlation ID: 4d4ddcc1-5957-4e10-89da-3daff36c5e70] Access Token and Refresh Token were returned
[INFO] Subscription : retailMgmt(845739df-78dd-4d05-9c57-21afecd45629)
[INFO] The specified function app does not exist. Creating a new function app...
[INFO] Set function worker runtime to java.
[INFO] Creating application insights...
[INFO] Successfully created the application insights $(artifactId)-$(timestamp) for this Function App. You can visit https://portal.azure.com/#resource/subscriptions/845739df-78dd-4d05-9c57-
21afecd45629/resourceGroups/java-functions-group/providers/microsoft.insights/components/$(artifactId)-$(timestamp)/overview to view your Application Insights component.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  47.107 s
[INFO] Finished at: 2020-07-14T21:10:10-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.microsoft.azure:azure-functions-maven-plugin:1.6.0:deploy (default-cli) on project helloworldfunction: Unknown error with status code 404 and body : OnErro
r while emitting onNext value: retrofit2.Response.class -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.microsoft.azure:azure-functions-maven-plugin:1.6.0:deploy (default-cli) on project helloworldfunction: Unknown error with status code 404 and body
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
...
...
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: retrofit2.Response.class
    at rx.exceptions.OnErrorThrowable.addValueAsLastCause (OnErrorThrowable.java:118)
    at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext (OnSubscribeMap.java:73)
    at retrofit2.adapter.rxjava.CallArbiter.deliverResponse (CallArbiter.java:120)
    at retrofit2.adapter.rxjava.CallArbiter.emitResponse (CallArbiter.java:102)
    at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call (CallExecuteOnSubscribe.java:46)
    at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call (CallExecuteOnSubscribe.java:24)
    at rx.Observable.unsafeSubscribe (Observable.java:10327)
    at rx.internal.operators.OnSubscribeMap.call (OnSubscribeMap.java:48)
    at rx.internal.operators.OnSubscribeMap.call (OnSubscribeMap.java:33)
    at rx.Observable.unsafeSubscribe (Observable.java:10327)
    at rx.internal.operators.OnSubscribeSingle.call (OnSubscribeSingle.java:81)
    at rx.internal.operators.OnSubscribeSingle.call (OnSubscribeSingle.java:27)
    at rx.internal.operators.SingleToObservable.call (SingleToObservable.java:39)
    at rx.internal.operators.SingleToObservable.call (SingleToObservable.java:27)
    at rx.Observable.unsafeSubscribe (Observable.java:10327)
    at rx.internal.operators.OnSubscribeMap.call (OnSubscribeMap.java:48)
    at rx.internal.operators.OnSubscribeMap.call (OnSubscribeMap.java:33)
    at rx.internal.operators.OnSubscribeLift.call (OnSubscribeLift.java:48)
--------
### Steps to reproduce the problem
mvn azure-functions:deploy

[helloworldfunction.zip](https://github.com/microsoft/azure-maven-plugins/files/4922879/helloworldfunction.zip)
[helloworldfunction.zip](https://github.com/microsoft/azure-maven-plugins/files/4922881/helloworldfunction.zip)

**Comment by Flanker32** [comment]
@ssampigegithub Thanks for your report, it seems that the functionAppName in your pom file is not set correctly, which is `<functionAppName>$(artifactId)-$(timestamp)</functionAppName>`, could you replace the value and try again?

Besides, `$(artifactId)-$(timestamp)` is the default value in archetype and should be replaced while generate the project,  it seems the archetype post script didn't work, did you meet any issues while generating the project? Any information could be helpful.

**Comment by ssampigegithub** [comment]
Yes. I changed it to

      <functionAppName>${artifactId}</functionAppName>

Same error.

**Comment by ssampigegithub** [comment]
I changed it to         <functionAppName>helloWorldFunctionApp</functionAppName>  also and tried. But same error.
Interesting thing is eventhough it fails it creates 4 storage accounts, the app service plan and the application insights.
In the app service plan under apps i don't see anything. Both screenshots attached (.PNG format).

![Azure-function-helloworld1](https://user-images.githubusercontent.com/59934017/87567230-e6df7200-c678-11ea-8558-02d65526fe80.PNG)
![Azure-function-helloworld2](https://user-images.githubusercontent.com/59934017/87567235-e8109f00-c678-11ea-8f91-e1b0d0548522.PNG)

**Comment by ssampigegithub** [comment]
Ok, this gets very interesting.  It worked! I narrowed down the issue and it gets very interesting. Changing the functionAppName works. I am able to repeatedly produce success and failures now by commenting+uncommenting the following sections to cycle between function app names. Each time before running i manually clear out all the resources in azure. So, can't really explain what the underlying issue is with the azure functions maven plugin, something for you to take a look..especially in the error reporting (more details to aid troubleshooting the better).

         
         
        <functionAppName>helloWorldFunctionAppInsights</functionAppName> 



[INFO] [Correlation ID: c3485437-31db-47c2-804f-d7f96c2829ed] Instance discovery was successful
[DEBUG] [Correlation ID: c3485437-31db-47c2-804f-d7f96c2829ed] Access Token and Refresh Token were returned
[INFO] Subscription : retailMgmt(845739df-78dd-4d05-9c57-21afecd45629)
[INFO] The specified function app does not exist. Creating a new function app...
[INFO] Set function worker runtime to java.
[INFO] Creating application insights...
[INFO] Successfully created the application insights helloWorldFunctionAppInsights for this Function App. You can visit https:
57-21afecd45629/resourceGroups/rates-dev/providers/microsoft.insights/components/helloWorldFunctionAppInsights/overview to vie
[INFO] Successfully created the function app: helloWorldFunctionAppInsights.
[INFO] Trying to deploy the function app...
[DEBUG] Compressing 'C:\2020-Workspaces\azure-cloud-pocs\helloworldfunction\target\azure-functions\helloWorldFunctionAppInsigh
\target\azure-functions\helloWorldFunctionAppInsights.zip'.
[DEBUG] Copying 'C:\2020-Workspaces\azure-cloud-pocs\helloworldfunction\target\azure-functions\helloWorldFunctionAppInsights.z
6183088348.zip' and removing paths [local.settings.json].
[INFO] Trying to deploy artifact to helloWorldFunctionAppInsights...
[INFO] Successfully deployed the artifact to https://helloworldfunctionappinsights.azurewebsites.net
[INFO] Successfully deployed the function app at https://helloWorldFunctionAppInsights.azurewebsites.net.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:13 min
[INFO] Finished at: 2020-07-15T09:12:14-07:00
[INFO] ------------------------------------------------------------------------

**Comment by Flanker32** [comment]
@ssampigegithub Thanks for the updates, it seems that some one has created function/app service named `helloworldfunction`  and if you try to deploy a new one with the same name, function service will block it and returns failed, and this is by design, we plan to do the validation earlier in later releases.
Below is the error log, could you please helps check whether you meet the same error.
```
[ERROR] Failed to execute goal com.microsoft.azure:azure-functions-maven-plugin:1.6.0:deploy (default-cli) on project helloworldfunction: Website with given name helloworldfunction already exists.: OnError while emitting onNext value: retrofit2.Response.class -> [Help 1]
```
