### ISSUE TITLE
@TimerTrigger function causes azure-maven-plugin to error out and functions CLI to crash

### ISSUE THREAD

**Issue by ssampigegithub** [microsoft/azure-maven-plugins#1105]
### Plugin name and version
azure-functions-maven-plugin version 1.6.0

### Plugin configuration in your `pom.xml`
See attached zip file that contains full source

### Expected behavior
Timer trigger function should have worked

### Actual behavior
The azure functions cli popup window that pops up crashes immediately. Can't capture/see what the error is.  This is the error i see in the command prompt

[ERROR] Failed to execute goal com.microsoft.azure:azure-functions-maven-plugin:1.6.0:run (default-cli) on project helloworldfunction: Failed to run Azure Functions. Please checkout console
output. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.microsoft.azure:azure-functions-maven-plugin:1.6.0:run (default-cli) on project helloworldfunction: Failed
to run Azure Functions. Please checkout console output.

### Steps to reproduce the problem
1) Comment out the other function in Function.java and add this
    @FunctionName("TimedHelloWorldExample")
    public void run(
        @TimerTrigger(name = "timerInfo", schedule = "0 */5 * * * *") String timerInfo,
        final ExecutionContext context
    ) {
    	System.out.println("This is the TimedHelloWorldExample....");
        context.getLogger().info("Java Timer trigger function executed at: " + LocalDateTime.now());
    }    
2) do mvn clean package  and then do mvn azure-functions:deploy

[helloworldfunction.zip](https://github.com/microsoft/azure-maven-plugins/files/4927014/helloworldfunction.zip)

**Comment by Flanker32** [comment]
@ssampigegithub Thanks for your report, i tried it locally and it reports `Missing value for AzureWebJobsStorage in local.settings.json. This is required for all triggers other than httptrigger, kafkatrigger. You can run 'func azure functionapp fetch-app-settings <functionAppName>' or specify a connection string in local.settings.json.`, please set an Azure storage connction string in your local.settings.json and try again, you may get it in portal.

![image](https://user-images.githubusercontent.com/12445236/87619586-1a8ccb80-c74f-11ea-9af7-ce9c3194c57a.png)

**Comment by ssampigegithub** [comment]
Yes. That worked. Please consider this an a improvement to be worked on for the next release; to give a meaningful error message in the main window and improved documentation. Thanks for your help.


Http Functions:

        HttpExample: [GET,POST] http://localhost:7071/api/HttpExample

        TestHelloExample: [GET,POST] http://localhost:7071/api/TestHelloExample

[7/16/2020 5:42:12 AM] The next 5 occurrences of the 'TimedHelloWorldExample' schedule (Cron: '0 * * * * *') will be:
[7/16/2020 5:42:12 AM] 07/15/2020 22:43:00-07:00 (07/16/2020 05:43:00Z)
[7/16/2020 5:42:12 AM] 07/15/2020 22:44:00-07:00 (07/16/2020 05:44:00Z)
[7/16/2020 5:42:12 AM] 07/15/2020 22:45:00-07:00 (07/16/2020 05:45:00Z)
[7/16/2020 5:42:12 AM] 07/15/2020 22:46:00-07:00 (07/16/2020 05:46:00Z)
[7/16/2020 5:42:12 AM] 07/15/2020 22:47:00-07:00 (07/16/2020 05:47:00Z)
[7/16/2020 5:42:12 AM]
[7/16/2020 5:42:12 AM] Host started (3831ms)
[7/16/2020 5:42:12 AM] Job host started
Hosting environment: Production
Content root path: c:\2020-workspaces\azure-cloud-pocs\helloworldfunction\target\azure-functions\helloworldfunctionappinsights
Now listening on: http://0.0.0.0:7071
Application started. Press Ctrl+C to shut down.
[7/16/2020 5:42:17 AM] Host lock lease acquired by instance ID '000000000000000000000000686BB809'.
