### ISSUE TITLE
Warning on Azure Functions Package

### ISSUE THREAD

**Issue by EwanNoble** [microsoft/azure-maven-plugins#1109]
### Plugin name and version
azure-functions-maven-plugin:1.6.0

### Plugin configuration in your `pom.xml`
```
 <plugin>
                <groupId>com.microsoft.azure</groupId>
                <artifactId>azure-functions-maven-plugin</artifactId>
                <configuration>
                    <resourceGroup>${functionResourceGroup}</resourceGroup>
                    <appName>${functionAppName}</appName>
                    <region>${functionAppRegion}</region>
                    <appSettings>
                        <property>
                            <name>WEBSITE_RUN_FROM_PACKAGE</name>
                            <value>1</value>
                        </property>
                        <property>
                            <name>FUNCTIONS_EXTENSION_VERSION</name>
                            <value>~3</value>
                        </property>
                    </appSettings>
                </configuration>
                <executions>
                    <execution>
                        <id>package-functions</id>
                        <goals>
                            <goal>package</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

### Expected behavior
No warnings on `mvn package`

### Actual behavior
`[WARNING] The POM for com.microsoft.azure.applicationinsights.v2015_05_01:azure-mgmt-insights:jar:1.0.0-beta is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details` appears in the logs

### Steps to reproduce the problem
Run `mvn package` with version 1.6.0 on azure-functions-maven-plugin

Seems to be caused by this: https://github.com/microsoft/azure-maven-plugins/blob/a6160f31b5f80b2398b8cd0ce6bbefb43bb5cdd7/azure-tools-common/pom.xml#L85-L89
Perhaps it can be updated or removed?

**Comment by Flanker32** [comment]
@EwanNoble Thanks for your report,we are using application insights mgmt sdk for resource creation in function deployment, so the dependencies can not be removed, we are waiting for the sdk updates and i'll update here once there are updates.
