### ISSUE TITLE
Cross-Site Scripting: Reflected

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [microsoft/azure-maven-plugins#1110]
https://github.com/microsoft/azure-maven-plugins/blob/4d8e73c0c2d5f61c8dd8304de5a31c9549bb0b87/azure-auth-helper/src/main/java/com/microsoft/azure/auth/LocalAuthServer.java#L57-L67

Sending unvalidated data to a web browser can result in the browser executing malicious code.

**Comment by wangmingliang-ms** [comment]
the `error` and `errorDescription`  come from Azure's own OAuth server, which should be trustable.
