### ISSUE TITLE
Setting subscriptionId changes active subscription

### ISSUE THREAD

**Issue by viters** [microsoft/azure-maven-plugins#1112]
### Plugin name and version

azure-webapp-maven-plugin 1.9.0

### Plugin configuration in your `pom.xml`

                <configuration>
                    <schemaVersion>v2</schemaVersion>
                    [...]
                    <subscriptionId>ID</subscriptionId>
                </configuration>

### Expected behavior

It uses provided ID only to run necessary commands without changing active subscription on SP.

### Actual behavior

It changes active subscription on the service principal. It may result in race conditions between CI / CD pipelines that use different subscriptions and the same service principal.

### Steps to reproduce the problem

1. Allow SP to deploy to 2 subscriptions.
2. Deploy first app to active subscription without specifying subscriptionId in configuration.
3. Deploy second app to non-active subscription with specifying subscriptionId in configuration.
4. Deploy first app to active subscription without specifying subscriptionId in configuration - INVALID, because plugin tries to deploy to second subscription - meaning that step 3 changed active subscription on SP.

**Comment by Flanker32** [comment]
@viters  Thanks for your report and sorry for the late reply. Could you please share your authentication method or pom configuration?  I tried to reproduce this issue with [service principal](https://github.com/microsoft/azure-maven-plugins/wiki/Authentication#service-principles-in-plugin-configuration) authentication and it works well.

**Comment by viters** [comment]
@Flanker32

I was using azure_cli authentication method. By the way, is Azure CLI required for this plugin or it is only required for azure_cli authentication?

**Comment by andxu** [comment]
Hi @viters, could you try other ways described in this [wiki](https://github.com/microsoft/azure-maven-plugins/wiki/Authentication) on the latest version 2.1.0?

**Comment by andxu** [comment]
The latest version 2.1.0 will prompt you to select subscription when your sp have multiple subs(azure cli won't since azure cli always has a default  subs)

![image](https://user-images.githubusercontent.com/17075863/128678024-731aaf99-884a-400f-8380-9735c2bcf2ae.png)
