### ISSUE TITLE
[Functions] Warn if creating a v2 function app 

### ISSUE THREAD

**Issue by pragnagopa** [microsoft/azure-maven-plugins#1113]
### Plugin name and version
Azure Functions

ASK:
Encourage customers to use v3.

Perhaps also warn when deploying to a v2 app and link to Azure/app-service-announcements#266

/cc @anthonychu @amamounelsayed

**Comment by Flanker32** [comment]
@pragnagopa According to the [announcements](https://github.com/Azure/app-service-announcements/issues/266), java users are not affected by the function host upgrade, so do we need to show this warning in Java tooling?

/cc @andxu @yucwan

**Comment by anthonychu** [comment]
Does the Maven plugin call Core Tools? If it does, Core Tools should already be showing this warning. (Assuming they’ve updated to a version that displays it)

**Comment by pragnagopa** [comment]
@flanker32  - Yes, Java users will not be affected by the auto upgrade. Warning is for awareness and encouraging users to move to latest version by themselves.

Also, as @anthonychu  mentioned, if publish from mvn plugin uses core tools - no action needed as core tools will soon be updated to display a warning. Please verify.

**Comment by Flanker32** [comment]
@pragnagopa @anthonychu Maven plugin will call function core tools while maven package and local run, and package/run will refer host.json instead of `FUNCTIONS_EXTENSION_VERSION` specified in pom configuration; for deployment, it will call Java SDK directly.
