### ISSUE TITLE
azure-webapp:deploy resource copy fails

### ISSUE THREAD

**Issue by twolfrum** [microsoft/azure-maven-plugins#1118]
azure-webapp-maven-plugin v1.9.1

### Plugin configuration in your `pom.xml`
      <plugin>
          <groupId>com.microsoft.azure</groupId>
          <artifactId>azure-webapp-maven-plugin</artifactId>
          <version>1.9.1</version>
          <configuration>
              <schemaVersion>V2</schemaVersion>
              <resourceGroup>RCOS2Home</resourceGroup>
              <appName>rcos2server</appName>
              <region>centralus</region>
              <subscriptionId>07fd4bb9-6449-4c5b-b597-b50aafd1b6c5</subscriptionId>
              <authentication>
           		<serverId>azure-auth</serverId>
        	  </authentication>
              <runtime>
            		<os>linux</os>
              	
              	<javaVersion>jre8</javaVersion>
              	
            	</runtime>
              <deployment>
                  <resources>
                      <resource>
                       <directory>${project.basedir}/target</directory>
                       <includes>
                           <include>*.jar</include>
                       </includes>
                      </resource>
                  </resources>
              </deployment>
          </configuration>
      </plugin>

### Expected behavior
app.jar gets deployed to the existing Azure App Service 

### Actual behavior
$ mvn -ntp -DskipTests=true -B azure-webapp:deploy -Pprod
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< com.spinmnt.rcos2:rcos-2-server >-------------------
[INFO] Building Rcos 2 Server 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- azure-webapp-maven-plugin:1.9.1:deploy (default-cli) @ rcos-2-server ---
[WARNING] You are using an old way of authentication which will be deprecated in future versions, please change your configurations.
[INFO] Authenticate with ServerId: azure-auth
[INFO] [Correlation ID: 245c74f1-c189-42b9-acd8-7b4fe003c6b4] Instance discovery was successful
[INFO] Updating target Web App...
[INFO] Successfully updated Web App.
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource to C:\Users\Tom\AzureDefect\RCOS2Server\target\azure-webapp\rcos2server-349b09c7-e349-4c37-9254-0e4d8395258e
[INFO] Trying to deploy artifact to rcos2server...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  14.983 s
[INFO] Finished at: 2020-08-05T12:01:50-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.microsoft.azure:azure-webapp-maven-plugin:1.9.1:deploy (default-cli) on project rcos-2-server: No executable jar found in target folder according to resource filter in <resource>, please make sure the resource filter is correct and you have built the jar. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Same Maven command executed with -X option:
mvn -ntp -DskipTests=true -B azure-webapp:deploy -Pprod -X
produces following snippet in console output:
...
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[DEBUG] resource with targetPath C:\Users\Tom\AzureDefect\RCOS2Server\target\azure-webapp\rcos2server-7d862ce0-9317-4ff1-9826-4c16b196ec6a
directory C:\Users\Tom\AzureDefect\RCOS2Server/target
excludes []
includes [*.jar]
[DEBUG] ignoreDelta true
[INFO] Copying 1 resource to C:\Users\Tom\AzureDefect\RCOS2Server\target\azure-webapp\rcos2server-7d862ce0-9317-4ff1-9826-4c16b196ec6a
[DEBUG] file app.jar has a filtered file extension
[DEBUG] copy C:\Users\Tom\AzureDefect\RCOS2Server\target\app.jar to C:\Users\Tom\AzureDefect\RCOS2Server\target\azure-webapp\rcos2server-7d862ce0-9317-4ff1-9826-4c16b196ec6a\app.jar
[INFO] Trying to deploy artifact to rcos2server...

I've traced the above logging output to the org.apache.maven.shared.filtering.DefaultMavenResourcesFiltering and org.apache.maven.shared.filtering.DefaultMavenFileFilter classes. It appears the DefaultMavenResourcesFiltering.copyFile() method at line 101 fails but no error is reported 

### Steps to reproduce the problem
Running on Windows 10 Pro with Azure CLI installed. Have tried using Windows cmd shell and Powershell (with admin rights) and git bash shell. All produced same result. Also tried using Docker container provisioned with Ubuntu, Azure CLI, Maven and Java8 - same result.

The attached zip contains the project (executable jar) I'm trying to deploy. Edit pom.xml to change azure-webapp-maven-plugin config to appropriate azure resources. My Azure subscription was provisioned with:
Resource Group: RCOS2Home
App Service: rcos2server (linux, Java8)
App Service Plan rcos2server-plan
Application Insights: rcos2server-insights

For authentication, a service principal was created for the app and the authentication credentials added the maven settings.xml file as follows:
<server>
      <id>azure-auth</id>
      <configuration>
         <client>{from az ad sp rbac command output}</client>
         <tenant>{from az ad sp rbac command output}</tenant>
         <key>{from az ad sp rbac command output}</key>
         <environment>AZURE</environment>
      </configuration>
</server>

Unzip the attached and build the jar with:
mvn install -DskipTests=true -Pprod

Then try to deploy with:
mvn -ntp -DskipTests=true -B azure-webapp:deploy -Pprod to reproduce.  
 
[RCOS2Server.zip](https://github.com/microsoft/azure-maven-plugins/files/5030394/RCOS2Server.zip)

**Comment by Flanker32** [comment]
@twolfrum Thanks a lot for your report, will looking into this issue soon.

**Comment by Flanker32** [comment]
@twolfrum Could you please set  `<executable>` of `spring-boot-maven-plugin` to be `false` and try again? This which will generate a bash file with jar content, while maven plugin requires a jar which could be invoke by `java -jar` (jar with Main class in Manifest)
