### ISSUE TITLE
azure:login does not appear to support service principal login

### ISSUE THREAD

**Issue by ericis** [microsoft/azure-maven-plugins#1182]
From the `azure:login` [authentication documentation](https://docs.microsoft.com/en-us/java/api/overview/azure/maven/azure-maven-plugin/authentication).

### Plugin name and version

```
        <groupId>com.microsoft.azure</groupId>
        <artifactId>azure-maven-plugin</artifactId>
        <version>0.2.0</version>
```

### Expected behavior

Logs in with Service Principal credentials.

### Actual behavior

Prompts for interactive device login with URL and login code. Works [as documented](https://docs.microsoft.com/en-us/java/api/overview/azure/maven/azure-maven-plugin/authentication).

### Steps to reproduce the problem

Use the plug-in as documented with service principal credentials.

### Likely offending code

https://github.com/microsoft/azure-maven-plugins/blob/09ac8421a66da49c6470a6e8d86bfd497ddc78ad/azure-maven-plugin/src/main/java/com/microsoft/azure/plugin/login/LoginMojo.java#L61-L68

```
            String loginMethod = devicelogin ? TELEMETRY_VALUE_AUTH_METHOD_DEVICE : TELEMETRY_VALUE_AUTH_METHOD_OAUTH;
            try {
                newAzureCredential = devicelogin ? AzureAuthHelper.deviceLogin(env) : AzureAuthHelper.oAuthLogin(env);
            } catch (DesktopNotSupportedException e) {
                // fallback to device login if oauth login fails
                newAzureCredential = AzureAuthHelper.deviceLogin(env);
                loginMethod = TELEMETRY_VALUE_AUTH_METHOD_DEVICE;
            }
```

**Comment by andxu** [comment]
Hi @ericis, the mvn login goal is designed as a backup plan for users who doesn't have azure cli, it is to pull the azure credentials to local like azure cli: `az login`, but it is very limited to two login ways: device login and oauth( unlike azure cli, it supports much more login ways including service principal), if you have service principle, you need not to login use maven azure plugin, use the following, you will be able to deploy your project.
```
     <auth>            
        <client>df4d03fa-135b-4b7b-932d-2f2ba6449792</client>
        <tenant>72f988bf-86f1-41af-91ab-2d7cd011db47</tenant>
        <key>xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx</key>
        <environment>AZURE</environment>
    </auth>
```

**Comment by ericis** [comment]
Closing for "as designed" since there is an alternative.
