### ISSUE TITLE
Use azure-maven-plugin to deploy python custom docker image

### ISSUE THREAD

**Issue by iyunbo** [microsoft/azure-maven-plugins#1209]
While deploying custom docker image with python runtime,
the worker runtime is overwritten by java, due to 

https://github.com/microsoft/azure-maven-plugins/blob/5d8e6b9d5bc171b9b4b7570072b9bdb72fc0c434/azure-functions-maven-plugin/src/main/java/com/microsoft/azure/maven/function/AbstractFunctionMojo.java#L99-L100

can you enable the deployment for python in case of  custom image? 

In fact, this light modification could help a lot on development of python custom image.

**Comment by iyunbo** [comment]
any update please ?

**Comment by Flanker32** [comment]
@iyunbo Thanks a lot for your advice, here is the pr for this issue https://github.com/microsoft/azure-maven-plugins/pull/1250

**Comment by iyunbo** [comment]
Excellent news

**Comment by Flanker32** [comment]
@iyunbo Thanks for your help and really sorry for the delay, functions maven plugin 1.10.0 has been released with this feature, you may get the change log [here](https://github.com/microsoft/azure-maven-plugins/releases/tag/azure-functions-maven-plugin-1.10.0)
