### ISSUE TITLE
Build result of Azure Functions project depends on source code

### ISSUE THREAD

**Issue by dimatomp** [Microsoft/azure-maven-plugins#121]
In the attached project, result of `mvn package` (whether it succeeds or fails) somehow depends on contents of project source files (`*.java`, not even `pom.xml`). 

### Plugin name and version
`azure-functions-maven-plugin:0.1.10`

### Plugin configuration in your `pom.xml`
Attached.

### Expected behavior
Behaviour of `mvn package` does not change when project source is modified

### Actual behavior
Build failure log attached.

### Steps to reproduce the problem
1. [Download the archive](https://seafile.in.devexperts.com/f/5930d46c330c40a1940c/?dl=1)
2. Unpack the project, run `mvn -e package`, observe the error.
3. Open `Function.java` source file and replace all contents of the class with a stub Azure function implementation that does nothing and succeeds (e.g. `return request.createResponse(200, "OK")`).
4. Run `mvn package` again, observe build success.

**Comment by jdneo** [comment]
Hi @dimatomp 
Thanks for reporting this. This is a known issue for our current released version. We are planning to release a new version with this fix.

If this is blocking you, please try the following work around:


## Install the SNAPSHOT version of the plugin
```
git clone https://github.com/Microsoft/azure-maven-plugins.git
cd azure-maven-plugins
mvn clean install -DskipTests
```

## Change the plugin version
```xml
<plugin>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-functions-maven-plugin</artifactId>
    <version>0.2.0-SNAPSHOT</version>
</plugin>
```

Then you can run `mvn package` with the expected results.

**Comment by jdneo** [comment]
v0.2.0 of the azure-functions-maven-plugin has been released and this issue should be fixed. Please feel free to have a try.
