### ISSUE TITLE
azure-functions-maven-plugin:1.9.0:package fails with NullPointerException

### ISSUE THREAD

**Issue by EspenSchei** [microsoft/azure-maven-plugins#1212]
### Plugin name and version
- **Plugin**: azure-functions-maven-plugin:1.9.0
- **Maven version**: Apache Maven 3.6.3

### Plugin configuration in your `pom.xml`
Generated with maven archetype.
```
<plugin>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-functions-maven-plugin</artifactId>
    <version>${azure.functions.maven.plugin.version}</version>
    <configuration>
        <appName>${functionAppName}</appName>
        <resourceGroup>java-functions-group</resourceGroup>
        <appServicePlanName>java-functions-app-service-plan</appServicePlanName>
        <region>westus</region>
        <runtime>
            <os>linux</os>
            <javaVersion>11</javaVersion>
        </runtime>
        <appSettings>
            <property>
                <name>FUNCTIONS_EXTENSION_VERSION</name>
                <value>~3</value>
            </property>
        </appSettings>
    </configuration>
    <executions>
        <execution>
            <id>package-functions</id>
            <goals>
                <goal>package</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```
### Expected behavior
`mvn azure-functions:package` should package the function.

### Actual behavior
Build fails with NullPointerException.
```
[ERROR] Failed to execute goal com.microsoft.azure:azure-functions-maven-plugin:1.9.0:package (default-cli) on project test: java.lang.NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.microsoft.azure:azure-functions-maven-plugin:1.9.0:package (default-cli) on project test: java.lang.NullPointerException
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    ....
Caused by: java.lang.NullPointerException
    at java.util.zip.ZipFile.<init> (ZipFile.java:233)
    at java.util.zip.ZipFile.<init> (ZipFile.java:177)
    at java.util.jar.JarFile.<init> (JarFile.java:348)
    at java.util.jar.JarFile.<init> (JarFile.java:319)
    at java.util.jar.JarFile.<init> (JarFile.java:285)
    at com.microsoft.azure.common.Utils.getArtifactCompileVersion (Utils.java:30)
    at com.microsoft.azure.maven.function.PackageMojo.promptCompileInfo (PackageMojo.java:378)
    at com.microsoft.azure.maven.function.PackageMojo.doExecute (PackageMojo.java:98)
    at com.microsoft.azure.maven.AbstractAzureMojo.execute (AbstractAzureMojo.java:448)
    ....
```
### Steps to reproduce the problem
1. Create new project with maven archetype using default settings:
`mvn archetype:generate -DarchetypeGroupId=com.microsoft.azure -DarchetypeArtifactId=azure-functions-archetype -DjavaVersion=11`
2. Build the project: `mvn clean package`
3. Attempt to package the function: `mvn azure-functions:package`

### Workaround
Downgrade azure-functions-maven-plugin to version 1.6.0

**Comment by Flanker32** [comment]
@EspenSchei Thanks for your report, I'm investigating this issue and will update here once there are updates

**Comment by jdubois** [comment]
@Flanker32 I'm having the same issue with plugin version 1.9.2 -> the PR is merged, but the ticket is still opened, does this mean this isn't released yet? It's a blocker issue to package an Azure Function that you want to deploy using the Azure Functions GitHub Action (not using the plugin to deploy)

**Comment by itsandreramon** [comment]
Having the same problem on 1.9.2

**Comment by jdubois** [comment]
@itsandreramon the PR is merged, but I talked to the team and it’s not released yet.

**Comment by sharebear** [comment]
@jdubois As mentioned in the issue description we have not experienced any problems  downgrading to 1.6.0 until the fix is released and deploy using the Azure Functions GitHub Action regularly.

Also if I understand the fix correctly I think the current version would work if you bind the the execution to maven's `package` lifecycle phase rather than running it separately, but I've not had the time or motivation to test out this theory.

**Comment by jdubois** [comment]
Yes I confirm v1.6.0 works, but I wouldn’t recommend using it (for reasons I can’t detail publicly, unfortunately)

**Comment by Flanker32** [comment]
@jdubois @itsandreramon @sharebear Thank you al for your support. I'm sorry but the fixes is still not released, as a workaround, please use `mvn package` if you want to package the function,  I'll update here once the fix is released.

**Comment by Flanker32** [comment]
@jdubois @itsandreramon @sharebear Thanks again for your help, functions maven plugin 1.10.0 has been released with fix for this issue.
