### ISSUE TITLE
Show error info when use auto to auth and select default authType is OAUTH2

### ISSUE THREAD

**Issue by SunnyChen1** [microsoft/azure-maven-plugins#1216]
### Plugin name and version

OS: MAC
Plugin: azure-functions-maven-plugin 1.10.0-SNAPSHOT
            azure spring cloud maven plugin 1.4.0-SNAPSHOT 
            Azure-webapp-maven-plugin:1.13.0-SNAPSHOT

**Plugin configuration in your pom.xml**
```
<configuration>
 <appName>${functionAppName}</appName>
 <resourceGroup>chylfuncrg</resourceGroup>
 <appServicePlanName>chylfunc01-app-service-plan</appServicePlanName>
 <region>westus</region>
 <runtime>
 <os>linux</os>
 <javaVersion>java 8</javaVersion>
 </runtime>
 <appSettings>
 <property>
 <name>FUNCTIONS_EXTENSION_VERSION</name>
 <value>~3</value>
 </property>
 </appSettings>
</configuration>
```
**Actual behavior**
![image](https://user-images.githubusercontent.com/63633836/104423482-1e43c280-55b9-11eb-9b4c-555d08af852d.png)

**Comment by ZhengJun003** [comment]
This issue is fixed
![image](https://user-images.githubusercontent.com/41051257/105276296-09c88100-5bdc-11eb-95e5-89c3b65c4115.png)
