### ISSUE TITLE
FTP deployment failure to an existing function app

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-maven-plugins#122]
### Plugin name and version
com.microsoft.azure.azure-functions-maven-plugin:0.2.0-SNAPSHOT
### Actual behavior
![image](https://user-images.githubusercontent.com/22470312/38183149-a08a074c-3670-11e8-8d75-ac550c826fb8.png)
![image](https://user-images.githubusercontent.com/22470312/38183154-a37ffcfe-3670-11e8-86d4-dc370cb5c73e.png)

**Comment by jdneo** [comment]
@bsaby Just as the log shows. It it because the jar file is been occupied by the service. To solve this problem, you and add `<stopAppDuringDeployment>true</stopAppDuringDeployment>` in the plugin configuration

**Comment by bsaby** [comment]
I can't repro this issue after adding the configuration `<stopAppDuringDeployment>true</stopAppDuringDeployment>`
