### ISSUE TITLE
Font color turn blue if ctrl+c when ask to confirm tasks

### ISSUE THREAD

**Issue by pl07** [microsoft/azure-maven-plugins#1242]
### Plugin name and version
OS: Win
Plugin: azure-spring-cloud-maven-plugin 1.4.0-SNAPSHOT

### Actual behavior
Default font color is white, after ctrl+c, it turns white
![image](https://user-images.githubusercontent.com/46642771/105456750-ab290300-5cc0-11eb-9d7b-a56ccc7d537d.png)

### Steps to reproduce the problem
1. Run mvn azure-spring-cloud:deploy.
2. When be asked to confirm tasks, press ctrl+c to terminate job.

**Comment by ZhengJun003** [comment]
Test in latest develop branch, this issue is fixed
![image](https://user-images.githubusercontent.com/41051257/105815765-623dbb00-5fee-11eb-82fd-39bec13de4a6.png)
