### ISSUE TITLE
Show same warning message twice

### ISSUE THREAD

**Issue by pl07** [microsoft/azure-maven-plugins#1244]
### Plugin name and version
OS: Win
Plugin: azure-spring-cloud-maven-plugin 1.4.0-SNAPSHOT

### Actual behavior
![image](https://user-images.githubusercontent.com/46642771/105460778-41602780-5cc7-11eb-929e-e5b51b3aeb99.png)

**Comment by ZhengJun003** [comment]
This issue is fixed
![image](https://user-images.githubusercontent.com/41051257/105814237-0d00aa00-5fec-11eb-9d02-6feaa021e4ac.png)
