### ISSUE TITLE
How to generate TimeTrigger function by maven

### ISSUE THREAD

**Issue by yaseenmd** [microsoft/azure-maven-plugins#1254]
### Plugin name and version
Azure-functions-archetype
1.33

### Expected behavior
By default it generates the httptrigger function and its configuration. 
How to generate  TimeTrigger function

**Comment by Flanker32** [comment]
@yaseenmd Thanks for your support and sorry for the delay, we are working on the trigger selection in archetype and here is the [pr](https://github.com/microsoft/azure-maven-archetypes/pull/163), which will be in next release. Before the new archetype, you may create a function project with archetype first, and use `mvn azure-functions:add` to create other triggers.
