### ISSUE TITLE
Warning about illegal reflective access at least since azure-maven-plugin 1.4.2

### ISSUE THREAD

**Issue by CaymanTurtleBeach** [microsoft/azure-maven-plugins#1359]
###
 `    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <azure.functions.maven.plugin.version>1.9.2</azure.functions.maven.plugin.version>
        <azure.functions.java.library.version>1.4.2</azure.functions.java.library.version>
        <functionAppName>xxxxxxxxxxxxxxxxxxxx</functionAppName>
        <stagingDirectory>${project.build.directory}/azure-functions/${functionAppName}</stagingDirectory>
    </properties>
`

### [WARNING] The POM for com.microsoft.azure.applicationinsights.v2015_05_01:azure-mgmt-insights:jar:1.0.0-beta is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.microsoft.applicationinsights.core.dependencies.xstream.core.util.Fields (file:/C:/Users/Admin/.m2/repository/com/microsoft/azure/applicationinsights-core/2.6.1/applicationinsights-core-2.6.1.jar) to field java.util.TreeMap.comparator
WARNING: Please consider reporting this to the maintainers of com.microsoft.applicationinsights.core.dependencies.xstream.core.util.Fields

### Seems to occur with any Java function

Azure Functions Core Tools
Core Tools Version:       3.0.3388 Commit hash: fb42a4e0b7fdc85fbd0bcfc8d743ff7d509122ae 
Function Runtime Version: 3.0.15371.0

Java 11

That this warning has persisted for so long (since 1.4.2), and with all the other issues reported here related to Application Insights and null pointers and other exceptions, one wonders how Java functions can claim to be GA.

**Comment by Flanker32** [comment]
@CaymanTurtleBeach Thanks for your report, the dependency is used to create AI insights for function, which is a code-less attach to provide detailed observability in to your application. We are still working with SDK team to solve this issue. I'll update here once there are updates.
