### ISSUE TITLE
Can not run java azure function locally, created using maven archetype:generate given on microsoft site using mvn azure-functions:run, not showing error. Its simply freezing.

### ISSUE THREAD

**Issue by Iuzuz** [microsoft/azure-maven-plugins#1377]
### Plugin name and version:
        <java.version>1.8</java.version>
        <azure.functions.maven.plugin.version>1.9.2</azure.functions.maven.plugin.version>
        <azure.functions.java.library.version>1.4.0</azure.functions.java.library.version>

### Plugin configuration in your `pom.xml`
            <plugin>
                <groupId>com.microsoft.azure</groupId>
                <artifactId>azure-functions-maven-plugin</artifactId>
                <version>${azure.functions.maven.plugin.version}</version>
                <configuration>
                    
                    <appName>${functionAppName}</appName>
                    
                    <resourceGroup>java-functions-group</resourceGroup>
                    
                    <appServicePlanName>java-functions-app-service-plan</appServicePlanName>
                    
                    
                    <region>westus</region>
                    
                    
                    
                    
                    
                    
                    
                    <runtime>
                        
                        <os>windows</os>
                        <javaVersion>8</javaVersion>
                        
                        
                        
                        
                    </runtime>
                    <appSettings>
                        <property>
                            <name>FUNCTIONS_EXTENSION_VERSION</name>
                            <value>~3</value>
                        </property>
                    </appSettings>
                </configuration>
                <executions>
                    <execution>
                        <id>package-functions</id>
                        <goals>
                            <goal>package</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

### Expected behavior
The ":run" starts the application
### Actual behavior
The maven command blocks at [DEBUG] Executing command: func
### Steps to reproduce the problem

Steps to reproduce (at least in my case):

windows, java 8, mvn 3.3.3
mvn archetype:generate -DarchetypeGroupId=com.microsoft.azure -DarchetypeArtifactId=azure-functions-archetype -DarchetypeVersion=1.35 -DgroupId=com.bla.function -Dversion=0.1-SNAPSHOT -DartifactId=arch-function
-> results in [INFO] BUILD SUCCESS
cd arch-function
mvn package
-> results in [INFO] BUILD SUCCESS
mvn azure-functions:run -X
-> results on stopping at:
[INFO] Azure Function App's staging directory found at: V:\V1420-Microservices\arch-function\target\azure-functions\arch-function-20210326092331413
[DEBUG] Executing command: func
If I try to "cd" to the staging directory and call "func start"
then -> it works!

[2021-03-26T08:26:37.096Z] Job host started

Functions:

    HttpExample: [GET,POST] http://localhost:7071/api/HttpExample
(...Maybe this is a workaround)

I tried to inspect the running process with the jconsole. The main thread is blocked at:

Name: main
State: RUNNABLE
Total blocked: 75 Total waited: 2

Stack trace:
java.lang.ProcessImpl.waitForInterruptibly(Native Method)
java.lang.ProcessImpl.waitFor(ProcessImpl.java:449)
com.microsoft.azure.common.function.handlers.CommandHandlerImpl.runCommand(CommandHandlerImpl.java:80)
com.microsoft.azure.common.function.handlers.CommandHandlerImpl.runCommandWithReturnCodeCheck(CommandHandlerImpl.java:32)
com.microsoft.azure.maven.function.RunMojo.checkRuntimeExistence(RunMojo.java:90)
com.microsoft.azure.maven.function.RunMojo.doExecute(RunMojo.java:74)
com.microsoft.azure.maven.AbstractAzureMojo.execute(AbstractAzureMojo.java:466)
org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

.... maybe this helps somehow

There is very similar issue in https://github.com/microsoft/azure-maven-archetypes/issues/167, Please verify it. Thanks.

**Comment by Flanker32** [comment]
@luzuz Thanks for your report, maven plugin will invoke `func` to determine whether function core tools is installed correctly, however this may be blocked with the latest function core tools. 
We have fixed the issue in https://github.com/microsoft/azure-maven-plugins/pull/1367, will be shipped in functions maven plugin 1.10.0. Before the release, you may use core tools 3.0.3311 or previous version or invoke func host start in staging folder as a workaround.

**Comment by Iuzuz** [comment]
@Flanker32 thank you!

**Comment by Flanker32** [comment]
@luzuz Thanks a lot for your help, functions maven plugin 1.10.0 has been released with fix for this issue.
