### ISSUE TITLE
Multi executable jars found when including application insights agent 

### ISSUE THREAD

**Issue by darinhoward** [microsoft/azure-maven-plugins#1380]
### Plugin name and version
azure-webapp-maven-plugin:1.13.0

### Plugin configuration in your `pom.xml`
```
<configuration>
    <schemaVersion>V2</schemaVersion>
    <region>${azure.region}</region>
    <resourceGroup>${azure.resourceGroup}</resourceGroup>
    <appName>${azure.appName}</appName>
    <appServicePlanName>${azure.appServicePlanName}</appServicePlanName>
    <subscriptionId>${azure.subscriptionId}</subscriptionId>
    <deploymentSlotSetting>
        <name>stage</name>
        <configurationSource>parent</configurationSource>
    </deploymentSlotSetting>
    <deployment>
        <resources>
            <resource>
                <directory>${project.basedir}/target</directory>
                <includes>
                    <include>myapp-*.jar</include>
                </includes>
            </resource>
            <resource>
                <directory>${project.basedir}/../resources/azure</directory>
                <targetPath>azure</targetPath>
                <includes>
                    <include>**</include>
                </includes>
            </resource>
        </resources>
    </deployment>
</configuration>
```

### Expected behavior

application jar and application insights agent jar and config upload and deploy.

### Actual behavior

I get the following error: 
Multi executable jars found in <resources>, please check the configuration

I'm guessing this is related to including the application insights jar - I'm curious if this is a bug or how i configure my resources to indicate which jar is my application.

### Steps to reproduce the problem

mvn azure-webapp:deploy

**Comment by andxu** [comment]
for Java Se container, it is required to have all-in-one jar executable, if you just need a library jar uploaded, then you can specify the type `lib`  in `<resource>`(deployed to /home/site/libs, see doc at https://github.com/shrishrirang/onedeploy/tree/master/usage):
    <resource>
                <directory>${project.basedir}/../resources/azure</directory>
                <type>lib</type>
                <includes>
                    <include>*.jar</include>
                </includes>
            </resource>
