### ISSUE TITLE
Add feature for username and password for httpProxy

### ISSUE THREAD

**Issue by kevin808** [microsoft/azure-maven-plugins#1386]
### Plugin name and version
azure-maven-plugins, all versions, latest one is 1.10.0.

### Plugin configuration in your `pom.xml`
<code>
<httpProxyHost>proxyserver.com</httpProxyHost>
<httpProxyPort>8080</httpProxyPort>
</code>

### Expected behavior
Plugin can work with proxy server which requires username and password.

### Actual behavior
According to document: https://docs.microsoft.com/it-it/java/api/overview/azure/maven/azure-functions-maven-plugin/readme?view=azure-java-stable#configurations
It only supports httpProxyHost and httpProxyPort. There is no entry to define username and password.

### Steps to reproduce the problem
Running a java application with proxy server configured, it can always been reproduced.

**Comment by andxu** [comment]
We will impl proxy with authentication in Auguest.

**Comment by andxu** [comment]
The PR is availabe https://github.com/microsoft/azure-maven-plugins/pull/1677
