### ISSUE TITLE
(azure-functions-maven-plugin) mvn azure-functions:deploy requires allowBlobPublicAccess to be set to true

### ISSUE THREAD

**Issue by vikramkamath** [microsoft/azure-maven-plugins#1388]
### Plugin name and version
azure-functions-maven-plugin 1.9.0

### Plugin configuration in your `pom.xml`
```xml
<plugin>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-functions-maven-plugin</artifactId>
    <version>${azure.functions.maven.plugin.version}</version>
    <configuration>
      <resourceGroup>${resourceGroupName}</resourceGroup>
      <appName>${functionAppName}</appName>
      <region>${functionAppRegion}</region>
      <runtime>
        <os>linux</os>
        <javaVersion>8</javaVersion>
      </runtime>
      <appSettings>
        <property>
          <name>FUNCTIONS_EXTENSION_VERSION</name>
          <value>~3</value>
        </property>
      </appSettings>
    </configuration>
    <executions>
      <execution>
        <id>package-functions</id>
        <goals>
          <goal>package</goal>
        </goals>
      </execution>
    </executions>
  </plugin>
```

### Expected behavior
Keep the `allowPublicBlobAccess` to `false` and still be able to deploy artifacts 
### Actual behavior
Unable to upload azure function artifacts to storage account linked with azure function unless `allowPublicBlobAccess` is set to true
Running `mvn azure-functions:deploy` causes the following:
```
[INFO] Auth Type : AZURE_CLI, Auth Files : [/Users/blah/.azure/azureProfile.json, /Users/blah/.azure/accessTokens.json]
[INFO] [Correlation ID: xxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] Instance discovery was successful
[INFO] Subscription : blah_subscription(xxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)
[INFO] Set function worker runtime to java.
[INFO] Updating the specified function app...
[INFO] Successfully updated the function app: blahfuncapp
[INFO] Starting deployment...
[INFO] Trying to deploy artifact to blahfuncapp...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  17.322 s
[INFO] Finished at: 2021-03-30T19:13:37-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.microsoft.azure:azure-functions-maven-plugin:1.9.0:deploy (default-cli) on project blah-api: Fail to updload file as blob: Public access is not permitted on this storage account. -> [Help 1]
[ERROR] 
```
### Steps to reproduce the problem

[Create a linux function app with terraform](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/function_app#example-usage-linux)

[generate a azure function app with maven](https://docs.microsoft.com/en-us/learn/modules/develop-azure-functions-app-with-maven-plugin/)

Update the `pom.xml` with correct `resource_group, function name, location` as defined in terraform step above.

Run`mvn clean package` 

Login with service principal and attempt deploy

```bash
az login --service-principal -u <client_secret> -p <password> -t <tenant_id> 
az account set -s <subscription_id>
mvn azure-functions:deploy
```

and it fails with above error.

Go to Terraform code and under `azurerm_storage_account` add `allow_blob_public_access = true` and re apply terraform.

Run `mvn azure-functions:deploy` and the app is deployed successfully

**Comment by Flanker32** [comment]
@vikramkamath Thanks for your report, we have fixed the blob access level issue in the new version, could you please upgrade to latest version(1.10.1) and try again?

**Comment by vikramkamath** [comment]
@Flanker32 I will let you know once I verify today

**Comment by vikramkamath** [comment]
Sorry for a late response. Not sure what had changed. Shortly after, I stopped noticing this issue with version `1.9.0` as well .... @Flanker32 thanks for looking into it!
