### ISSUE TITLE
doc: update wiki guide about authType

### ISSUE THREAD

**Issue by AimeSoleil** [microsoft/azure-maven-plugins#1390]
### Plugin name and version

azure-webapp-maven-plugin:1.12.0

### Plugin configuration in your `pom.xml`

😢  **Bad configuration**:

```
<auth>
   <type>azure_cli</type>
    <environment>AzureChina</environment>
</auth>
```
😄  **Good one**:

`<authType>azure_cli</authType>`

### Expected behavior

In Authentication wiki, expected to guide authType correctly. 
The (official wiki example)[https://github.com/microsoft/azure-maven-plugins/wiki/Authentication#azure-cli] is using:
```
<configuration>
     <auth><type>azure_cli</type></auth>
</configuration>
```
But should use:
`<authType>azure_cli</authType>`

### Actual behavior

The (official wiki example)[https://github.com/microsoft/azure-maven-plugins/wiki/Authentication#azure-cli] has wrong example for specifiy `authType`.

### Steps to reproduce the problem

N/A

**Comment by andxu** [comment]
@AimeSoleil , thank you for the kindly notification, we will now release new versions of webapp/functions/spring cloud maven plugins which supports \<auth>\<type>

**Comment by andxu** [comment]
BTW, the wiki is updated

**Comment by andxu** [comment]
The wiki is updated
