### ISSUE TITLE
Dependency issue with DocumentDBInput vs cosmosdb on azure-functions-maven-plugin 

### ISSUE THREAD

**Issue by rjgmail88** [Microsoft/azure-maven-plugins#140]
### Plugin name and version
azure-functions-maven-plugin (0.2.0)

### Expected behavior
Project should be packaged with all dependancies. 

### Actual behavior
Error as mentioned.

### Steps to reproduce the problem
Started getting error after following commit on this repo.
rename documentdb to cosmosdb (#128)

```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:43 min
[INFO] Finished at: 2018-04-19T21:48:43-06:00
[INFO] Final Memory: 56M/509M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.microsoft.azure:azure-functions-maven-plugin:0.1.8:package (package-functions) on project **roomSync**: Execution package-functions of goal com.microsoft.azure:azure-functions-maven-plugin:0.1.8:package failed: A required class was missing while executing com.microsoft.azure:azure-functions-maven-plugin:0.1.8:package: com/microsoft/azure/serverless/functions/annotation/DocumentDBInput
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.microsoft.azure:azure-functions-maven-plugin:0.1.8
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy

[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------: com.microsoft.azure.serverless.functions.annotation.DocumentDBInput

```

**Comment by jdneo** [comment]
Duplicate with #139.

please set the the version of azure-functions-java-core to 1.0.0-beta-2 in the pom file.

**Comment by rjgmail88** [comment]
Thanks for quick update.

**Comment by rjgmail88** [comment]
I am still getting same error after setting the the version of azure-functions-java-core to 1.0.0-beta-2 in the pom file.

**Comment by jdneo** [comment]
@rjgmail88 May I ask what's the annotation you are using for the CosmosDB?

**Comment by jdneo** [comment]
Ah, I can repro this issue, and set version not help. Let's me check if there is any workaround for this. Sorry for the confusion.

**Comment by rjgmail88** [comment]
Sure. Thanks

**Comment by jdneo** [comment]
Hi @rjgmail88 .

Could you please try the following workaround.

-  Go to the package location of your local maven repo: `$HOME\.m2\repository\com\microsoft\azure\azure-functions-java-core`
- Open `maven-metadata-central.xml`
- Change the content that make sure no `1.0.0-beta-3` is in there

```xml
<?xml version="1.0" encoding="UTF-8"?>
<metadata>
  <groupId>com.microsoft.azure</groupId>
  <artifactId>azure-functions-java-core</artifactId>
  <versioning>
    <latest>1.0.0-beta-2</latest>
    <release>1.0.0-beta-2</release>
    <versions>
      <version>1.0.0-beta-1</version>
      <version>1.0.0-beta-2</version>
    </versions>
    <lastUpdated>20180419023505</lastUpdated>
  </versioning>
</metadata>

```
- Run `mvn clean package` again for your project

**Comment by jdneo** [comment]
@rjgmail88 @anky2209 

Just released a hot fix for this.

Here is the solution for any user who encountered this problem:

- set the version of `azure-functions-java-core` to `1.0.0-beta-2`.
- set the version of `azure-functions-maven-plugin` to `0.2.1`.

**Comment by rjgmail88** [comment]
@jdneo Your hot fix worked. Thanks much. Happy Friday !
