### ISSUE TITLE
Azure Functions Maven Plugin template doesn't include Kafka

### ISSUE THREAD

**Issue by TsuyoshiUshio** [microsoft/azure-maven-plugins#1423]
This is not the issue, this is for tracking progress of the work. I'm not sure if RabbitMQ is planned or not.

### Plugin name and version
1.10.1
### Plugin configuration in your `pom.xml`
default

### Expected behavior
`mvn azure-functions:add` includes Kafka (at least) 

### Actual behavior

```bash
Choose from below options as template for new function 
0. HttpTrigger
1. BlobTrigger
2. QueueTrigger
3. TimerTrigger
4. EventGridTrigger
5. EventHubTrigger
6. CosmosDBTrigger
7. ServiceBusQueueTrigger
8. ServiceBusTopicTrigger
```

### Steps to reproduce the problem

```bash
mvn archetype:generate -DarchetypeGroupId=com.microsoft.azure -DarchetypeArtifactId=azure-functions-archetype -DjavaVersion=8
https://github.com/Azure/azure-functions-core-tools/issues/2562
```

@pragnagopa

**Comment by pragnagopa** [comment]
Issue: https://github.com/microsoft/azure-maven-plugins/issues/1197 is tracking adding RabbitMQ template

Yes, I agree we should track work-item for Kafka trigger as well.

**Comment by Flanker32** [comment]
Pr for Kafka is ready, https://github.com/microsoft/azure-maven-plugins/pull/1410.

We hold the PR as Kafka extension is not included in the functions extensions bundle, as maven template could only add the content, but Kafka need to add the `extension.csproj` now.

**Comment by TsuyoshiUshio** [comment]
Thanks @Flanker32 
That's make sense. We will let you know once Bundle Template has been released.

**Comment by Flanker32** [comment]
Kaffa template has been added to functions maven plugin, so close this issue
