### ISSUE TITLE
Environment Variables are not pushed anymore

### ISSUE THREAD

**Issue by blacelle** [microsoft/azure-maven-plugins#1466]
When switching from com.microsoft.azure:azure-webapp-maven-plugin:1.12.0 to com.microsoft.azure:azure-webapp-maven-plugin:1.13.0, the plugin does not set environment variables anymore.

It seems not to push both:

- implicit environment variables (like DOCKER_CUSTOM_IMAGE_NAME)
- explicit environment variables (as defined in appSettings)

**Comment by Flanker32** [comment]
@blacelle Thanks a lot for your report and sorry for the trouble, this is an known issue which has been fixed in the webapp-maven-plugin:1.14.0, could you please upgrade the plugin and try again?

**Comment by blacelle** [comment]
@Flanker32 Thanks for the feedback. But it also appears in 1.14.0. I tried being more precise indicating the issue popped in 1.13.0 however I observed it initially but upgrading from 1.12 to 1.14.

**Comment by Flanker32** [comment]
@blacelle Thanks for your feedback. Could you please share me a demo project with 1.14.0? I tried to deploy a docker app with appsettings with maven plugin 1.14.0 and it seems works well.

**Comment by blacelle** [comment]
@Flanker32 Any news on this? Thanks

**Comment by Flanker32** [comment]
@blacelle Sorry but I could not repro this issue, could you please try update to the latest maven plugin and try again? Or could you please share a demo configuration for your project?
