### ISSUE TITLE
plugin does not honor ${git.commit.id.abbrev} in <imageName>

### ISSUE THREAD

**Issue by Incarnation-p-lee** [Microsoft/azure-maven-plugins#149]
### Plugin name and version
azure-webapp-maven-plugin 1.1.0
### Plugin configuration in your `pom.xml`
```
		<docker.image.prefix>xxxxxx.azurecr.io</docker.image.prefix>
                <docker.image.name>azure-xxxxxx-xxxxxx</docker.image.name>
		<docker.image.tag>${git.commit.id.abbrev}-${maven.build.timestamp}</docker.image.tag>
		<docker.image>${docker.image.prefix}/${docker.image.name}</docker.image>

		<containerSettings>
			<imageName>${docker.image}:${docker.image.tag}</imageName>
			<serverId>${azure.cr.server}</serverId>
			<registryUrl>https://${docker.image.prefix}</registryUrl>
		</containerSettings>
```
### Expected behavior
should be read git version as abbrev
### Actual behavior
[INFO] 509-byte body:
{"id":"/subscriptions/685ba005-af8d-4b04-8f16-a7bf38b2eb5a/resourceGroups/gremlin-test-4-11/providers/Microsoft.Web/sites/azure-spring-cloud/config/appsettings","name":"appsettings","type":"Microsoft.Web/sites/config","location":"Japan East","tags":{},"properties":{"PORT":"8080","DOCKER_REGISTRY_SERVER_PASSWORD":"XXXXXXXXXXXXXXXXXXXXXXXX","DOCKER_REGISTRY_SERVER_URL":"https://XXXXXXX.azurecr.io","DOCKER_REGISTRY_SERVER_USERNAME":"XXXXXX","DOCKER_CUSTOM_IMAGE_NAME":"XXXXXX.azurecr.io/azure-spring-cloud:${git.commit.id.abbrev}-2018_05_08-01_55"}}

### Steps to reproduce the problem
Use git.commit.id.abbrev in pom

**Comment by jdneo** [comment]
@Incarnation-p-lee 

To parse such git information, you may need the help for `[maven-git-commit-id-plugin](https://github.com/ktoso/maven-git-commit-id-plugin)`

**Comment by Incarnation-p-lee** [comment]
@jdneo 
Thanks for you response. Actually I use this plugin in below, it works well in dockerfile-maven-plugin but still keep place hold in this plugin.
```
			<plugin>
				<groupId>pl.project13.maven</groupId>
				<artifactId>git-commit-id-plugin</artifactId>
				<version>2.2.4</version>

				<executions>
					<execution>
						<goals>
							<goal>revision</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
````

**Comment by jdneo** [comment]
As far as I know, this might possibly not be an issue related with the azure webapp plugin. As a plugin, the context is given by Maven. The `${git.commit.id.abbrev}` is still there is because `<docker.image.tag>` is not parsed correctly, which is out of our scope.

You might see some similar issues about this if you search it in the [maven-git-commit-id-plugin repo](https://github.com/ktoso/maven-git-commit-id-plugin) or in Stackoverflow. For a quick workaround, call `mvn package azure-webapp:deploy` instead of `mvn azure-webapp:deploy` might help.

**Comment by Incarnation-p-lee** [comment]
@jdneo 
Thanks for you explain. So you mean that command `mvn azure-webapp:deploy` do not packaging when deploying. The mvn context cannot provide that information without packaging process and we need add `package` to deploy command. Do I understanding the root cause correctly ?

**Comment by jdneo** [comment]
mvn azure-webapp:deploy do not package? - No, it does not execute packaging.

Root cause could either be misusing the maven-git-commit-id plugin (for example, wrong configuration set) or this is an issue/bug related with that, which need further investigation.

**Comment by Incarnation-p-lee** [comment]
OK, thanks, help a lot. I add execution with `<phase>packaging</phase>`. It works well as expected. That is the reason finally.
