### ISSUE TITLE
Endgame 2021 May release 

### ISSUE THREAD

**Issue by andxu** [microsoft/azure-maven-plugins#1533]
###  Prepare bit
add the following sections in maven `settings.xml`
```xml
<profiles>
  <profile>
    <id>archetype</id>
    <activation>
      <activeByDefault>true</activeByDefault>
    </activation>
    <repositories>
      <repository>
        <id>archetype</id>
        <url>https://oss.sonatype.org/content/repositories/commicrosoftazure-4697/</url>
        <releases>
          <enabled>true</enabled>
        </releases>
        <snapshots>
          <enabled>true</enabled>
        </snapshots>
      </repository>
    </repositories>
    <pluginRepositories>
      <pluginRepository>
        <id>commicrosoftazure</id>
        <name>commicrosoftazure</name>
        <url>https://oss.sonatype.org/content/repositories/commicrosoftazure-4697/</url>
      </pluginRepository>
    </pluginRepositories>
  </profile>
</profiles>
```

### Features
| Features | Owner | Verifier | Tester | Verified | 
|---|---|---|---|---|
| [one deployment](https://dev.azure.com/mseng/VSJava/_sprints/taskboard/Java%20Azure%20Tooling/VSJava/Sprint%20187?workitem=1829098) | andxu| qianjin|cindy||

### Features
| Features | Owner | Verifier | Tester | Verified | 
|---|---|---|---|---|
| [track2 migration](https://dev.azure.com/mseng/VSJava/_sprints/taskboard/Java%20Azure%20Tooling/VSJava/Sprint%20187?workitem=1836155) | hanxiao| miller|||

### Features
| Features | Owner | Verifier | Tester | Verified | 
|---|---|---|---|---|
| [track2 migration](https://dev.azure.com/mseng/VSJava/_sprints/taskboard/Java%20Azure%20Tooling/VSJava/Sprint%20187?workitem=1836151) | miller|qianjin |||

**Comment by v-yuyul** [comment]
#### Test Pass
- Feature: Azure Web App maven plugin 1.15.0
- Tester: Cindy on 5/25
- Cases:

|With bits 4692|With bits 4697|  
|------|---|
|Can deploy to web app on linux: deploy jar, war and ear|Can deploy to web app on windows/linux: deploy jar, war|
|Can update after edit project code||

**Comment by SunnyChen1** [comment]
Verify maven spring cloud 1.6.0 on commicrosoftazure-4697, new issue: [#1846902](https://dev.azure.com/mseng/VSJava/_backlogs/backlog/Java%20Azure%20Tooling/Stories/?workitem=1846902); known issue [#1839045](https://dev.azure.com/mseng/VSJava/_workitems/edit/1839045)--Sunny,PanLei

**Comment by SunnyChen1** [comment]
Verify maven function on commicrosoftazure-4698, find the 6 new issues: [#1847373​](https://dev.azure.com/mseng/VSJava/_workitems/edit/1847373), [#1847375](https://dev.azure.com/mseng/VSJava/_workitems/edit/1847375), [#1847377](https://dev.azure.com/mseng/VSJava/_workitems/edit/1847377),[#1847379](https://dev.azure.com/mseng/VSJava/_workitems/edit/1847379), 
[#1847383](https://dev.azure.com/mseng/VSJava/_workitems/edit/1847383), [#1847385](https://dev.azure.com/mseng/VSJava/_workitems/edit/1847385)-Sunny,Yuan&Cindy
