### ISSUE TITLE
Is there a maven plugin to help deploy ARM template?

### ISSUE THREAD

**Issue by saragluna** [microsoft/azure-maven-plugins#1539]
This is a question/feature requests: is there a maven plugin to help deploy ARM template?

**Comment by andxu** [comment]
No maven plugin, but in intellij azure toolkit, you can deploy a arm template.

![image](https://user-images.githubusercontent.com/17075863/119474334-9f3c7300-bd7e-11eb-8c41-6a773715923c.png)
