### ISSUE TITLE
Redeploy on App Service Windows throws error

### ISSUE THREAD

**Issue by selvasingh** [Microsoft/azure-maven-plugins#16]
Here is the redeploy error:

`ERROR] Failed to upload directory: /Users/selvasingh/GitHub/demo/gs-spring-boot/complete/target/azure-webapps/maven-web-app-99758 --> /site/wwwroot`

**Comment by xscript** [comment]
Sample error message.
![image](https://user-images.githubusercontent.com/2300784/29065194-dea21380-7c5d-11e7-9bbd-66e65a579e5a.png)

**Comment by xscript** [comment]
Solution is adding configuration element <stopAppDuringDeployment> like [here](https://github.com/Microsoft/azure-maven-plugins/blob/master/azure-webapp-maven-plugin/src/it/windows-ftp/pom.xml#L27) with latest version 0.1.5.
