### ISSUE TITLE
Explicit option to block automatic resource/plan/app creation

### ISSUE THREAD

**Issue by sgalles** [microsoft/azure-maven-plugins#1651]
When the plugin is used to deploy on a resource/plan/app that was already manually created, it would be nice to have an option that explicitly disables the accidental automatic creation of any Azure resource/plan/app in the Subscription.
Because when there's a  misconfiguration/typo in my pom.xml, or if I'm on the wrong Subscription, I'd like an explicit error (resource not found...) not the creation of the  wrong resource/plan/app at the wrong place

Thanks

**Comment by andxu** [comment]
Would you like a confirm parameter in deploy, which actually lists all the operations/changes(only do read operation on your subscription) and when you press 'Y', it will continue to deploy (very similar to the terraform plan command: https://www.terraform.io/docs/cli/commands/plan.html)

mvn azure-webapp:deploy --confirm

**Comment by yucwan** [comment]
What if we add a new parameter like:
mvn azure-webapp:deploy **--prevent-creation**
which will always try to update existing Azure resources and prevent creating any resource group/app service plan/app service.

**Comment by sgalles** [comment]
Hi, thanks for your answers, and sorry for the delayed response.
A flag on the CLI could be useful for certain use cases, but ideally I was rather looking for something that doesn't depend on the user doing the right thing with the CLI command.
To put it differently I was looking for a flag directly in the configuration of the plugin in the XML file that would prevent all users from creating new resources _by default_. Because in my case, for instance, a user connected on the wrong subscription wouldn't even know that he is going to create new resources, and wouldn't even think about adding the new `--prevent-creation` option.

**Comment by andxu** [comment]
https://github.com/microsoft/azure-maven-plugins/pull/1762, use `-Dazure.webapp.create.skip=true` or `-DskipCreateWebApp`.

**Comment by andxu** [comment]
or use pom configuration:
```xml
   <plugin>
        <groupId>com.microsoft.azure</groupId>
        <artifactId>azure-webapp-maven-plugin</artifactId>
        <version>2.2.0</version>
        <configuration>
           <resourceGroup>andxu-test-rg</resourceGroup>
          <appName>andxu-test-app</appName>
          <region>westus</region>
          <skipCreateWebApp>true</skipCreateWebApp>
        </configuration>
      </plugin>
```
