### ISSUE TITLE
Support Jar deploy

### ISSUE THREAD

**Issue by jdneo** [Microsoft/azure-maven-plugins#168]
- [x] Merge PR: #167
- [x] Re-organize the deploy logic, to make sure war, jar & ftp can works for all kinds of Web Apps (Windows, Linux, Containers)
- [x] Add unit test
- [x] Add integration test
- [x] Update documents & README
- [x] Run tests & verification

**Comment by jdneo** [comment]
We also need to change checking method for war & jar deploy to make sure it will not block container Web App.

**Comment by jdneo** [comment]
Hi @brunoborges,

We are working on the integration works for the Jar deploy and find some problems. May need your suggestions.

Currently if the user does not set the deployment type in the plugin configuration, we will leverage the `<packaging>` field to decide which deployment type will be used. This decision may have several problems in the following scenario:
 - When user does not want to deploy anything, just update the application settings, provision a resources, etc..
- When user is using Web App for Containers, he only wants to change the image name setting for the Web App.

Can we still needs to check if a valid deployment type is set during the execution. And do jar/war/ftp deploy if user explicitly set the deployment type. What do you think?

**Comment by brunoborges** [comment]
I believe what we need is a new Deployment Type called "AUTO". This way developers can set NONE for the use case you are talking about, and AUTO would be default (to look into <packaging>).

What do you think?

**Comment by brunoborges** [comment]
Although frankly, I think this plugin should only be about deployment, and not configuration changes. It is weird to have the functionality of building a Maven project that will not deploy the artifact to somewhere, just update the runtime configuration. 

We should consider removing the feature about updating config without redeployment. It does not make sense in the context of a Maven lifecycle.

**Comment by jdneo** [comment]
I see. But I still do not want to block those container Web App users due to our AUTO deployment. Maybe we can check what the runtime user is using. And printing a warning instead of error if the runtime is Container?

**Comment by brunoborges** [comment]
The flow is like this: 

1. Plugin checks _deploymentType_.
1. If set to NONE, nothing is deployed
1. If set to JAR/WAR/FTP, does those
1. If set to AUTO not set at all (AUTO is default), it inspects _packaging_ of the Maven artifact (jar/war)

This should be sufficient.

**Comment by jdneo** [comment]
@brunoborges I see, that makes sense!

**Comment by brunoborges** [comment]
I will code that one for you. PR coming soon.

**Comment by brunoborges** [comment]
Alright, check PR #216
