### ISSUE TITLE
Deployment Fails Successfully - Unexpected character

### ISSUE THREAD

**Issue by mrm9084** [microsoft/azure-maven-plugins#1712]
### Plugin name and version
<groupId>com.microsoft.azure</groupId>
<artifactId>azure-webapp-maven-plugin</artifactId>
<version>2.1.0</version>

### Plugin configuration in your `pom.xml`
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>com.microsoft.azure</groupId>
                <artifactId>azure-webapp-maven-plugin</artifactId>
                <version>2.1.0</version>
                <configuration>
                    <schemaVersion>v2</schemaVersion>
                    <subscriptionId>${SUBSCRIPTION_ID}</subscriptionId>
                    <resourceGroup>${RG}</resourceGroup>
                    <appName>${APP_NAME}</appName>
                    <pricingTier>P1v2</pricingTier>
                    <region>westus2</region>
                    <runtime>
                        <os>Linux</os>
                        <javaVersion>Java 11</javaVersion>
                        <webContainer>Java SE</webContainer>
                    </runtime>
                    <appSettings>
                        <property>
                            <name>SUB_ID</name>
                            <value>01</value>
                        </property>
                    </appSettings>
                    <deployment>
                        <resources>
                            <resource>
                                <directory>${project.basedir}/target</directory>
                                <includes>
                                    <include>*.jar</include>
                                </includes>
                            </resource>
                        </resources>
                    </deployment>
                </configuration>
            </plugin>
        </plugins>
    </build>

### Expected behavior
Deploys Successfully without error.

### Actual behavior
Everything seems to deploy fine, but a large error is given.
[error-log.txt](https://github.com/microsoft/azure-maven-plugins/files/7009300/error-log.txt)

### Steps to reproduce the problem
Happens every time I deploy.

**Comment by Flanker32** [comment]
@mrm9084 Thanks for your report, according to the log it seems that there are some issues with the service host that return 502 error code. I tried to create a spring boot web app with same runtime and it seems works well. Could you please try create a new web app instance in another region and see whether the issue still exists?

**Comment by mrm9084** [comment]
@Flanker32 I have tried in a few different regions and get the same issues.
