### ISSUE TITLE
Get status code 429 "TooManyRequests" when deploy TimerTrigger

### ISSUE THREAD

**Issue by JanusWu** [Microsoft/azure-maven-plugins#177]
### Plugin name and version
![image](https://user-images.githubusercontent.com/17060520/41344116-e7a6e104-6f32-11e8-9e3f-7cf76a139732.png)

### Expected behavior
Deploy success.

### Actual behavior
![image](https://user-images.githubusercontent.com/17060520/41344163-05b84156-6f33-11e8-9d9c-167962db44a9.png)

**Comment by jdneo** [comment]
@JanusWu Will this error disappear if you redeploy the functions?

**Comment by JanusWu** [comment]
Yes, this error disappear after I wait for a few minutes and then deploy again.

**Comment by jdneo** [comment]
Seems it is caused by request quota. Close it for now.
