### ISSUE TITLE
"Required parameter AccessKey is missing" on WebApp with Mount

### ISSUE THREAD

**Issue by blacelle** [microsoft/azure-maven-plugins#1790]
### Plugin name and version

					<groupId>com.microsoft.azure</groupId>
					<artifactId>azure-webapp-maven-plugin</artifactId>
					2.2.0

### Plugin configuration in your `pom.xml`

				<plugin>

					
					<groupId>com.microsoft.azure</groupId>
					<artifactId>azure-webapp-maven-plugin</artifactId>
					<configuration>
						
						
						<auth>
							
							
							<serverId>azure-auth</serverId>
						</auth>

						
						<authType>service_principal</authType>
						<authentication>
							
							<serverId>azure-auth</serverId>
						</authentication>

						
						<allowTelemetry>false</allowTelemetry>

						<appServicePlanResourceGroup>${azure.resourceGroup}</appServicePlanResourceGroup>
						<appServicePlanName>${azure.appServicePlanName}</appServicePlanName>

						<resourceGroup>${azure.resourceGroup}</resourceGroup>
						<appName>${azure.appName}</appName>

						
						<region>francecentral</region>

						<deploymentType>none</deploymentType>
						
						<subscriptionId>${azure.subscriptionId.datasharing}</subscriptionId>

						
						<schemaVersion>v1</schemaVersion>

						<runtime>
							<os>docker</os>

							
							<serverId>${docker.registry.root}</serverId>
							<registryUrl>https://${docker.registry.root}</registryUrl>
							
							<image>${docker.image.qualifiedNameNoTag}:${docker.tag}</image>
						</runtime>

						<appSettings>
							
							
							
							
							<property>
								<name>WEBSITES_PORT</name>
								<value>${azure.port}</value>
							</property>
							<property>
								
								
								<name>SPRING_PROFILES_ACTIVE</name>
								<value>${azure.spring.profiles.active}</value>
							</property>
							<property>
								
								<name>WEBSITES_CONTAINER_START_TIME_LIMIT</name>
								
								
								
								<value>300</value>
							</property>
						</appSettings>
					</configuration>
					<executions>
						
						<execution>
							<id>deployWebApp</id>
							<phase>deploy</phase>
							<goals>
								<goal>deploy</goal>
							</goals>
						</execution>
					</executions>
				</plugin>

### Expected behavior

My WebApp has a mounted storage:

![image](https://user-images.githubusercontent.com/2117911/135271382-54bff8e6-20f7-4e98-8d28-21b95ef73ff3.png)

### Actual behavior

I get an error:

14:56:16,691 [ERROR] Failed to execute goal com.microsoft.azure:azure-webapp-maven-plugin:2.2.0:deploy (deployWebApp) on project backoffice-server: deploy to Azure Web App with resource creation or updating: create or update Azure Web App (XXX) from config: Status code 400, "{"Code":"BadRequest","Message":"Required parameter AccessKey is missing.","Target":null,"Details":[{"Message":"Required parameter AccessKey is missing."},{"Code":"BadRequest"},{"ErrorEntity":{"ExtendedCode":"01010","MessageTemplate":"Required parameter {0} is missing.","Parameters":["AccessKey"],"Code":"BadRequest","Message":"Required parameter AccessKey is missing."}}],"Innererror":null}" -> [Help 1]

### Steps to reproduce the problem

The issue happens since we upgraded from 1.12.0

**Comment by Flanker32** [comment]
@blacelle Thanks for your report and really sorry for the late reply, This seems to be an external [issue ](https://github.com/Azure/azure-sdk-for-java/issues/24758)of Azure track 2 SDK, we will working with the SDK team to resolve the issue and will update here once there are updates, really sorry for the inconvenience.

**Comment by Flanker32** [comment]
@blacelle Web App Maven Plugin 2.2.2 has been released, which include fix for this issue, could you please try again with the lates version? Thanks for your report and really sorry for the trouble.
