### ISSUE TITLE
There is no function under Functions after deployed service bus demo project to Azure. 

### ISSUE THREAD

**Issue by JanusWu** [Microsoft/azure-maven-plugins#180]
### Plugin name and version
![image](https://user-images.githubusercontent.com/17060520/41401797-56e00abc-6ff3-11e8-8a53-2ae4b766041b.png)

### Expected behavior
The demo service bus function can be triggered successfully.

### Actual behavior
The demo project can be deployed to Azure. But there is no function under Functions.
![image](https://user-images.githubusercontent.com/17060520/41402246-60113b8c-6ff4-11e8-9760-ef227ea807c0.png)

### Steps to reproduce the problem
Get service bus demo project from:  \\\vwdbuild01\temp\v-mona\azurefunctions\function-demo1.zip

1. Preparation:
	- Change the plugin version for test in pom.xml
	- Provision a service bus
	- Add a queue named 'hello' in the service bus
	- Get the connection string of the service bus
	- Update the connection strings in the project
		- In pom file
			
```
                <property>
                     <name>servicebusconnection</name>
                     <value>{connection string}</value>
                </property>
```
		- In \src\main\js\helloMessageProducer.js, line 15

			var serviceBusService = azure.createServiceBusService({connection string}).withFilter(retryOperations);

2. Package
	mvn clean package

3. Deploy
	mvn azure-functions: deploy

4. Start the message producer
	cd src/main/js
	npm install
	node helloMessageProducer.js

5. Verify
	Go to portal -> open the function page -> open the log panel
	send msg by message producer
	See if the function can be triggered

**Comment by jdneo** [comment]
There are 2 reasons may cause this issue:
- Package name and dependency in pom need to be updated: https://github.com/Azure/app-service-announcements/issues/112#issue-327919928
- There is a regression issue for functions-core-tools: https://github.com/Azure/azure-functions-core-tools/issues/531

**Comment by JanusWu** [comment]
This issue only occurs on Function CLI version 2.0.1-beta.29.
I can test the service bus demo project successfully (locally and deployed on azure) with Function CLI version 2.0.1-beta.28.

**Comment by jdneo** [comment]
Fixed in https://github.com/Azure/azure-functions-core-tools/issues/531
