### ISSUE TITLE
Functions deploy failing with error: parameter properties has an invalid value

### ISSUE THREAD

**Issue by rajchandvaniya** [Microsoft/azure-maven-plugins#1809]
azure-functions-maven-plugin version: 1.14.0

```
<plugin>
                <groupId>com.microsoft.azure</groupId>
                <artifactId>azure-functions-maven-plugin</artifactId>
                <version>${azure.functions.maven.plugin.version}</version>
                <configuration>
                    <!-- function app name -->
                    <appName>${function.name}</appName>
                    <!-- function app resource group -->
                    <resourceGroup>${function.resourcegroup}</resourceGroup>
                    <!-- function app service plan name -->
                    <appServicePlanName>${function.appserviceplan}</appServicePlanName>
                    <!-- function app region-->
                    <!-- refers https://github.com/microsoft/azure-maven-plugins/wiki/Azure-Functions:-Configuration-Details#supported-regions for all valid values -->
                    <region>westus</region>
                    <!-- function pricingTier, default to be consumption if not specified -->
                    <!-- refers https://github.com/microsoft/azure-maven-plugins/wiki/Azure-Functions:-Configuration-Details#supported-pricing-tiers for all valid values -->
                    <pricingTier>consumption</pricingTier>
                    <!-- Whether to disable application insights, default is false -->
                    <!-- refers https://github.com/microsoft/azure-maven-plugins/wiki/Azure-Functions:-Configuration-Details for all valid configurations for application insights-->
                    <disableAppInsights>false</disableAppInsights>
                    <runtime>
                        <!-- runtime os, could be windows, linux or docker-->
                        <os>windows</os>
                        <javaVersion>8</javaVersion>
                    </runtime>
                    <appSettings>
                        <property>
                            <name>FUNCTIONS_EXTENSION_VERSION</name>
                            <value>~3</value>
                        </property>
                    </appSettings>
                </configuration>
                <executions>
                    <execution>
                        <id>package-functions</id>
                        <goals>
                            <goal>package</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```
I've created the project using following command
`mvn archetype:generate "-DarchetypeGroupId=com.microsoft.azure" "-DarchetypeArtifactId=azure-functions-archetype" "-DjavaVersion=8"`

It is HTTPBinding function.

I'm able to locally run it 
```
mvn clean package
mvn azure-functions:run
```

Deployment of the function is failing
`mvn azure-functions:deploy`

Error:
`com.azure.resourcemanager.appservice.models.DefaultErrorResponseErrorException: Status code 400, "{"Code":"BadRequest","Message":"The parameter properties has an invalid value.","Target":null,"Details":[{"Message":"The pa
rameter properties has an invalid value."},{"Code":"BadRequest"},{"ErrorEntity":{"ExtendedCode":"51008","MessageTemplate":"The parameter {0} has an invalid value.","Parameters":["properties"],"Code":"BadRequest","Message":"The param
eter properties has an invalid value."}}],"Innererror":null}`

[Uploading deploy-error.txt…]()

**Comment by rajchandvaniya** [comment]
[deploy-error.txt](https://github.com/microsoft/azure-maven-plugins/files/7445966/deploy-error.txt)

**Comment by Flanker32** [comment]
@rajchandvaniya Thanks for your report, I tried the same configuration and it seems works fine in my project. Could you please help the project to reproduce the issue? By the way, could you please share the authentication method for your deployment?

**Comment by rajchandvaniya** [comment]
Project: https://github.com/rajchandvaniya/azure-function-http-sample (its the default function that gets created through mvn archtype)

Authentication Method: az cli login using device code method

**Comment by Flanker32** [comment]
@rajchandvaniya Thanks for your response, I tried the project https://github.com/rajchandvaniya/azure-function-http-sample and it works fine for me for both create and updates.  Did you tried some old azure libraries before, if so, could you please clean the azure libraries in `.m2` and try again? 
Besides, did this issue also occurs for other azure tools? Could you please help try create a function with azure cli? You may get the guidance [here](https://docs.microsoft.com/en-us/azure/azure-functions/scripts/functions-cli-create-serverless).

**Comment by rajchandvaniya** [comment]
Thanks for all the help. I had not tried old libraries. I also tried using gradle plugin, deploying zip and creating function through cli, I'm getting the same error for all. It seems there might be something wrong with the subscription setup

**Comment by Flanker32** [comment]
@rajchandvaniya Thanks for your feedback and really sorry for the trouble, please submit an [App Service support ticket](http://aka.ms/CRI-WebApps) once you need further help.

**Comment by Flanker32** [comment]
Close this issue as this should be an account issue rather than the toolkit.
