### ISSUE TITLE
Support deploy function app to existing app service plan

### ISSUE THREAD

**Issue by JohnReeson** [Microsoft/azure-maven-plugins#183]
Use latest `1.0.0-beta-2` plugin to deploy function to existing app service plan.

[Configurations](https://github.com/Microsoft/azure-maven-plugins/blob/develop/azure-functions-maven-plugin/README.md#configurations) doesn't mention `appSevicePlanName` which is valid in web app plugin. Tried, didn't work. I don't see `appSevicePlanName` in [source code](https://github.com/Microsoft/azure-maven-plugins/blob/develop/azure-functions-maven-plugin/src/main/java/com/microsoft/azure/maven/function/AbstractFunctionMojo.java) either.

So is it possible for function or have I missed sth?

**Comment by jdneo** [comment]
I’m sorry, currently it’s not supported in function plugin. But we can add it in the future. I’ll let you know it when we have a detailed plan for support existing service plan for function😀

**Comment by jdneo** [comment]
Let’s keep this open since this is a feature request.

**Comment by mathursharp** [comment]
Can we deploy two azure java function apps in same app service plan (like B1 etc.. not shared one.) ?

**Comment by mathursharp** [comment]
@jdneo 
Is it by anyway possible to deploy two java azure function apps in same app service plan (considering it is not the shared one) ?

**Comment by jdneo** [comment]
Hi @mathursharp

Emm, currently it is not supported. And may I ask what do you mean by `shared one` in your question?

**Comment by mathursharp** [comment]
@jdneo  I meant the pricing tier "Shared compute: Free and Shared" .

**Comment by jdneo** [comment]
You can try this:
- In the Azure Portal, create a new Azure Functions, during the creation, you can host the Azure Functions in an existing App Service Plan
- In the pom file, filling the information about your Azure Functions, then the Maven plugin should be able to deploy it.

**Comment by selvasingh** [comment]
This is a must-have feature, please prioritize this

**Comment by TurtleBeach** [comment]
For Java functions, it seems to me there are at least two issues: (1) getting the "administration" correct when the Java function is moved to or created in an AppService plan, and more importantly (2) ensuring the Java runtime framework gets correctly installed on the (an) existing running VM already in the plan. The comment from @jdneo sort of side steps what to put in the POM - the only default property remotely related is the Resource Group. But without some specific statement from MS that using an existing resource group would automatically install the necessary Java runtime components, I am not willing to experiment with a running server that is almost "production".
Assuming getting Java functions into an AppService plan isn't really possible now, an ETA would be useful.

**Comment by MicahMcKittrick-MSFT** [comment]
FYI, I also have a customer who is looking for this feature 

https://social.msdn.microsoft.com/Forums/azure/en-US/aa80f3aa-e2a1-418c-9765-3c9a7b68cb4b/how-can-a-java-function-be-deployed-to-a-vm-under-an-app-service-plan?forum=AzureFunctions

I have seen many customers are opting to use Java Functions and I expect to see even more in the future. 

@jdneo would you be able to share the work item for this feature request? You can send it to me offline if you like :)

**Comment by jdneo** [comment]
@JohnReeson @mathursharp @TurtleBeach @MicahMcKittrick-MSFT @selvasingh

I wrote a draft version to support this feature. Could you please help try it when you have time? I'd like to make sure the requirements are correctly addressed before shipping the product.

Please follow these steps:
1. Clone the repo:
```
git clone git@github.com:Microsoft/azure-maven-plugins.git
cd azure-maven-plugins
```

2. Checkout to the feature branch:
```
git checkout cs/existing-app-plan
```

3. Build the plugin
```
mvn clean install -DskipTests
```

4. Go to your test function project, change the version of function plugin to `1.0.0-beta-3-SNAPSHOT`

5. Change the plugin configuration of function plugin:
```xml
<groupId>com.microsoft.azure</groupId>
<artifactId>azure-functions-maven-plugin</artifactId>
<configuration>
    <resourceGroup>${functionResourceGroup}</resourceGroup>
    <appName>${functionAppName}</appName>

    <!-- Only required if the app service plan is not in the same resource group of the function app -->
    <!-- If the resource group of the existing app service plan is the same as we defined above, this field does not need to set -->
    <appServicePlanResourceGroup></appServicePlanResourceGroup>

    <!-- The existing app service plan name -->
    <appServicePlanName>CentralUSPlan</appServicePlanName>
</configuration>
```

Please let me know if you meet any questions. Thanks

**Comment by TurtleBeach** [comment]
@TurtleBeach @jdneo in Item 3 that should be "... we deploy our function USING your test ..."
