### ISSUE TITLE
Move templates to functions templates repo

### ISSUE THREAD

**Issue by pragnagopa** [Microsoft/azure-maven-plugins#184]
### Plugin name and version
azure-functions-maven
Azure functions templates need to moved to https://github.com/Azure/azure-functions-templates
and maven plugin needs to be updated to consume from the repo above

**Comment by jdneo** [comment]
Sure. Do we have a long-term plan about where to host those templates? Consume templates from GitHub source directly looks strange to me.

**Comment by pragnagopa** [comment]
Discussed with @soninaren 
As of now, maven plugin is the only one consuming the functions java template. VSCode uses them via maven. So it makes sense for them to stay here.
@asavaritayal  - Let's revisit this issue, if portal quick start experience for Java needs to java templates.

**Comment by jdneo** [comment]
@pragnagopa Fine, but currently function templates repo already has several trigger templates. Do we need to remove them from there?

**Comment by pragnagopa** [comment]
Yes. Let's go ahead and delete templates from https://github.com/Azure/azure-functions-templates to avoid confusion and also to avoid updating templates in two repos.

**Comment by jdneo** [comment]
Cool. Then let's track the issue here: https://github.com/Azure/azure-functions-templates/pull/710
