### ISSUE TITLE
azure-spring-cloud-maven-plugin deployment memory config options 

### ISSUE THREAD

**Issue by bryandx** [Microsoft/azure-maven-plugins#1845]
The azure-spring-cloud-maven-plugin it currently has a deployment memoryInGB option.  The Azure Portal allows an option of 512 Mi. Can the plugin be enhanced to support that memory option.

**Comment by Flanker32** [comment]
@bryandx Thanks for your report, support for 0.5 memoryInGB was introduced in the preview version of azure rest api, which was not supported by Java SDK for now. We are working with SDK team to release this feature asap, and will update here once there are updates.

**Comment by wangmingliang-ms** [comment]
this feature has been added. please try the latest version.
