### ISSUE TITLE
Azure Spring Cloud Maven Plugin creating Java 8 app instead of Java 11 app

### ISSUE THREAD

**Issue by sadukie** [Microsoft/azure-maven-plugins#1937]
### Plugin name and version

**name**: azure-spring-cloud-maven-plugin
**version**: 1.8.0

Additional debugging information just in case:

**pricing tier**: standard
**region**: West US

I generated my configuration based off of the advanced options prompts from the config goal.

### Plugin configuration in your `pom.xml`

```xml
<plugin>
		<groupId>com.microsoft.azure</groupId>
		<artifactId>azure-spring-cloud-maven-plugin</artifactId>
		<version>1.8.0</version>
			  <configuration>
			      <clusterName>azure-spring-cloud-instance-name</clusterName>
			      <appName>our-app-name</appName>
			      <isPublic>true</isPublic>
			      <deployment>
			          <cpu>1</cpu>
			          <memoryInGB>1</memoryInGB>
			          <instanceCount>1</instanceCount>
			          <runtimeVersion>Java 11</runtimeVersion>
			          <resources>
			              <resource>
			                  <filtering/>
			                  <mergeId/>
			                  <targetPath/>
			                  <directory>${project.basedir}/target</directory>
			                  <includes>
			                      <include>*.jar</include>
			                  </includes>
			              </resource>
			          </resources>
			      </deployment>
			  </configuration>
</plugin>
```

### Expected behavior

When I run `mvn azure-spring-cloud:deploy` with the **runtimeVersion** set to `Java 11`, then I expect to see an app on my Azure Spring Cloud instance with a Java 11 runtime.

### Actual behavior

When I run `mvn azure-spring-cloud:deploy` with the **runtimeVersion** set to `Java 11`, I get an app on my Azure Spring Cloud instance with a Java 8 runtime.

![image](https://user-images.githubusercontent.com/106202/154345624-4eaccff2-427c-4329-815b-ea9ac35d706b.png)

Confirming this in Azure CLI, the runtime version shows Java_8, not Java 11 that would I expect.

### Steps to reproduce the problem

1. Create a Java Spring application that refers to the Azure Spring Cloud Maven Plugin.
2. Include Java 11 as the runtime version.
3. Run `mvn azure-spring-cloud:deploy` and then confirm the app built in the portal.

**Comment by wangmingliang-ms** [comment]
@sadukie Hi, thanks for reporting, but we are not able to reproduce this bug. 
is this issue stably reproduceable on your own machine?

**Comment by sadukie** [comment]
@wangmingliang-ms 

I am running this in a Git Bash terminal within Visual Studio Code. I am running on Windows 11 Professional with the 21H2 patch.

These are the steps that I am taking that you could repeat:

1. Create an Azure Spring Cloud instance:

```shell
AZURE_RESOURCE_GROUP=spring-cloud-test
AZURE_SPRING_CLOUD_NAME=sadukie-spring-cloud-test
az spring-cloud create -n $AZURE_SPRING_CLOUD_NAME -g $AZURE_RESOURCE_GROUP --sku Basic 
```
2. Go through [Build a Spring Boot microservice using Spring Cloud features](https://github.com/microsoft/azure-spring-cloud-training/blob/master/05-build-a-spring-boot-microservice-using-spring-cloud-features/README.md)  - Stop at the Create and deploy part.

3. Add this to the pom.xml:

```xml
<plugin>
	<groupId>com.microsoft.azure</groupId>
	<artifactId>azure-spring-cloud-maven-plugin</artifactId>
	<version>1.8.0</version>
</plugin>
```
4. Run: `mvn azure-spring-cloud:config -DadvancedOptions`.
   * app name: demo
   * public access: N
   * instance count: 1
   * cpu count per instance: 1
   * memory size: 1
   * runtime JAVA versoin: Java 11
   * JVM options: <blank>
   
   ```shell
Summary of properties:
Subscription id   : MY_SUBSCRIPTION_ID
Service name      : sadukie-spring-cloud-test
App name          : demo
Public access     : false
Instance count    : 1
CPU count         : 1
Memory size(GB)   : 1
Runtime Java version : Java 11
Confirm to save all the above configurations (Y/n): Y
```

This generated the XML in the pom.xml file:

```xml
<plugin>
	<groupId>com.microsoft.azure</groupId>
	<artifactId>azure-spring-cloud-maven-plugin</artifactId>
	<version>1.8.0</version>
	<configuration>			        
		<clusterName>sadukie-spring-cloud-test</clusterName>
		<appName>demo</appName>
		<isPublic>false</isPublic>
		<deployment>
			<cpu>1</cpu>
			<memoryInGB>1</memoryInGB>
			<instanceCount>1</instanceCount>
			<runtimeVersion>Java 11</runtimeVersion>
			<resources>
				<resource>
					<filtering/>
					<mergeId/>
					<targetPath/>
					<directory>${project.basedir}/target</directory>
					<includes>
						<include>*.jar</include>
					</includes>
				</resource>
			</resources>
		</deployment>
	</configuration>
</plugin>
```

5. Run `mvn azure-spring-cloud:deploy`.

During creation...
![image](https://user-images.githubusercontent.com/106202/154721137-78d0926e-1a0f-4c8b-b4d5-16d4f262e1e6.png)

Done creating...
![image](https://user-images.githubusercontent.com/106202/154721283-ea210794-36a2-49ac-8153-46d1d1ed00ae.png)

Deploying...
![image](https://user-images.githubusercontent.com/106202/154721743-d9a68912-1635-4fec-bcf7-53a6e1a8498d.png)


Hmm...  this wasn't working in my client's tenant. I'll go back to the project to see if we have something else causing this issue. 

Sorry. :(
