### ISSUE TITLE
java.lang.NullPointerException at com.microsoft.azure.maven.utils.MavenArtifactUtils.isExecutableJar (MavenArtifactUtils.java:50)

### ISSUE THREAD

**Issue by blacelle** [Microsoft/azure-maven-plugins#1989]
### Plugin name and version

	<groupId>com.microsoft.azure</groupId>
	<artifactId>azure-spring-cloud-maven-plugin</artifactId>
	<version>1.9.0</version>

### Plugin configuration in your `pom.xml`

```
				<plugin>
					<groupId>com.microsoft.azure</groupId>
					<artifactId>azure-spring-cloud-maven-plugin</artifactId>
					<version>1.9.0</version>
					<!-- https://github.com/microsoft/azure-maven-plugins/wiki/Azure-Spring-Cloud -->
					<configuration>
						<runtimeVersion>Java_11</runtimeVersion>
						<allowTelemetry>false</allowTelemetry>
						<appName>${azure.appName}</appName>
						<clusterName>${azure.env}-XXX-asc</clusterName>

						<!-- https://github.com/microsoft/azure-maven-plugins/wiki/Authentication#service-principles-in-plugin-configuration -->
						<auth>
							<serverId>azure-auth</serverId>
						</auth>

						<public>true</public>
						<isPublic>true</isPublic>

						<subscriptionId>${azure.subscriptionId}</subscriptionId>

						<!-- ??? -->
						<advancedOptions>true</advancedOptions>

						<!-- https://github.com/microsoft/azure-maven-plugins/wiki/Azure-Spring-Cloud%3A-Configuration-Details -->
						<deployment>
							<environment>
								<SPRING_PROFILES_ACTIVE>${azure.spring.profiles.active}</SPRING_PROFILES_ACTIVE>
							</environment>
						</deployment>

						<!-- About the lack of skip option -->
						<!-- https://github.com/microsoft/azure-maven-plugins/issues/1936 -->
					</configuration>

					<executions>
						<execution>
							<id>deployWebApp</id>
							<phase>deploy</phase>
							<goals>
								<goal>deploy</goal>
							</goals>
						</execution>
					</executions>
				</plugin>
```

### Expected behavior
A self-expressive error if something is wrong in my configuration

### Actual behavior

```
Caused by: java.lang.NullPointerException
    at com.microsoft.azure.maven.utils.MavenArtifactUtils.isExecutableJar (MavenArtifactUtils.java:50)
    at java.util.stream.ReferencePipeline$2$1.accept (ReferencePipeline.java:176)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining (ArrayList.java:1655)
    at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:484)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:474)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential (ReduceOps.java:913)
    at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect (ReferencePipeline.java:578)
    at com.microsoft.azure.maven.utils.MavenArtifactUtils.getExecutableJarFiles (MavenArtifactUtils.java:84)
    at com.microsoft.azure.maven.springcloud.config.ConfigurationParser.toDeploymentConfig (ConfigurationParser.java:39)
    at com.microsoft.azure.maven.springcloud.config.ConfigurationParser.parse (ConfigurationParser.java:22)
    at com.microsoft.azure.maven.springcloud.AbstractMojoBase.getConfiguration (AbstractMojoBase.java:124)
    at com.microsoft.azure.maven.springcloud.AbstractMojoBase.initTelemetryProxy (AbstractMojoBase.java:100)
    at com.microsoft.azure.maven.AbstractAzureMojo.execute (AbstractAzureMojo.java:505)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
```

### Steps to reproduce the problem

My command is `mvn azure-spring-cloud:deploy -Pazure,dev,deploySpringCloud -DskipTests -PskipStyle -X`, but I suppose this denotes something wrong in the considered input fatJar.

Given https://github.com/microsoft/azure-maven-plugins/blob/develop/azure-maven-plugin-lib/src/main/java/com/microsoft/azure/maven/utils/MavenArtifactUtils.java#L46-L54

    public static boolean isExecutableJar(File file) {
        try (final FileInputStream fileInputStream = new FileInputStream(file);
             final JarInputStream jarInputStream = new JarInputStream(fileInputStream)) {
            final Manifest manifest = jarInputStream.getManifest();
            return manifest.getMainAttributes().getValue("Main-Class") != null;
        } catch (IOException e) {
            return false;
        }
    }

I suppose `manifest.getMainAttributes()` is null in my case, and the exception should report this explicitly.

**Comment by blacelle** [comment]
The path to the faulty jar would also be helpful.

**Comment by Flanker32** [comment]
@blacelle Thanks for your report and sorry for the late reply, we will looking into this issue soon, as a workaround, you may use add the following configuration to your plugin configuration to set the artifact to deploy
```
            <configuration>
                ...
                <deployment>
                    ....
                    <resources>
                        <resource>
                            <filtering/>
                            <mergeId/>
                            <targetPath/>
                            <directory>${project.basedir}/target</directory>
                            <includes>
                                <include>{your_fat_jar}.jar</include>
                            </includes>
                        </resource>
                    </resources>
                </deployment>
            </configuration>
```

**Comment by blacelle** [comment]
Hello,

I feel my issue is not a lack of jar. It seems related to https://stackoverflow.com/questions/37783069/why-cant-i-extract-a-spring-boot-executable-jar

-> Hence, JarInputStream (supposedly) fails opening this file/finding a Manifest.

as the NPE hits `return manifest.getMainAttributes().getValue("Main-Class") != null;`

**Comment by Flanker32** [comment]
@blacelle Thanks for your message, could you please help check is there any fat jar in your target directory? If not, you may use spring-boot-maven-plugin to generate one, you may refer [document](https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/htmlsingle/#packaging) here. Then could you please specify the fat jar in spring cloud maven plugin configuration and try deploy again?

We will fix the NPE issue to get main class asap, will update here once we have any updates

**Comment by blacelle** [comment]
> could you please help check is there any fat jar in your target directory? If not, you may use spring-boot-maven-plugin to generate one, you may refer [document](https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/htmlsingle/#packaging) here.

@Flanker32 There is a fat jar, else your code would throw differently. it is generating using spring-boot-maven-plugin, but with `<executable>true</ executable>` (as suggested by the pointer to https://stackoverflow.com/questions/37783069/why-cant-i-extract-a-spring-boot-executable-jar).

**Comment by blacelle** [comment]
https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/htmlsingle/#goals-repackage-parameters-details-executable

**Comment by blacelle** [comment]
(I suppose this is a normal migration step from AppService (with a custom Dockerfile, referring to an entrypoint.sh script starting sshd then the fatjar with executable=true)).

**Comment by wangmingliang-ms** [comment]
@blacelle 
1. The NPE is unquestionably a bug, we'll fix it in the next release.
2. [this format of jar](https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/htmlsingle/#goals-repackage-parameters-details-executable) is not supported by Azure Spring Cloud(confirmed with @yuwzho) so we will keep taking this type of jar as NOT executable, you need change the configuration to make it compatible with Azure Spring Cloud.

---
BTW, is it necessary for you to run it directly? why is `java -jar` not acceptable? 
[Spring Boot with Docker](https://spring.io/guides/gs/spring-boot-docker/#:~:text=FROM%20openjdk%3A8%2Djdk%2Dalpine%0ARUN%20addgroup%20%2DS%20spring%20%26%26%20adduser%20%2DS%20spring%20%2DG%20spring%0AUSER%20spring%3Aspring%0AARG%20JAR_FILE%3Dtarget/*.jar%0ACOPY%20%24%7BJAR_FILE%7D%20app.jar%0AENTRYPOINT%20%5B%22java%22%2C%22%2Djar%22%2C%22/app.jar%22%5D)?

**Comment by blacelle** [comment]
> BTW, is it necessary for you to run it directly? why is java -jar not acceptable?

It is acceptable as a general rule of thumb, but not for our current way of deploying to AppService -> during the migration, we need to have both deployment OK (AppSerice and SpringCLoud) -> it is totally OK to require executable false (for SpringCloud) ; I suppose azure-spring-cloud documentation should be improved, and maybe the maven plugin should reject them explicitly.

-> For my own case, this can be closed. However, the doc + maven plugin code can be improved for other people in my case.

**Comment by wangmingliang-ms** [comment]
@blacelle
> I suppose azure-spring-cloud documentation should be improved, and maybe the maven plugin should reject them explicitly.

You are right, we'll fix the NPE and improve the error message, thanks

**Comment by wangmingliang-ms** [comment]
hi, @blacelle , we have fixed this issue, and the fixed be included in the coming released. 
you can try on branch `endgame-202204.deprecation`, the updated version of the plugin is `1.10.0`
