### ISSUE TITLE
The configuration command removes all new lines from the pom

### ISSUE THREAD

**Issue by JasonFreeberg** [Microsoft/azure-maven-plugins#1990]
### Plugin name and version

```
<groupId>com.microsoft.azure</groupId>
<artifactId>azure-webapp-maven-plugin</artifactId>
<version>2.5.0</version>
```

### Actual behavior

I ran the `:config` command and completed the form. The configuration was saved to my pom, but it _also_ removed every blank line on my pom, so I had to go and put these all back manually

![image](https://user-images.githubusercontent.com/18747768/161607158-a875a3c8-dba4-43e1-8bce-f9a553d009b8.png)

I don't think it's good for the plugin to change with the pom file this much:

![image](https://user-images.githubusercontent.com/18747768/161607252-6ca3897d-3f3c-4dc9-b112-fb902326e416.png)

### Expected behavior

Don't remove blank lines from the pom. People use them to help readability in large pom files.

**Comment by Flanker32** [comment]
@JasonFreeberg Thanks for your report, we will investigate this issue soon.

**Comment by wangmingliang-ms** [comment]
this issue should be fixed by commit https://github.com/microsoft/azure-maven-plugins/commit/a93f2d47b9a323ff3351472cf3c7d50b1777a0c0
