### ISSUE TITLE
Improve the setting structure for Web App plugin

### ISSUE THREAD

**Issue by jdneo** [Microsoft/azure-maven-plugins#200]
Currently the setting structure of the Web App plugin is somehow confusing. We need to simplify it.

**Comment by jdneo** [comment]
@brunoborges Let's discuss the structure design in this issue. Do you have any suggestions here?

**Comment by brunoborges** [comment]
We can merge PR #167 and look at this in a next release, or look at it now. What do you suggest?

**Comment by jdneo** [comment]
Agree that we can look at this in next release. Anyway, Let's just start discussion first. 😄

**Comment by jdneo** [comment]
@brunoborges Here is the new proposed setting structure, it has 3 major parts:

- basic settings: common for all Web Apps
- runtime settings: OS related
- deployment settings: deployment type related

```xml
<!-- basic settings -->
<resourceGroup />
<appName />
<region />
<pricingTier />
<appServicePlanResourceGroup />
<appServicePlanName />
<appSettings />
...

<!-- runtime settings -->
<runtime>
    ....
</runtime>

<!-- deployment settings -->

<deployment>
    ....
</deployment>
```
## Runtime settings
The runtime settings will be different according to what OS is chosen by user.
### Windows / Linux
```xml
<runtime>
    <os>windows/linux</os>
    <javaVersion />
    <javaMinorVersion />
    <webContainerType />
    <webContainerVersion />
</runtime>
```

### Docker
```xml
<runtime>
    <os>Docker</os>
    <imageName />
    <serverId />
    <registryUrl />
</runtime>
```

## Deployment settings
The deployment settings will be different according to what deployment type is chosen by user.

### FTP
```xml
<deployment>
    <type>ftp</type>
    <resources />
</deployment>
```

### WAR
```xml
<deployment>
    <type>war</type>
    <warFile />
    <path />
</deployment>
```

### JAR
```xml
<deployment>
    <type>jar</type>
    <jarFile />
</deployment>
```

Please let us know if you have any suggestions. 😄

**Comment by brunoborges** [comment]
Hey @jdneo , this is a great start. 

Here are a few things I think we can simplify further:

1. No need for `<jarFile>` and `<warFile>`... Just `<file>` 
1. Does it make sense to have `<path>`? I mean, is it possible to deploy two WAR apps on a single App Service instance? If not, this is irrelevant. Otherwise, it should be applicable for JAR as well, as they are web apps too. If yes, we should instead use `<context-root>`. It is easier understandable.
1. `<type>` must be optional (inspects `<packaging>` if type not set `[jar, war]`).
1. We can just have one `<java>` setting. Available options using the pattern *vendor*-*major*_*minor*. Customers should specify the exact version they want. We should not allow them to *not* set a minor version. It opens a can of worms; plus it is an anti-pattern to use *latest* without knowing what latest is.
1. `<imageName />` can be just `<image>` for Docker.
1. `<os>` should be `<platform>`. It makes more sense given its options. If in the future App Service allows Windows Containers, then we can go back and add `<os>`.

**Comment by jdneo** [comment]
@brunoborges thanks for the suggestions. 

> 1. No need for `<jarFile>` and `<warFile>`... Just `<file>` 

OK

> 2. Does it make sense to have `<path>`? I mean, is it possible to deploy two WAR apps on a single App Service instance? If not, this is irrelevant. Otherwise, it should be applicable for JAR as well, as they are web apps too. If yes, we should instead use `<context-root>`. It is easier understandable.

This is a feature provided by Web Containers (let's say, tomcat), but I don't think same thing can be achieved in Java SE Web App. the name `path` is actually following tomcat plugin's configuration. See: http://tomcat.apache.org/maven-plugin-2.0/tomcat7-maven-plugin/usage.html

> 3. `<type>` must be optional (inspects `<packaging>` if type not set `[jar, war]`).

Agree

> 4. We can just have one `<java>` setting. Available options using the pattern *vendor*-*major*_*minor*. Customers should specify the exact version they want. We should not allow them to *not* set a minor version. It opens a can of worms; plus it is an anti-pattern to use *latest* without knowing what latest is.

Yes we can only have one `<java>` here. Also maybe `<webContainerType />` and `<webContainerVersion />` can be combined into one `<WebContainer>`.
About the minor version problem, actually we are following the portal & Azure SDK's behavior here.
![image](https://user-images.githubusercontent.com/6193897/42552756-75ca1a4e-8510-11e8-897b-31dd372707a8.png)
In portal, user can select `newest` as the minor version number.

> 5. `<imageName />` can be just `<image>` for Docker.

OK

> 6. `<os>` should be `<platform>`. It makes more sense given its options. If in the future App Service allows Windows Containers, then we can go back and add `<os>`.

`<platform>` might make some confusion here. Since in Portal, platform is a configuration for 32bit or 64bit.
![image](https://user-images.githubusercontent.com/6193897/42552988-7797f3fe-8511-11e8-9bf6-474abbb42cb3.png)
We use `<os>` because it is the field name when creating a new Web App
![image](https://user-images.githubusercontent.com/6193897/42553031-9b1d9b26-8511-11e8-926a-d5f8a423da80.png)

**Comment by brunoborges** [comment]
Alright, so let's review:

1. Great. 
2. The reason Tomcat Maven plugin offers `<path>` (context root) is because one can deploy multiple apps to a single Tomcat instance, and therefore apps must run in unique context roots (`/myapp1`, `/myapp2`). This is not the case with App Service. One app, one Tomcat.
3. Awesome.
4. I will connect with @selvasingh to discuss this. It is a bad practice to allow users to choose `newest`. But I understand this is an issue with App Service.
5. Awesome.
6. So I guess we need to add `<platform>` int he plugin to allow user to set 32/64, and keep `<os>` for windows/linux/docker. Sounds good to me. Other settings should be done too (websockets, http version, always-on, managed pipeline).

**Comment by jdneo** [comment]
@brunoborges  Cool. Seems most of the questions are addressed.

Just some explanations for point 2.

Currently Windows Web App support deploy multiple apps into one app/tomcat. But Linux Web App has a limitation that can only deploy to ROOT now. As far as I know, the service team is working on supporting deploy to other than ROOT feature for Linux Tomcat Web App and will available soon. So <path> here is fine?

**Comment by jdneo** [comment]
This is what the structure looks like for now.

_**Updated at Tue Jul 17 2018 13:26:58 GMT+0800 (China Standard Time)**_

```xml
<!-- basic settings -->
<resourceGroup />
<appName />
<region />
<pricingTier />
<appServicePlanResourceGroup />
<appServicePlanName />
<appSettings />
...

<!-- runtime settings -->
<runtime>
    ....
</runtime>

<!-- deployment settings -->

<deployment>
    ....
</deployment>
```
## Runtime settings
The runtime settings will be different according to what OS is chosen by user.
### Windows / Linux
```xml
<runtime>
    <os>windows/linux</os>
    <javaVersion />
    <javaMinorVersion />
    <webContainerType />  - optional
    <webContainerVersion />  - optional
</runtime>
```

### Docker
```xml
<runtime>
    <os>docker</os>
    <image />
    <serverId />  - optional
    <registryUrl />  - optional
</runtime>
```

## Deployment settings
The deployment settings will be different according to what deployment type is chosen by user.

### FTP
```xml
<deployment>
    <type>ftp</type>  - optional
    <resources />  - optional
</deployment>
```

### WAR
```xml
<deployment>
    <type>war</type>  - optional
    <file />  - optional
    <path />  - optional
</deployment>
```

### JAR
```xml
<deployment>
    <type>jar</type>  - optional
    <file /> - optional
</deployment>
```

### AUTO
```xml
<deployment>
    <type>auto</type>  - optional
    ...
</deployment>
```

### NONE
```xml
<deployment>
    <type>none</type>  - optional
</deployment>
```

**Comment by brunoborges** [comment]
Looks really good. One feedback is with the indication of `optional`. For example, stating that `<type>none</type> - optional` gives the impression that `<deployment>` node can be empty.

Take a look for example on the [Cargo Maven Plugin configuration documentation](https://codehaus-cargo.github.io/cargo/Maven2+Plugin+Reference+Guide.html).

Another thing we might want to look at in the future is generating a documentation page using the Maven Plugin Plugin, following Maven standards. We can use special annotations in the javadoc that are aimed at documenting parameters and configuration elements.

**Comment by jdneo** [comment]
@brunoborges Thanks for the feedback. I'll reformat the table later.

**Comment by selvasingh** [comment]
These are good improvements, particularly the default deployment types. Auto deployment for Java SE target is Zip deploy.

**Comment by jdneo** [comment]
@selvasingh Yes we will use Zip as the back-end for jar deploy after the related feature is implemented.

**Comment by Flanker32** [comment]
Close it since schema V2 has completed.
