### ISSUE TITLE
Update the Azure Functions publish to use Zip Deploy instead of FTP 

### ISSUE THREAD

**Issue by jeffhollan** [Microsoft/azure-maven-plugins#203]
Work being done to update the Java SDKs to support Zip Deploy instead of FTP -- in conjunction with this we need to update the publish job for Azure Functions to use Zip Deploy.  Provides perf benefits and deployment benefits all-up.

@davidebbo as FYI who I believe is coordinating with the Java SDK team according to Asir

**Comment by jdneo** [comment]
Thank you for the feedback @jeffhollan. 👍 

just want to close this issue since it's duplicated with #179. Let's track this in #179.

We will implement zipDeploy when the API is available in Azure management lib for Java. @lenala is now working on that.
