### ISSUE TITLE
Build failing after upgrading azure:azure-functions-maven-plugin:1.19.0

### ISSUE THREAD

**Issue by rajashekarNampelli** [Microsoft/azure-maven-plugins#2097]
### Plugin configuration in your `pom.xml`
```
<plugin>
                <groupId>com.microsoft.azure</groupId>
                <artifactId>azure-functions-maven-plugin</artifactId>
                <version>1.19.0</version>
                <configuration>
                    <resourceGroup>${functionResourceGroup}</resourceGroup>
                    <appName>${functionAppName}</appName>
                    <region>${functionAppRegion}</region>
                    <appServicePlanName>java-functions-app-service-plan</appServicePlanName>
                    <runtime>
                        <!-- runtime os, could be windows, linux or docker-->
                        <os>windows</os>
                        <javaVersion>8</javaVersion>
                    </runtime>
                    <appSettings>
                        <!-- Run Azure Function from package file by default -->
                        <property>
                            <name>WEBSITE_RUN_FROM_PACKAGE</name>
                            <value>1</value>
                        </property>
                        <property>
                            <name>FUNCTIONS_EXTENSION_VERSION</name>
                            <value>~4</value>
                        </property>
                        <property>
                            <name>FUNCTIONS_WORKER_RUNTIME</name>
                            <value>java</value>
                        </property>
                    </appSettings>
                </configuration>
                <executions>
                    <execution>
                        <id>package-functions</id>
                        <goals>
                            <goal>package</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

### Expected behavior
The build should success.  mvn clean package azure-functions:run

### Actual behavior
Getting error for : mvn clean package azure-functions:run

[ERROR] Failed to execute goal com.microsoft.azure:azure-functions-maven-plugin:1.19.0:package (package-functions) on project <project_name>: File canonical
 paths are equal: 'C:\Projects\<project_name>\target\azure-functions\fn-name\<project_name>-1.51-SNAPSHOT.jar' (file1='C:\Projects\<project_name>\target\azure-functions\fn-name\<project_name>-1.51-SNAPSHOT.jar', file2='C:\Projects\<project_name>\target\az
ure-functions\fn-name\<project_name>-1.51-SNAPSHOT.jar')

### Steps to reproduce the problem
The same code base is working for the version : 1.10.1. It started giving problem when we upgrade to 1.19.0. 
FUNCTIONS_EXTENSION_VERSION=~4 is not supporting in 1.10.1 so we are trying to upgrade latest version.

**Comment by navintkr** [comment]
@Flanker32 could you please check this, it's blocking the development of a high critical app

**Comment by Flanker32** [comment]
@rajashekarNampelli @navintkr Thanks for your message and sorry for the trouble, could you please help share us the out of `mvn clean package -X` to help us better investigate this issue.

**Comment by Flanker32** [comment]
@rajashekarNampelli @navintkr Thanks for your report, it seems that our toolkit trying to copy resource (library/artifact) to the same location as its origin. 
During maven package, we will copy your artifact to staging directory (`${project_root}/target/azure-functions/${appName}`) and copy your dependencies to `${staging_directory}/lib`, could you please check did you save your library or project artifact to the same location? We will resolve this issue in our later release soon, thanks again for your report and sorry for the trouble.

**Comment by rajashekarNampelli** [comment]
@Flanker32 
Yes. We are saving to `${project_root}/target/azure-functions/${appName} `

`        <stagingDirectory>${project.build.directory}/azure-functions/${functionAppName}</stagingDirectory>
`
```

<plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.1.1</version>
                <configuration>
                    <outputDirectory>${project.build.directory}/azure-functions/${functionAppName}
                    </outputDirectory>
                    <appendAssemblyId>false</appendAssemblyId>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                    <archive/>
                </configuration>
                <executions>
                    <execution>
                        <id>make-assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

**Comment by Flanker32** [comment]
@rajashekarNampelli Thanks for your message, as a workaround, could you please change the output directory and try again? We are using `FileUtils` to copy resources and their latest release will throw exception in this case

**Comment by rajashekarNampelli** [comment]
@Flanker32 
Yes, it is working after changing the directory path. Thank you very much for your support.
