### ISSUE TITLE
Decide whether use Travis, AppVeyor or Azure Pipelines

### ISSUE THREAD

**Issue by brunoborges** [microsoft/azure-maven-plugins#217]
Currently the project has Travis *and* AppVeyor configured. Is there a particular reason for that?

**Comment by brunoborges** [comment]
@jdneo @yitao-zhang fyi...

**Comment by Alihamzehzadeh** [comment]
پشتیبانی کنید لطقا

**Comment by jdneo** [comment]
We are using AppVeyor for integration test now. And the README page will only show the AppVeyor's badge.

**Comment by brunoborges** [comment]
We should consider using Azure Pipelines moving forward .

**Comment by jdneo** [comment]
Ok. Reopen it. Will revisit it later.
