### ISSUE TITLE
All Trigger Types Not Available in IntelliJ IDEA IDE while adding the additional function to existing Java Azure Functions Project

### ISSUE THREAD

**Issue by mikeurnun** [Microsoft/azure-maven-plugins#2228]
### Plugin name and version
Maven plugins for Azure Functions

`<plugin>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-functions-maven-plugin</artifactId>
    <version>[Use the latest version above]</version>
</plugin>`

### Expected behavior
Whereas in VS Code, I can see the same scenario but I'm able to get all types of triggers by changing Template Filter: 
![IntelliJIdea](https://user-images.githubusercontent.com/88704316/218722770-2f3212f5-f265-476d-b408-268cae4da3da.gif) 
I cannot see the same template filter in IntelliJ IDEA IDE to see all the trigger or normally only 3 types of triggers available to add into the existing Java Project. 

### Actual behavior
But when we try to add the blob or Queue trigger to the existing Azure Functions Java Project, unable to see other than only 3 types of triggers:

<img width="528" alt="image" src="https://user-images.githubusercontent.com/113497539/218727245-4009ce7d-96bb-416a-b4a9-47fcb4d4be24.png">

### Steps to reproduce the problem
When We create New Azure Functions (Java) Project in the IntelliJ IDEA IDE, able to get most of the triggers: ![image](https://user-images.githubusercontent.com/88704316/218719834-41550e43-7799-4907-87c5-bdbdfdf70368.png) 

Reported by @PravallikaKothaveerannagari: MicrosoftDocs/azure-docs#105223

**Comment by Flanker32** [comment]
@mike-urnun-msft Thanks for your report, currently we are working on this feature, IntelliJ toolkits will share the same Function template as maven plugin in next release, which will be done at the end of February,

**Comment by mikeurnun** [comment]
> @mike-urnun-msft Thanks for your report, currently we are working on this feature, IntelliJ toolkits will share the same Function template as maven plugin in next release, which will be done at the end of February,

Thanks, @Flanker32!  @PravallikaKothaveerannagari I hope the answer above brings clarity & helps with the planning. I'm going to close this issue. If you have any additional concerns, please let me know.
