### ISSUE TITLE
Azure Functions deploy error if resource group name is not unique

### ISSUE THREAD

**Issue by pragnagopa** [microsoft/azure-maven-plugins#242]
### Plugin name and version
azure-functions-maven 1.0.0-beta-2
### Plugin configuration in your `pom.xml`
if deafult value is used for  functionResourceGroup deploy fails with wrong error

<functionResourceGroup>java-functions-group</functionResourceGroup>

### Expected behavior
Error should indicate a unique name must be used for resource group. Also, Archetype needs to be updated to append unique id to resource group name

### Actual behavior
[INFO] Starting deploying to Azure Functions test-functions-20180712090403798...
[INFO] Authenticate with Azure CLI 2.0
[INFO] Updating Azure Functions...
[INFO] Successfully updated Azure Functions test-functions-20180712090403798
[INFO]
[INFO] Step 1 of 4: Creating ZIP package...
[INFO] Successfully saved ZIP package at C:\mypath\test-functions\target\azure-functions\test-functions-20180712090403798.zip
[ERROR] Application setting 'AzureWebJobsStorage' not found.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

**Comment by jdneo** [comment]
@pragnagopa 

I see an error goes: `[ERROR] Application setting 'AzureWebJobsStorage' not found.`

Could you please check the Application settings of the Function App that `AzureWebJobsStorage` is not empty?

you can find this in Azure Portal:
![image](https://user-images.githubusercontent.com/6193897/42669608-ead98670-8688-11e8-9a48-62667006a53d.png)

**Comment by pragnagopa** [comment]
FunctionApp is not deployed/created in azure because resource group name provided is not unique. Archetype needs to be updated to append a GUID similar to what it does for function app name. Also, if possible, plugin needs to show detailed error logs for deployment errors

**Comment by jdneo** [comment]
@pragnagopa I tried to deploy multiple Function Apps into the same resource group but cannot repro this issue. Is there any other configurations I need to take care?

**Comment by ruyakubu** [comment]
@pragnagopa How was the following issue fixed? https://github.com/Azure/azure-functions-java-worker/issues/140

- If the user chooses/leaves the default **"Java-functions-group"** resource group open each time they create an Azure Function, will their function continue to freeze when deployed to Azure?

<img width="844" alt="functions-resource-group" src="https://user-images.githubusercontent.com/11497088/43960317-9fc1f87c-9c7f-11e8-8afb-b9156ce3f40d.png">

**Comment by pragnagopa** [comment]
@ruyakubu - Right. This is not an issue on the worker. This needs to be fixed in the maven plugin. 
@jdneo is unable to repro the issue. Any more details on how to consistently repro will help him fix this issue in maven plugin
