### ISSUE TITLE
Default connection to "AzureWebJobsStorage"

### ISSUE THREAD

**Issue by mjiderhamn** [Microsoft/azure-maven-plugins#269]
### Plugin name and version
`azure-functions-maven-plugin` 1.0.0-beta-2

### Expected behavior
`com.microsoft.azure.functions.annotation.*Trigger.connection` has a default value of empty string. Documentation (albeit for C#) says "If you leave `connection` empty, the Functions runtime uses the default Storage connection string in the app setting that is named `AzureWebJobsStorage`."

### Actual behavior
If `connection` annotation attribute is not provided, the following error occurs when executing `azure-functions:package`:
```
[ERROR] Failed to execute goal com.microsoft.azure:azure-functions-maven-plugin:1.0.0-beta-2:package (package-functions) on project serverless-azure: Storage binding (blob/queue/table) must have non-empty connection. Invalid storage binding found on method: se.jiderhamn.serverless.azure.AzureFunction.transformBlob -> [Help 1]
```

**Comment by jdneo** [comment]
@mjiderhamn Apologize for the late reply for this issue.

@pragnagopa Personally I think it's fine to add a default value for the storage connection string. What do you think?

**Comment by jdneo** [comment]
Close it for now and tracking in: https://github.com/Azure/azure-functions-java-library/issues/43.
