### ISSUE TITLE
Sometimes, an error occured when trying to create a controller of type 'DeploymentController'

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-maven-plugins#278]
### Plugin name and version
Maven Plugin for Azure Functions: 1.0.0-beta-3
### Plugin configuration in your `pom.xml`
```
          <plugin>
                <groupId>com.microsoft.azure</groupId>
                <artifactId>azure-functions-maven-plugin</artifactId>
                <configuration>
                    <resourceGroup>${functionResourceGroup}</resourceGroup>
                    <appName>${functionAppName}</appName>
                    <region>${functionAppRegion}</region>
                    <appSettings>
                        <property>
                            <name>FUNCTIONS_EXTENSION_VERSION</name>
                            <value>beta</value>
                        </property>
                    </appSettings>
                </configuration>
                <executions>
                    <execution>
                        <id>package-functions</id>
                        <goals>
                            <goal>package</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```
### Expected behavior
Can deploy successfully.
### Actual behavior
![image](https://user-images.githubusercontent.com/22470312/43133815-81ce00a0-8f72-11e8-80a1-3dd6ee9fb8b9.png)

### Steps to reproduce the problem
1. Create a queue trigger
2. mvn clean package
3. mvn azure-functions:deploy

**Comment by bsaby** [comment]
I can deploy successfully at the second time.

**Comment by jdneo** [comment]
This is a problem of the MS Deploy.

We will use ZipDeploy in the future.

Tracking: #294

**Comment by jdneo** [comment]
In 1.0.0-beta-5 we have supported the zip deploy as the default deployment type. This issue can be addressed by using the zip deploy.
