### ISSUE TITLE
Adjust POM.xml to not include container registry name

### ISSUE THREAD

**Issue by selvasingh** [Microsoft/azure-maven-plugins#28]
https://github.com/Microsoft/gs-spring-boot-docker/blob/private-registry/complete/pom.xml - line 21

To run this sample project, users must change the registry name in line 21. Please modify this to a environment variable. So, users can use without changing POM and do not accidentally check POM changes into their forked version of this sample

**Comment by jdneo** [comment]
@selvasingh @xscript I'm closing this issue since it is not related with maven plugin.
