### ISSUE TITLE
Maven Azure Functions plugin 1.0.0-beta-4 Endgame

### ISSUE THREAD

**Issue by jdneo** [Microsoft/azure-maven-plugins#283]
| Status | Task | Due |
|---|---|---|
✔️   | Publish new plugin & archetype into sonatype staging repo | 7/26
✔️  | Verification | TBD
✔️ | Release to Maven Central | TBD
✔️ | Merge develop to master | TBD
✔️ | Add tag and release notes | TBD
✔️ | Update version for next release | TBD

**Comment by jdneo** [comment]
@pragnagopa FYI

**Comment by pragnagopa** [comment]
👍 will update this issue as the release progresses

**Comment by jdneo** [comment]
@pragnagopa new staging repo url: https://oss.sonatype.org/content/repositories/commicrosoftazure-2491/
