### ISSUE TITLE
Generating from archetype fails to populate plugin properties.

### ISSUE THREAD

**Issue by rloutlaw** [Microsoft/azure-maven-plugins#285]
### Plugin name and version

1.11 and 1.12 Maven releases from maven central. Java 8 and Maven 3.5.4.

### Plugin configuration in your `pom.xml`

Relevant failing part:

   <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <azure.functions.maven.plugin.version>1.0.0-beta-3</azure.functions.maven.plugin.version>
        <azure.functions.java.library.version>1.0.0-beta-4</azure.functions.java.library.version>
        <functionAppName>helloworld-${package.getClass().forName("java.time.LocalDateTime").getMethod("now").invoke(null).format($package.Class.forName("java.time.format.DateTimeFormatter").getMethod("ofPattern", $package.Class).invoke(null, "yyyyMMddHHmmssSSS"))}</functionAppName>
        <functionAppRegion>${package.getClass().forName("java.lang.StringBuilder").getConstructor($package.getClass().forName("java.lang.String")).newInstance("westus").toString()}</functionAppRegion>
        <stagingDirectory>${project.build.directory}/azure-functions/${functionAppName}</stagingDirectory>
        <functionResourceGroup>${package.getClass().forName("java.lang.StringBuilder").getConstructor($package.getClass().forName("java.lang.String")).newInstance("java-functions-group").toString()}</functionResourceGroup>
    </properties>

### Expected behavior

The functionAppName, AppRegion, and other fields have proper variable interpolation.

### Actual behavior

Fields aren't generated / interpolated properly.

### Steps to reproduce the problem

Generate a new project from archtype from Windows command line, Eclipse, or IntellliJ.

**Comment by jdneo** [comment]
@rloutlaw Thanks for reporting. I move this issue to: https://github.com/Microsoft/azure-maven-archetypes/issues/42
