### ISSUE TITLE
When deploy cosmos db trigger to azure, it can't be triggered if the deploymentType set to "msdeploy" or "ftp"

### ISSUE THREAD

**Issue by JanusWu** [Microsoft/azure-maven-plugins#329]
### Plugin name and version
Maven Plugin for Azure Functions: 1.0.0-beta-5-SNAPSHOT
 ```
<azure.functions.maven.plugin.version>1.0.0-beta-5-SNAPSHOT</azure.functions.maven.plugin.version>
<azure.functions.java.library.version>1.0.0-beta-5</azure.functions.java.library.version>
```

### Plugin configuration in your `pom.xml`
```
            <plugin>
                <groupId>com.microsoft.azure</groupId>
                <artifactId>azure-functions-maven-plugin</artifactId>
                <configuration>
                    <resourceGroup>${functionResourceGroup}</resourceGroup>
                    <appName>${functionAppName}</appName>
                    <region>${functionAppRegion}</region>
                    <deploymentType>ftp</deploymentType> //or msdeploy
                    <appSettings>
                        <property>
                            <name>FUNCTIONS_EXTENSION_VERSION</name>
                            <value>beta</value>
                        </property>
                        <property>
                            <name>connection</name>
                            <value>xxx</value>
                        </property>
                    </appSettings>
                </configuration>
                <executions>
                    <execution>
                        <id>package-functions</id>
                        <goals>
                            <goal>package</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

### Expected behavior
The function can be triggered successfully on azure, not matter the deploymentType is "zip", "msdeploy" or "ftp"

### Actual behavior
After add a document in collection, 
if the deploymentType  is "zip", which is default, the function can be triggered,
if  the deploymentType is "msdeploy" or "ftp", the function has no response.

### Steps to reproduce the problem

connection : connection
databaseName : db
collectionName : col
leaseCollectionName : leasecol
createLeaseCollectionIfNotExists : true

1. Create a Cosmos DB in azure and create a datebase and a collection according to above configuration
2. Generate a Cosmos DB Trigger according to above configuration
3. In the POM file, update `azure.functions.maven.plugin.version` to `1.0.0-beta-5-SNAPSHOT`
4. In the POM file, update `azure-functions-maven-plugin` configuration  as above
5. Run `mvn clean package` under the root folder which contains the POM file
6. Run `mvn azure-functions:deploy` under the root folder
6. Add a document to collection `col` to see if the function get triggered.

**Comment by SummerSun** [comment]
@JanusWu Please verify your pom.xml is valid. There is no version for <artifactId>azure-functions-maven-plugin</artifactId>.

**Comment by JanusWu** [comment]
Added the azure-functions-maven-plugin version under `Plugin name and version`.

**Comment by jdneo** [comment]
In 1.0.0-beta-5 we have supported the zip deploy as the default deployment type. This issue can be addressed by using the zip deploy.
