### ISSUE TITLE
extensions.csproj file and obj directory are generated by the Maven Plugin for Azure functions

### ISSUE THREAD

**Issue by jdneo** [Microsoft/azure-maven-plugins#338]
_By @selvasingh_ :

There are two issues with this approach:

1)	It pollutes developers’ workspaces. They unnecessarily show up in Git status. They may be accidentally checked into source control.

Workaround – update .gitignore

2)	It interferes with the Maven work flow. $ mvn clean – deletes everything in the target folder but extensions.csproj file and obj directory are left behind. When the function code is changed and re-packaged using Maven, these artifacts are not changed. If you were to deploy this function app to Azure, it would become a bad deployment and you would see all kinds of startup errors.

Workaround – if we were to manually drop these artifacts, they would be regenerated and then everything is cool.

Per the Standard Maven Directory Layout, the target directory is used to house all output of a build.

**Comment by pragnagopa** [comment]
Notes from @selvasingh 
Temporarily, I overrode the “$ mvn clean cycle” to blow away the “obj” directory. But, our customers will not know that. Here is how – add another plugin statement to POM.xml –

```
<plugin>
    <artifactId>maven-clean-plugin</artifactId>
    <version>3.1.0</version>
    <configuration>
        <filesets>
            <fileset>
                <directory>obj</directory>
            </fileset>
        </filesets>
    </configuration>
</plugin>

```

**Comment by jdneo** [comment]
@pragnagopa @selvasingh 

So I think we have achieved the conclusion that the `obj/` and `extensions.csproj` should be regenerated for each local build right?

If that is true, I think there are at least two solutions here:
1. leverage the `maven-clean-plugin` as @selvasingh mentioned.
2. put those files in the target folder rather than in the project base path.

Personally, I prefer the second one.

**Comment by pragnagopa** [comment]
Obj folder is not needed. That needs to be cleaned up. Extensions.csproj should move to target folde

**Comment by pragnagopa** [comment]
@jdneo - Correction, extensions.csproj does not have to be deployed. It is part of the source code.

**Comment by jdneo** [comment]
@pragnagopa 

Does that mean we will not clean the `extensions.csproj`? I think what the @selvasingh says is that the package goal will not install the latest extensions.

**Comment by selvasingh** [comment]
@jdneo - any update on this issue?

`maven-clean-plugin` is a TEMPORARY FIX

**Comment by jdneo** [comment]
I think we can put the `obj/` and `extensions.csproj` into the target folder, then each time user triggers `mvn clean` will remove them. For what @pragnagopa concerns, I think we can add some simple logic in the deploy mojo to exclude these files during the deployment. 

@pragnagopa @selvasingh @brunoborges any thoughts?

**Comment by brunoborges** [comment]
target folder is ideal for generated files that are not required to be kept in the source control system (e.g. git)

**Comment by pragnagopa** [comment]
Apologies for going back and forth on where to put extensions.csproj
To address this issue:
- Delete obj folder
- Copy extensions.csproj to  target\azure-functions\<your function app name>
  - We still need extensions.csproj at the src level to restore packages when running locally
  - We need extensions.csproj in the targer folder to be included when deployed, to restore packages if ever needed from portal

**Comment by brunoborges** [comment]
It will be confusing to developers having a generated file in `src`.

Doesn't the Maven plugin uses what is inside `target` to run locally?

**Comment by pragnagopa** [comment]
Technically extensions.csproj is part of src and needs to be part of source control. If users have an app working with a set of extensions packages, this needs to be preserved.
If extensions.csproj is only in target folder, it gets cleaned up and mvn clean package will always pull the latest extensions.

**Comment by brunoborges** [comment]
Is `extensions.csproj` something that users can write manually? Or is it something that is always generated every time the Maven plugin is triggered during build?

If it is always generated when the project is built with `clean package`, then the Maven plugin should be configurable to allow sticking to a set of extensions/versions.

We need to be clear on whether this is a once-only generated file, or something that is generated eventually, or always - during `package`.

**Comment by jdneo** [comment]
@brunoborges `extensions.csproj` is once-only generated file. It will be generated (by function cli) if it does not exist. After that, the function cli will consume it and install the extensions which are specified in the `extensions.csproj`.

@pragnagopa I'm interested in what will happen if we deployed  the `extensions.csproj` onto the cloud. Could you explain more about `to restore packages if ever needed from portal`?

**Comment by soninaren** [comment]
@jdneo, It depends how you deploy to the cloud, Certain methods of deployments would build extensions.csproj and others would leave it as is, It should be fine if extensions.csproj is  gets built as a part of deployment.

**Comment by jdneo** [comment]
Update:

Per the service team, they are considering to remove the .NET Core SDK dependency for extension installation. So we have nothing to do right now.

**Comment by pragnagopa** [comment]
@jdneo - Sorry for the confusion. Removing .Net Core SDK dependency is a long term fix. We do no have ETA for this yet. Please go ahead with the changes you suggested.

**Comment by jdneo** [comment]
Ok, so here is the actions we need to take:

- Store extensions.csproj & obj/ in source folder
- Add obj/ into .gitignore ([It's already there](https://github.com/Microsoft/azure-maven-archetypes/blob/master/azure-functions-archetype/src/main/resources/archetype-resources/.gitignore#L35))
- Remove the obj/ when the user triggers 'mvn clean'

**Comment by Flanker32** [comment]
Solved in https://github.com/Microsoft/azure-maven-archetypes/pull/73 and close it.
