### ISSUE TITLE
Get socket timeout exception when deploy artifacts to the web app immediately after the web app is created

### ISSUE THREAD

**Issue by jdneo** [microsoft/azure-maven-plugins#339]
When the plugin deploys the artifact to the web app immediately after the web app is created. It will get socket timeout exception. This is due to the problem that for a newly created Web App, its kudu endpoint still needs several more seconds to ready.

So currently our workaround is to add some retry logic into the code to make sure the deployment can success finally.

**Comment by selvasingh** [comment]
@jdneo - retry logic is working but the console statement is misleading when the Maven surfaces the socket timeout. Possible to absorb the timeout message?

FYI @shrishrirang

**Comment by jdneo** [comment]
We’ve swallowed the exceptions during the retry logic. See codes here: https://github.com/Microsoft/azure-maven-plugins/blob/develop/azure-maven-plugin-lib/src/main/java/com/microsoft/azure/maven/artifacthandler/ZIPArtifactHandlerImpl.java#L61-L64

Guessing this log is printed by the Azure SDK.

Also + @jianghaolu for awareness.

**Comment by shrishrirang** [comment]
@jdneo: Do you know if anyone is working on the timeout message?

**Comment by jdneo** [comment]
@shrishrirang, SDK team should be aware of this issue. But I'm not quite sure about current state of this issue.

**Comment by shrishrirang** [comment]
Wondering if you can check if this is on their radar and by when the SDK team plans to fix this. Is there a corresponding GitHub issue created for the SDK team? This bug is pretty bad and has been there for a long time now. Would be good to follow-up with the right folks.

**Comment by SummerSun** [comment]
@shrishrirang As I could remember this timeout message might not be printed by SDK side. @jianghaolu  Could you please help confirm this?  (I am trying to find a snapshot for the issue.)

**Comment by jianghaolu** [comment]
This is due to a log statement in HTTP logging regardless of the log level setting: https://github.com/Azure/autorest-clientruntime-for-java/blob/master/client-runtime/src/main/java/com/microsoft/rest/interceptors/LoggingInterceptor.java#L118

A bug opened: https://github.com/Azure/autorest-clientruntime-for-java/issues/512

**Comment by Flanker32** [comment]
Fixed in https://github.com/Azure/autorest-clientruntime-for-java/issues/512
