### ISSUE TITLE
Maven command will be hanged on MacOS

### ISSUE THREAD

**Issue by jdneo** [Microsoft/azure-maven-plugins#341]
Platform Information
Operation System: MacOS 10.13.5
Java Version: Java version: 1.8.0_162, vendor: Oracle Corporation
Maven Version: 3.5.0
AI-Core Version: 2.1.2

> Note: This issue seems cannot be reproduced on Windows, but can be stable repro on Mac

Seems the AI will send the telemetry asynchronously. So when the maven goal finished, maven dispose its classloader, but the AI is still doing some tasks. Then NoClassDefFoundError happens. Besides the process will be hanged.

This issue is also tracked by: https://github.com/Microsoft/ApplicationInsights-Java/issues/416

**Comment by Flanker32** [comment]
Fixed in #576
