### ISSUE TITLE
Site could not run correctly when deploy jar to Java SE web app 

### ISSUE THREAD

**Issue by SummerSun** [microsoft/azure-maven-plugins#345]
It is quite often that users deploy a jar file to Java SE web app and the site just could not run it.
It turns out the jar file has to be named as app.jar for it to take effect.

Currently, users could get the information only from the website home page they provisioned. It could be very useful if service or SDK side could provide a separate document that delivers this important information. Or, furthermore, support users to config the entry point and set any name of the jar file as they want.

From tooling side, we could add a warning or information message when a jar file is deploying to a web app and its name is not app.jar.To avoid it become annoying for users who just want to deploy a dependency jar file to the web app, we could prompt the warning message with the setting and support users to turn it off.

**Comment by Flanker32** [comment]
Fixed in V1.6.0, now maven plugin will rename the artifact and show info message when deploying to Java SE runtime.
