### ISSUE TITLE
ROOT\WEB-INF\classes\com] could not be completely deleted.

### ISSUE THREAD

**Issue by cfmDeveloper** [Microsoft/azure-maven-plugins#36]
### Plugin name and version
azure-webapp-maven-plugin 1.0.3
### Plugin configuration in your `pom.xml`
FTP -> azure webapp
### Expected behavior
Undeploy the existing ROOT dir on server
Deploy WAR file
Be happy 
### Actual behavior
Server is not completing undeploy of ROOT due to locked class files:
D:\home\site\wwwroot\webapps\ROOT] could not be completely deleted. The presence of the remaining files may cause problems
### Steps to reproduce the problem
This does not happen every time the project is deployed.  Generally, rebuilding the project will get it to deploy correctly and complete the undeploy of ROOT from server before deploying the new ROOT.war

**Comment by xscript** [comment]
@cfmDeveloper  I tried to reproduce from my side, but unfortunately couldn't. I will give another try.
Two questions to confirm:
- The WAR file is successfully uploaded to web app via FTP, right?
- by **_rebuilding the project_**, do you mean repackage the Maven project? Or something else?

**Comment by cfmDeveloper** [comment]
the problem lies in the webapp deploying the war file after it is uploaded.  is there a method to send out a stop call before pushing the war file?  Because the webapp isn't stopping it occasionally will have a few class files locked during "undeployment" if Tomcat isn't shutdown first.

**Comment by xscript** [comment]
@cfmDeveloper Thanks for the follow-up explanation! That's what I suspected. Right now in web app Maven plugin, it is not supported to stop the target web app before deployment. I've added #37 to add this functionality. Feel free to comment under #37 if you have any suggestions.
Thanks very much!

**Comment by xscript** [comment]
@cfmDeveloper Now you can use configuration element `<stopAppDuringDeployment>` like [here](https://github.com/Microsoft/azure-maven-plugins/blob/master/azure-webapp-maven-plugin/src/it/windows-ftp/pom.xml#L27) with latest version `0.1.5`. Thanks!
