### ISSUE TITLE
Use Maven to publish to an existing app in Azure

### ISSUE THREAD

**Issue by asavaritayal** [microsoft/azure-maven-plugins#365]
The [Java Functions quick start](https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-java-maven) explains how to create and publish a net new app in Azure. 

Can you explain how users can leverage maven to publish to an existing app in Azure? 

/cc @mattchenderson @pragnagopa

**Comment by jdneo** [comment]
The Maven plugin will only create a new app if the configured app does not exist on Azure. If the specified App does exist, the plugin will deploy the artifact to the existing one.

**Comment by jdneo** [comment]
Closing since the thread is inactive for a long time.

**Comment by pragnagopa** [comment]
We should atleast track this issue as documentation as there is no clear instructions on how to update pom.xml if user created an app on Azure portal
