### ISSUE TITLE
Mvn package error

### ISSUE THREAD

**Issue by asavaritayal** [Microsoft/azure-maven-plugins#366]
`mvn package` for Azure Functions archetype throws the following error - 

Execution package-functions of goal com.microsoft.azure:azure-functions-maven-plugin:1.0.0-beta-5:package failed: A required class was missing while executing com.microsoft.azure:azure-functions-maven-plugin:1.0.0-beta-5:package: javax/xml/bind/JAXBException
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.microsoft.azure:azure-functions-maven-plugin:1.0.0-beta-5
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/Users/asavaritayal/.m2/repository/com/microsoft/azure/azure-functions-maven-plugin/1.0.0-beta-5/azure-functions-maven-plugin-1.0.0-beta-5.jar
[ERROR] urls[1] = file:/Users/asavaritayal/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
[ERROR] urls[2] = file:/Users/asavaritayal/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.0/org.eclipse.sisu.inject-0.3.0.jar
[ERROR] urls[3] = file:/Users/asavaritayal/.m2/repository/org/apache/maven/maven-builder-support/3.3.3/maven-builder-support-3.3.3.jar
[ERROR] urls[4] = file:/Users/asavaritayal/.m2/repository/org/eclipse/aether/aether-util/1.0.2.v20150114/aether-util-1.0.2.v20150114.jar
[ERROR] urls[5] = file:/Users/asavaritayal/.m2/repository/org/sonatype/sisu/sisu-guice/3.2.5/sisu-guice-3.2.5-no_aop.jar
[ERROR] urls[6] = file:/Users/asavaritayal/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
[ERROR] urls[7] = file:/Users/asavaritayal/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.21/plexus-interpolation-1.21.jar
[ERROR] urls[8] = file:/Users/asavaritayal/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[9] = file:/Users/asavaritayal/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[10] = file:/Users/asavaritayal/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[11] = file:/Users/asavaritayal/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.20/plexus-utils-3.0.20.jar
[ERROR] urls[12] = file:/Users/asavaritayal/.m2/repository/com/microsoft/azure/azure-maven-plugin-lib/1.1.0/azure-maven-plugin-lib-1.1.0.jar
[ERROR] urls[13] = file:/Users/asavaritayal/.m2/repository/org/apache/maven/shared/maven-filtering/3.0.0/maven-filtering-3.0.0.jar
[ERROR] urls[14] = file:/Users/asavaritayal/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.0.0/maven-shared-utils-3.0.0.jar
[ERROR] urls[15] = file:/Users/asavaritayal/.m2/repository/com/google/code/findbugs/jsr305/2.0.1/jsr305-2.0.1.jar
[ERROR] urls[16] = file:/Users/asavaritayal/.m2/repository/org/sonatype/plexus/plexus-build-api/0.0.7/plexus-build-api-0.0.7.jar
[ERROR] urls[17] = file:/Users/asavaritayal/.m2/repository/com/microsoft/azure/azure/1.14.0/azure-1.14.0.jar
[ERROR] urls[18] = file:/Users/asavaritayal/.m2/repository/com/microsoft/azure/azure-client-runtime/1.6.0/azure-client-runtime-1.6.0.jar
[ERROR] urls[19] = file:/Users/asavaritayal/.m2/repository/com/microsoft/rest/client-runtime/1.6.0/client-runtime-1.6.0.jar
[ERROR] urls[20] = file:/Users/asavaritayal/.m2/repository/com/squareup/retrofit2/retrofit/2.4.0/retrofit-2.4.0.jar
[ERROR] urls[21] = file:/Users/asavaritayal/.m2/repository/com/squareup/okhttp3/okhttp/3.11.0/okhttp-3.11.0.jar
[ERROR] urls[22] = file:/Users/asavaritayal/.m2/repository/com/squareup/okio/okio/1.14.0/okio-1.14.0.jar
[ERROR] urls[23] = file:/Users/asavaritayal/.m2/repository/com/squareup/okhttp3/logging-interceptor/3.11.0/logging-interceptor-3.11.0.jar
[ERROR] urls[24] = file:/Users/asavaritayal/.m2/repository/com/squareup/okhttp3/okhttp-urlconnection/3.11.0/okhttp-urlconnection-3.11.0.jar
[ERROR] urls[25] = file:/Users/asavaritayal/.m2/repository/com/squareup/retrofit2/converter-jackson/2.4.0/converter-jackson-2.4.0.jar
[ERROR] urls[26] = file:/Users/asavaritayal/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.9.4/jackson-databind-2.9.4.jar
[ERROR] urls[27] = file:/Users/asavaritayal/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-joda/2.9.4/jackson-datatype-joda-2.9.4.jar
[ERROR] urls[28] = file:/Users/asavaritayal/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.9.0/jackson-annotations-2.9.0.jar
[ERROR] urls[29] = file:/Users/asavaritayal/.m2/repository/com/squareup/retrofit2/adapter-rxjava/2.4.0/adapter-rxjava-2.4.0.jar
[ERROR] urls[30] = file:/Users/asavaritayal/.m2/repository/com/microsoft/azure/azure-client-authentication/1.6.0/azure-client-authentication-1.6.0.jar
[ERROR] urls[31] = file:/Users/asavaritayal/.m2/repository/com/microsoft/azure/adal4j/1.1.2/adal4j-1.1.2.jar
[ERROR] urls[32] = file:/Users/asavaritayal/.m2/repository/com/nimbusds/oauth2-oidc-sdk/4.5/oauth2-oidc-sdk-4.5.jar
[ERROR] urls[33] = file:/Users/asavaritayal/.m2/repository/javax/mail/mail/1.4.7/mail-1.4.7.jar
[ERROR] urls[34] = file:/Users/asavaritayal/.m2/repository/javax/activation/activation/1.1/activation-1.1.jar
[ERROR] urls[35] = file:/Users/asavaritayal/.m2/repository/net/jcip/jcip-annotations/1.0/jcip-annotations-1.0.jar
[ERROR] urls[36] = file:/Users/asavaritayal/.m2/repository/net/minidev/json-smart/1.1.1/json-smart-1.1.1.jar
[ERROR] urls[37] = file:/Users/asavaritayal/.m2/repository/com/nimbusds/lang-tag/1.4/lang-tag-1.4.jar
[ERROR] urls[38] = file:/Users/asavaritayal/.m2/repository/com/nimbusds/nimbus-jose-jwt/3.1.2/nimbus-jose-jwt-3.1.2.jar
[ERROR] urls[39] = file:/Users/asavaritayal/.m2/repository/org/bouncycastle/bcprov-jdk15on/1.51/bcprov-jdk15on-1.51.jar
[ERROR] urls[40] = file:/Users/asavaritayal/.m2/repository/com/microsoft/azure/azure-annotations/1.2.0/azure-annotations-1.2.0.jar
[ERROR] urls[41] = file:/Users/asavaritayal/.m2/repository/com/microsoft/azure/azure-mgmt-resources/1.14.0/azure-mgmt-resources-1.14.0.jar
[ERROR] urls[42] = file:/Users/asavaritayal/.m2/repository/org/slf4j/slf4j-simple/1.7.5/slf4j-simple-1.7.5.jar
[ERROR] urls[43] = file:/Users/asavaritayal/.m2/repository/io/reactivex/rxjava/1.3.8/rxjava-1.3.8.jar
[ERROR] urls[44] = file:/Users/asavaritayal/.m2/repository/org/apache/httpcomponents/httpcore/4.4.5/httpcore-4.4.5.jar
[ERROR] urls[45] = file:/Users/asavaritayal/.m2/repository/com/microsoft/azure/azure-mgmt-storage/1.14.0/azure-mgmt-storage-1.14.0.jar
[ERROR] urls[46] = file:/Users/asavaritayal/.m2/repository/com/microsoft/azure/azure-mgmt-network/1.14.0/azure-mgmt-network-1.14.0.jar
[ERROR] urls[47] = file:/Users/asavaritayal/.m2/repository/com/microsoft/azure/azure-mgmt-compute/1.14.0/azure-mgmt-compute-1.14.0.jar
[ERROR] urls[48] = file:/Users/asavaritayal/.m2/repository/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
[ERROR] urls[49] = file:/Users/asavaritayal/.m2/repository/com/microsoft/azure/azure-mgmt-graph-rbac/1.14.0/azure-mgmt-graph-rbac-1.14.0.jar
[ERROR] urls[50] = file:/Users/asavaritayal/.m2/repository/com/microsoft/azure/azure-mgmt-keyvault/1.14.0/azure-mgmt-keyvault-1.14.0.jar
[ERROR] urls[51] = file:/Users/asavaritayal/.m2/repository/com/microsoft/azure/azure-keyvault/1.0.0/azure-keyvault-1.0.0.jar
[ERROR] urls[52] = file:/Users/asavaritayal/.m2/repository/com/microsoft/azure/azure-keyvault-webkey/1.0.0/azure-keyvault-webkey-1.0.0.jar
[ERROR] urls[53] = file:/Users/asavaritayal/.m2/repository/com/microsoft/azure/azure-mgmt-batch/1.14.0/azure-mgmt-batch-1.14.0.jar
[ERROR] urls[54] = file:/Users/asavaritayal/.m2/repository/com/microsoft/azure/azure-mgmt-trafficmanager/1.14.0/azure-mgmt-trafficmanager-1.14.0.jar
[ERROR] urls[55] = file:/Users/asavaritayal/.m2/repository/com/microsoft/azure/azure-mgmt-dns/1.14.0/azure-mgmt-dns-1.14.0.jar
[ERROR] urls[56] = file:/Users/asavaritayal/.m2/repository/com/microsoft/azure/azure-mgmt-redis/1.14.0/azure-mgmt-redis-1.14.0.jar
[ERROR] urls[57] = file:/Users/asavaritayal/.m2/repository/com/microsoft/azure/azure-mgmt-appservice/1.14.0/azure-mgmt-appservice-1.14.0.jar
[ERROR] urls[58] = file:/Users/asavaritayal/.m2/repository/com/microsoft/azure/azure-storage/6.1.0/azure-storage-6.1.0.jar
[ERROR] urls[59] = file:/Users/asavaritayal/.m2/repository/com/microsoft/azure/azure-keyvault-core/0.8.0/azure-keyvault-core-0.8.0.jar
[ERROR] urls[60] = file:/Users/asavaritayal/.m2/repository/com/microsoft/azure/azure-mgmt-locks/1.14.0/azure-mgmt-locks-1.14.0.jar
[ERROR] urls[61] = file:/Users/asavaritayal/.m2/repository/com/microsoft/azure/azure-mgmt-eventhub/1.14.0/azure-mgmt-eventhub-1.14.0.jar
[ERROR] urls[62] = file:/Users/asavaritayal/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.9.4/jackson-core-2.9.4.jar
[ERROR] urls[63] = file:/Users/asavaritayal/.m2/repository/com/microsoft/azure/azure-mgmt-cdn/1.14.0/azure-mgmt-cdn-1.14.0.jar
[ERROR] urls[64] = file:/Users/asavaritayal/.m2/repository/com/microsoft/azure/azure-mgmt-sql/1.14.0/azure-mgmt-sql-1.14.0.jar
[ERROR] urls[65] = file:/Users/asavaritayal/.m2/repository/com/microsoft/azure/azure-mgmt-containerinstance/1.14.0/azure-mgmt-containerinstance-1.14.0.jar
[ERROR] urls[66] = file:/Users/asavaritayal/.m2/repository/com/microsoft/azure/azure-mgmt-containerregistry/1.14.0/azure-mgmt-containerregistry-1.14.0.jar
[ERROR] urls[67] = file:/Users/asavaritayal/.m2/repository/com/microsoft/azure/azure-mgmt-containerservice/1.14.0/azure-mgmt-containerservice-1.14.0.jar
[ERROR] urls[68] = file:/Users/asavaritayal/.m2/repository/com/microsoft/azure/azure-mgmt-cosmosdb/1.14.0/azure-mgmt-cosmosdb-1.14.0.jar
[ERROR] urls[69] = file:/Users/asavaritayal/.m2/repository/com/microsoft/azure/azure-mgmt-search/1.14.0/azure-mgmt-search-1.14.0.jar
[ERROR] urls[70] = file:/Users/asavaritayal/.m2/repository/com/microsoft/azure/azure-mgmt-msi/1.14.0/azure-mgmt-msi-1.14.0.jar
[ERROR] urls[71] = file:/Users/asavaritayal/.m2/repository/com/microsoft/azure/azure-mgmt-monitor/1.14.0/azure-mgmt-monitor-1.14.0.jar
[ERROR] urls[72] = file:/Users/asavaritayal/.m2/repository/com/microsoft/azure/azure-mgmt-servicebus/1.14.0/azure-mgmt-servicebus-1.14.0.jar
[ERROR] urls[73] = file:/Users/asavaritayal/.m2/repository/joda-time/joda-time/2.1/joda-time-2.1.jar
[ERROR] urls[74] = file:/Users/asavaritayal/.m2/repository/com/microsoft/azure/azure-mgmt-batchai/1.14.0/azure-mgmt-batchai-1.14.0.jar
[ERROR] urls[75] = file:/Users/asavaritayal/.m2/repository/com/microsoft/azure/applicationinsights-core/1.0.9/applicationinsights-core-1.0.9.jar
[ERROR] urls[76] = file:/Users/asavaritayal/.m2/repository/eu/infomas/annotation-detector/3.0.4/annotation-detector-3.0.4.jar
[ERROR] urls[77] = file:/Users/asavaritayal/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar
[ERROR] urls[78] = file:/Users/asavaritayal/.m2/repository/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar
[ERROR] urls[79] = file:/Users/asavaritayal/.m2/repository/org/apache/httpcomponents/httpclient/4.5.3/httpclient-4.5.3.jar
[ERROR] urls[80] = file:/Users/asavaritayal/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
[ERROR] urls[81] = file:/Users/asavaritayal/.m2/repository/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
[ERROR] urls[82] = file:/Users/asavaritayal/.m2/repository/commons-net/commons-net/3.6/commons-net-3.6.jar
[ERROR] urls[83] = file:/Users/asavaritayal/.m2/repository/org/zeroturnaround/zt-zip/1.13/zt-zip-1.13.jar
[ERROR] urls[84] = file:/Users/asavaritayal/.m2/repository/com/microsoft/azure/functions/azure-functions-java-library/1.0.0-beta-5/azure-functions-java-library-1.0.0-beta-5.jar
[ERROR] urls[85] = file:/Users/asavaritayal/.m2/repository/org/reflections/reflections/0.9.11/reflections-0.9.11.jar
[ERROR] urls[86] = file:/Users/asavaritayal/.m2/repository/com/google/guava/guava/20.0/guava-20.0.jar
[ERROR] urls[87] = file:/Users/asavaritayal/.m2/repository/org/javassist/javassist/3.21.0-GA/javassist-3.21.0-GA.jar
[ERROR] urls[88] = file:/Users/asavaritayal/.m2/repository/com/github/zafarkhaja/java-semver/0.9.0/java-semver-0.9.0.jar
[ERROR] urls[89] = file:/Users/asavaritayal/.m2/repository/junit/junit/4.12/junit-4.12.jar
[ERROR] urls[90] = file:/Users/asavaritayal/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR]

**Comment by jdneo** [comment]
So I guess you are using java 9/10. If that is the case, then it is due to the issue that the Application Insights Java SDK do not support Java 9/10 so far.

See this duplicated issue: #162 

/cc @Flanker32
