### ISSUE TITLE
Lower case values generated in function.json

### ISSUE THREAD

**Issue by jdneo** [microsoft/azure-maven-plugins#386]
The original issue: https://github.com/Microsoft/azure-maven-archetypes/issues/63

_From @pragnagopa:_

Key-Value pairs in function.json need to be camelCased. 
Following is fields are inconsistent and when opened in VS show schema validation errors
```  
    "webHookType" : "NONE",
     "methods" : [ "GET", "POST" ]
```
see sample function.json here
https://github.com/Azure/azure-functions-templates/blob/dev/Functions.Templates/Templates/HttpTrigger-JavaScript/function.json

**Comment by Flanker32** [comment]
@pragnagopa  
Should we just convert the value of webHookType and method to lowercase, or convert all the key value pairs in function.json to camelCased? Is there any document about the validation schema?

**Comment by pragnagopa** [comment]
Here is the published json schema for function.json http://json.schemastore.org/function

**Comment by Flanker32** [comment]
All attributes in function configuration have been camelCased,  close this issue.
