### ISSUE TITLE
azure-functions-maven-plugin:1.0.0-beta-6:deploy is not working

### ISSUE THREAD

**Issue by milismsft** [Microsoft/azure-maven-plugins#390]
### Plugin name and version
azure-functions-maven-plugin:1.0.0-beta-6:deploy

### Plugin configuration in your `pom.xml`
        <dependency>
            <groupId>com.microsoft.azure.functions</groupId>
            <artifactId>azure-functions-java-library</artifactId>
            <version>1.0.0-beta-5</version>
        </dependency>
....
                <plugin>
                    <groupId>com.microsoft.azure</groupId>
                    <artifactId>azure-functions-maven-plugin</artifactId>
                    <version>1.0.0-beta-6</version>
                </plugin>
....
                    <appSettings>
                        <property>
                            <name>FUNCTIONS_EXTENSION_VERSION</name>
                            <value>2.0.12095.0</value>
                        </property>

### Expected behavior
Function successfully deployed and running

### Actual behavior
Function deployment takes significantly longer then when using 1.0.0-beta-4.
Function is only partially deployed (see the attached screenshots); when 1.0.0-beta-4 is deployed correctly so this is a regression.

### Steps to reproduce the problem
Build a simple Java function with a time trigger and an EventHub output. For actual code see (https://github.com/Microsoft/inventory-hub-java-on-azure/tree/master/function-apps/Point-Of-Transaction)
<img width="1655" alt="screen shot 2018-09-15 at 1 00 30 pm" src="https://user-images.githubusercontent.com/15163996/45590211-6880e000-b8e8-11e8-9c19-c4ef0d246ab0.png">
<img width="1284" alt="screen shot 2018-09-15 at 1 00 43 pm" src="https://user-images.githubusercontent.com/15163996/45590212-69197680-b8e8-11e8-91d9-6d3f3bd6bf22.png">

**Comment by Flanker32** [comment]
@milismsft
Thanks for your report, could you please offer more details infos to reproduce the problem? I tried to clone the Point-Of-Transaction project and deploy it by plugin beta6, it seems works well. Besides, we change the default deploy method to zip deploy, so infos printed in console may differs from beta4 to beta6.
![image](https://user-images.githubusercontent.com/12445236/45606145-2e911480-ba75-11e8-926e-6806bd2f8722.png)

**Comment by milismsft** [comment]
@Flanker32 can you please attach a screenshot of your console and the pom.xml settings you used? Might be good to setup a skype call and see if we can straight these things right.

**Comment by milismsft** [comment]
Ok, it seems to be working now by just changing the version of the plugin version in the pom.xml. The deployment takes a bit longer than when using beta-4 but it's definitely shorter than the 9 minutes.

**Comment by milismsft** [comment]
@Flanker32 The deployment failure when using beta-6 plugin repro'ed constantly last Saturday so I'm a bit puzzled at the moment what might have caused the failure (see the console screenshot I attached with 9 min deployment time). I'm running couple more tests over the day and if all goes well I'll close the issue.
