### ISSUE TITLE
Java Azure Function - root directory file host.json does not get deployed

### ISSUE THREAD

**Issue by milismsft** [Microsoft/azure-maven-plugins#391]
### Plugin name and version
                <plugin>
                    <groupId>com.microsoft.azure</groupId>
                    <artifactId>azure-functions-maven-plugin</artifactId>
                    <version>1.0.0-beta-4</version>
                </plugin>
### Expected behavior
changes to the host.json from the app's root directory are reflected in the Azure Function when deployed to the cloud.

**Comment by jdneo** [comment]
@milismsft Do you run `mvn clean package` before the deployment?

**Comment by milismsft** [comment]
@jdneo you're right, it does not repo after running the package command.
