### ISSUE TITLE
[Functions]Do not enforce minimum version requirement on the core tools

### ISSUE THREAD

**Issue by pragnagopa** [Microsoft/azure-maven-plugins#395]
### Plugin name and version
Funcitons
Moving notes from https://github.com/Azure/azure-functions-host/issues/3363#issuecomment-423281935
[INFO] Step 7 of 7: Installing function extensions if needed
[WARNING] Failed to get Azure Functions Core Tools version locally
[WARNING] Local Azure Functions Core Tools does not support extension auto-install, skip it in the package phase.
[WARNING] Local version of Azure Functions Core Tools (null) does not match the latest (2.0.2). Please update it for the best experience. See: https://aka.ms/azfunc-install
[INFO] Function extension installation done.
[INFO] Successfully built Azure Functions.
local.settings.json looks like this (after supposedly installing java extension)
{
"IsEncrypted": false,
"Values": {
"AzureWebJobsStorage": "",
"AzureWebJobsDashboard": "",
"FUNCTION_WORKER_RUNTIME": "java"
},
"ConnectionStrings": {}
}

**Comment by pragnagopa** [comment]
@turtlebeach - Moved the issue here
@jdneo  - Can you please take a look?

**Comment by pragnagopa** [comment]
cc: @soninaren
We found the root cause [func --version](https://github.com/Microsoft/azure-maven-plugins/blob/develop/azure-functions-maven-plugin/src/main/java/com/microsoft/azure/maven/function/handlers/FunctionCoreToolsHandlerImpl.java#L24) retruns 2.0.2.0 breaking the semver look up.

**Comment by pragnagopa** [comment]
Starting GA, do not enforce min version of core tools requirement. Only print warning if not using latest.

**Comment by soninaren** [comment]
fixed here https://github.com/Azure/azure-functions-core-tools/pull/739

**Comment by jdneo** [comment]
@pragnagopa Is there any action we need to take for the plugin side?

**Comment by pragnagopa** [comment]
No action needed right now. We released an update to core tools

**Comment by jdneo** [comment]
I see..

**Comment by jdneo** [comment]
@pragnagopa I guess this issue can be closed right?
