### ISSUE TITLE
[Functions] Delete WebHookType

### ISSUE THREAD

**Issue by pragnagopa** [Microsoft/azure-maven-plugins#402]
### Plugin name and version
Functions
WebHookType attribute is deleted. Not supported in V2 in Commit

https://github.com/Azure/azure-webjobs-sdk-extensions/commit/d7c8d3155947f642eacd9d493dc8a99d52622754#diff-2e1c91ba37984a71a1b391aaf7b471c1 

Delete from https://github.com/Microsoft/azure-maven-plugins/blob/8be22351e32cb0d14d102c7381b3c758b2362ed9/azure-functions-maven-plugin/src/main/java/com/microsoft/azure/maven/function/bindings/HttpBinding.java#L38

**Comment by pragnagopa** [comment]
@jdneo - please take a look

**Comment by jdneo** [comment]
Looks like only delete the related part in plugin will be fine, right?

**Comment by pragnagopa** [comment]
> Looks like only delete the related part in plugin will be fine, right?

Correct.

**Comment by Flanker32** [comment]
done in #406
