### ISSUE TITLE
[Functions] Show Queue Naming convention on add

### ISSUE THREAD

**Issue by pragnagopa** [Microsoft/azure-maven-plugins#403]
### Plugin name and version
Functions

### Steps to reproduce the problem
Queue name can only have lower case letters. Documentation on naming convention
https://docs.microsoft.com/en-us/rest/api/storageservices/naming-queues-and-metadata

It will be helpful to print a note "All letters in a queue name must be lowercase" on QueueTrigger azure-functions:add command

**Comment by pragnagopa** [comment]
Here is the message when user enters quename with  uppercase letters on the portal
```
Queue name must start and end with a letter or number, and it can contain only lowercase letters, numbers, and the hyphen. The name must be 3 to 63 characters.
```
cc: @brunoborges  - in case he has any input on the verbosity for maven plugin

**Comment by jdneo** [comment]
related with #405

**Comment by brunoborges** [comment]
LGTM

**Comment by Flanker32** [comment]
Added prompt infos and validation in pr #526
