### ISSUE TITLE
Leverage the metadata and give users more hints when calling azure-functions:add

### ISSUE THREAD

**Issue by pragnagopa** [Microsoft/azure-maven-plugins#405]
### Plugin name and version
Functions
Provide default values for adding trigger
Here is a sample output when adding QueueTrigger

```
[INFO] Selected function template: QueueTrigger
[INFO] Successfully found function template: QueueTrigger
[INFO]
[INFO] Step 3 of 4: Prepare required parameters
[INFO] Common parameter [Function Name]: name for both the new function and Java class
Enter value for Function Name: QueueTrigger1
[INFO] Common parameter [Package Name]: package name of the new Java class
Enter value for Package Name: com.test.pgopa
[INFO] Trigger specific parameter [connection]
Enter value for connection: AzureWebJobsStorage
[INFO] Trigger specific parameter [queueName]
Enter value for queueName: myqueue
```
### Expected behavior
Provide default values for all of them
[Function Name] QueueTrigger1
[Package Name] Default should be to use the same package name as the app
[connection] Default to AzureWebJobsStorage
[queueName] Default to myqueue-items

**Comment by pragnagopa** [comment]
@jdneo - If needed, please open separate issues for each trigger

**Comment by jdneo** [comment]
So we consume the templates metadata as we did in VS Code Azure Functions extension. This might be a big change for the `azure-functions:add` goal.

@Flanker32 Let's address the design first when you have time.

**Comment by Flanker32** [comment]
Added prompt infos and validation in pr #526
