### ISSUE TITLE
Maven Azure Functions plugin 1.0.0-beta-7 Endgame

### ISSUE THREAD

**Issue by Flanker32** [Microsoft/azure-maven-plugins#413]
| Status | Task | Due |
|---|---|---|
| ✔| Publish new plugin & archetype into sonatype staging repo | 10/10|
| ✔ | Verification | 10/11 |
| ✔ | Release to Maven Central | 10/12  |
| ✔ | Merge develop to master | 10/12  |
|✔ | Add tag and release notes |  10/12 |
| ✔| Update version for next release | 10/12 | 

### URL for the staging repo is:
https://oss.sonatype.org/service/local/staging/repository/commicrosoftazure-2645

**Comment by jdneo** [comment]
cc @pragnagopa

**Comment by Flanker32** [comment]
Done, new version can be found there. https://repo.maven.apache.org/maven2/com/microsoft/azure/azure-functions-maven-plugin/1.0.0-beta-7/
