### ISSUE TITLE
POM scaffolds to help configure for deployment/interact with App Service 

### ISSUE THREAD

**Issue by Matthew-Dong** [microsoft/azure-maven-plugins#416]

**Comment by kyliel** [comment]
1. Offer the right POM snippet for Azure App Service Linux, App Service Windows, App Service Container. And it also could be applied to Functions and others. 
2. If I run a maven command with some parameters, corresponding output can be added into the POM file. 
3. Have the canonical sample branch for each and let the user simply clone, set a couple unique params (globally unique app service name, resource group, etc) and go.

**Comment by Flanker32** [comment]
Now we could use `mvn azure-webapp:config` to generate or update maven configurations.
