### ISSUE TITLE
Error when Connect to localhost:2375 

### ISSUE THREAD

**Issue by Matthew-Dong** [Microsoft/azure-maven-plugins#42]
Error Message -> HttpHostConnectException: Connect to localhost:2375 

Possible solution: **_enable_** Expose Docker Daemon on TCP://localhost:2375 without TLS 

![expose docker daemon](https://user-images.githubusercontent.com/7653539/29961208-62275d06-8f31-11e7-98e4-19b875442c02.png)

**Comment by xscript** [comment]
@rmcmurray Could you add a note about this issue in the [ACR article](https://docs.microsoft.com/en-us/azure/app-service-web/app-service-web-deploy-spring-boot-app-from-container-registry-using-maven-plugin)?
Thanks!

**Comment by rmcmurray** [comment]
@Matthew-Dong and @xscript - I fixed this a few weeks ago; but I just realized that I neglected to close the loop on this bug. If you look at the following article, you will see that it has a note section which mentions this issue specifically. Thanks!

https://docs.microsoft.com/en-us/java/azure/spring-framework/deploy-spring-boot-java-app-from-container-registry-using-maven-plugin

**Comment by xscript** [comment]
Thanks @rmcmurray  for fixing this!
