### ISSUE TITLE
[Functions] Set javaversion to 1.8 on deploy

### ISSUE THREAD

**Issue by pragnagopa** [Microsoft/azure-maven-plugins#433]
Functions only supports Java 8 for now. Plugin or archetype needs to verify this and show friendly error message.

**Comment by pragnagopa** [comment]
cc: @asavaritayal

**Comment by jdneo** [comment]
@pragnagopa Just double confirm: Do you mean we need to make sure the java version on the cloud side should be Java 8?

**Comment by Flanker32** [comment]
@pragnagopa  Here is the planed workflow for java version setting
* Add new function
  Set Java Version = `1.8`
* Update function
  - Old java version = `Off`
     Throw Exception
  - Old java version !=1.8 (e.g. 1.7)
      Show warning, set java version to 1.8 and deploy 
  - Old java version == 1.8
      Show message and deploy
  - Old java version == 1.8 but not the latest
      Show warning and deploy

Do you have any comments on this issue?

**Comment by pragnagopa** [comment]
For existing apps, this property is null. Do not throw. Just show info message that this property is being added

Also, need to show error if not using java 8 locally

**Comment by pragnagopa** [comment]
I have updated title to be more explicit. This issue will address 
- showing error if java 8 not used when developing locally 
- set javaVersion to 1.8 as part of deploying

**Comment by pragnagopa** [comment]
All the changed needed in the Antares have been rolled out. 
@Flanker32 / @jdneo  - Can you please prioritize this work?

**Comment by Flanker32** [comment]
@pragnagopa merged in #464

**Comment by pragnagopa** [comment]
cc @Hazhzeng  @amamounelsayed
