### ISSUE TITLE
[Functions] Remove strong dependency on azure-functions-java-library

### ISSUE THREAD

**Issue by pragnagopa** [microsoft/azure-maven-plugins#456]
cc @soninaren
Right now any updates to annotations even adding new properties to existing annotations  require updating maven plugin
For example,  [CosmosDBBinding.java](https://github.com/Microsoft/azure-maven-plugins/blob/develop/azure-functions-maven-plugin/src/main/java/com/microsoft/azure/maven/function/bindings/CosmosDBBinding.java) is a copy of 
[CosmosDBTrigger.java](https://github.com/Azure/azure-functions-java-library/blob/dev/src/main/java/com/microsoft/azure/functions/annotation/CosmosDBTrigger.java).

Need to decouple library and plugin dependency. All the information needed for plugin should be coming from azure-functions-java-library

**Comment by pragnagopa** [comment]
@jdneo / @Flanker32  Lets discuss this post GA.

**Comment by Flanker32** [comment]
@pragnagopa @jdneo Refactor done in pr #508, please have a review.

In this pr, i remove other binding classes except BaseBinding, attributes was get by java reflect and save to the map of Basebinding, i will get all attributes defined in annotation and save attributes which is different with its default value, besides, a serializer was created to keep the format of generated function.json.

For now adding new properties to existing annotations will not affect maven plugin, but remove an existing annotations will still not work. I store the type and direction of annotations in BindingEnum and save the relevance in BindingFactory, which import all annotations from java lib. 

@pragnagopa 
1. Is there any other way for us to get the type and direction of each annotation? If so, we could decouping the dependency between function lib and maven plugin.
2. Could you please update the [function.json scheme](http://json.schemastore.org/function)? Schema could be much helpful in local validation and users could verify and update their code according to schema as well

**Comment by kulkarnisonia16** [comment]
https://github.com/Azure/azure-functions-java-library/issues/69
