### ISSUE TITLE
Maven Azure Web App Plugin EndGame 1.5.0

### ISSUE THREAD

**Issue by SummerSun** [Microsoft/azure-maven-plugins#496]
## Build
- [x] 11/4 - Build and push jar files to stage repository @SummerSun 

## Test
- [x] 11/15 - Run [Test Plan](https://github.com/Microsoft/azure-maven-plugins/wiki/Test-Plan-for-Web-App) @bsaby  @lxhmavis @sallyur 
> The {id} is commicrosoftazure-2708

## Release
- [x] Add 1.5.0 tag for web app @SummerSun 
- [x] Add 1.2.3 tag for library module @SummerSun 
- [x] Release to maven central @SummerSun

**Comment by sallyur** [comment]
### Run Test Plan with V1 and V2
Build 1.5.0
### Two new issues found #497 #499

### Test results
**V1**


Case | Details | Issue
-- | -- | --
Can deploy to Web App on windows | Pass |  
Can Auto detect deployment type | Pass |  
Can deploy to Deployment Slot on Windows | Pass |  
Can deploy to Web App on Linux | Pass |  
Can deploy to Deployment Slot on Linux | Pass |  
Can deploy to Web App on Linux with public Docker Hub container image | Pass |  
Can deploy to Deployment Slot on Linux with public DockerHub container image | Pass |  
Can deploy to Web App on Linux with private Docker Hub container image | Pass |  
Can deploy to Deployment Slot on Linux with private DockerHub container image | Pass |  
Can deploy to Web App on Linux with Docker container image in private container registry | Pass |  
Can deploy to Deployment Slot on Linux with docker container image in private container registry | Pass |  
Can deploy Web App to existing App Service Plan | Pass |  


**V2**

Case | Details | Issue
-- | -- | --
Can deploy to Web App on windows | #499 |  
Can deploy to Deployment Slot on Windows | Pass |  
Can deploy to Web App on Linux | #497 #499 |  
Can deploy to Deployment Slot on Linux | Pass |  
Can deploy to Web App on Linux with public Docker Hub container image | #499|  
Can deploy to Deployment Slot on Linux with public DockerHub container image | Pass |  
Can deploy to Web App on Linux with private Docker Hub container image | #499 |  
Can deploy to Deployment Slot on Linux with private DockerHub container image | Pass |  
Can deploy to Web App on Linux with Docker container image in private container registry | #499 |  
Can deploy to Deployment Slot on Linux with docker container image in private container registry | Pass |  
Can deploy Web App to existing App Service Plan | Pass |
