### ISSUE TITLE
Use string for configuration of pricing tiers

### ISSUE THREAD

**Issue by SummerSun** [microsoft/azure-maven-plugins#500]
We are currently hard code all the available pricing tiers for Azure App Service, It will be more reliable if we leverage the management SDK to get all available pricing tiers. However,the premium pricing tier changes in Azure (P1 -> P1V2) does not reflect in SDK yet https://github.com/Azure/azure-libraries-for-java/issues/660 . Make this issue to track, we could update once SDK do the changes.

**Comment by SummerSun** [comment]
Updated the pricing tier configuration to string, and map them to `PricingTier`. Add workaround the unavailable values of P1, P2 and P3.

**Comment by Flanker32** [comment]
Done in #650
