### ISSUE TITLE
Maven Azure Web App Plugin 1.5.1 EndGame

### ISSUE THREAD

**Issue by SummerSun** [Microsoft/azure-maven-plugins#506]
## Build
- [x] 11/21 - Build and push jar files to stage repository @SummerSun 

## Test
- [x] 11/23 - Run [Test Plan](https://github.com/Microsoft/azure-maven-plugins/wiki/Test-Plan-for-Web-App) @bsaby  @lxhmavis @sallyur 
> The {id} is commicrosoftazure-2715

## Release
- [x] Add 1.5.1 tag for web app @SummerSun 
- [x] Add 1.2.4 tag for library module @SummerSun 
- [x] Release to maven central @SummerSun 
- [x] Bump version for next release

**Comment by sallyur** [comment]
### Run Test Plan with V1 and V2

Build 1.5.1
Id: 2715

### Open bugs
#510 

### Test results
**V1**

Case | Details | Issue
-- | -- | --
Can deploy to Web App on windows | Pass |  
Can Auto detect deployment type | Pass |  
Can deploy to Deployment Slot on Windows | Pass |  
Can deploy to Web App on Linux | Pass |  
Can deploy to Deployment Slot on Linux | Pass |  
Can deploy to Web App on Linux with public Docker Hub container image | Pass |  
Can deploy to Deployment Slot on Linux with public DockerHub container image | Pass |  
Can deploy to Web App on Linux with private Docker Hub container image | Pass |  
Can deploy to Deployment Slot on Linux with private DockerHub container image | Pass |  
Can deploy to Web App on Linux with Docker container image in private container registry | Pass |  
Can deploy to Deployment Slot on Linux with docker container image in private container registry | Pass |  
Can deploy Web App to existing App Service Plan | #510 |  

**V2**

Case | Details | Issue
-- | -- | --
Can deploy to Web App on windows | Pass |  
Can deploy to Deployment Slot on Windows | Pass |  
Can deploy to Web App on Linux | Pass |  
Can deploy to Deployment Slot on Linux | Pass |  
Can deploy to Web App on Linux with public Docker Hub container image | Pass |  
Can deploy to Deployment Slot on Linux with public DockerHub container image | Pass |  
Can deploy to Web App on Linux with private Docker Hub container image | Pass |  
Can deploy to Deployment Slot on Linux with private DockerHub container image | Pass |  
Can deploy to Web App on Linux with Docker container image in private container registry | Pass |  
Can deploy to Deployment Slot on Linux with docker container image in private container registry | Pass |  
Can deploy Web App to existing App Service Plan | #510 |
