### ISSUE TITLE
Snapshot version causing Build failure from Central Maven Repo

### ISSUE THREAD

**Issue by anumalasri** [Microsoft/azure-maven-plugins#518]
### Plugin name and version
azure-functions-maven-plugin: 1.2.0
### Plugin configuration in your `pom.xml`
  ```
<properties>
      <azure.functions.maven.plugin.version>1.2.0</azure.functions.maven.plugin.version>
        <azure.functions.java.library.version>1.2.0</azure.functions.java.library.version>
   </properties>
  .....
<plugin>
   <groupId>com.microsoft.azure</groupId>
   <artifactId>azure-functions-maven-plugin</artifactId>
   <version>${azure.functions.maven.plugin.version}</version>
</plugin>
```
### Expected behavior
We should be able to download all dependencies from Central Maven Repo
### Actual behavior
Maven build is failing as given Plugin referring a parent with SNAPSHOT version, which does not exist in Central Maven Repo. 
### Steps to reproduce the problem

 
http://central.maven.org/maven2/com/microsoft/azure/azure-functions-maven-plugin/1.2.0/azure-functions-maven-plugin-1.2.0.pom

We are unable to connect to OSS due to enterprise issues.  When we only have Central Maven,  we are unable to use azure-functions-maven-plugin and run build. 

Please update necessary versions and publish them to Central Repo.

Thanks

**Comment by Flanker32** [comment]
@anumalasri  Thanks for your report, we have released new version of Function Plugin and Plugin lib, all snapshot dependency has been removed in our repo, but some of our dependency may still depend on libs with SNAPSHOT version, please have a test whether function plugin could work now.

**Comment by anumalasri** [comment]
We are getting new error ...  Hence, we unable to use JAVA functions in Azure.. 

> Could not resolve dependencies for project com.metlife.azure:azure-java-function:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at com.microsoft.azure.functions:azure-functions-java-library:jar:1.2.0: Failed to read artifact descriptor for com.microsoft.azure.functions:azure-functions-java-library:jar:1.2.0: Could not find artifact **com.microsoft.maven:java-8-parent:pom:8.0.0-SNAPSHOT** in snapshots

**Comment by Flanker32** [comment]
@anumalasri  Sorry for replying so late.
@pragnagopa Could you please look at this issue? I found that maven dependencies in azure-functions-java-library has been updated, do you have a release plan for this?

**Comment by pragnagopa** [comment]
Will release updated version of azure-functions-java-library soon. Will update this issue once its published.

**Comment by pragnagopa** [comment]
azure-functions-java-library version 1.2.2 is now published to maven central.
@Flanker32 - Please update maven plugin to the latest version.

**Comment by Flanker32** [comment]
Closed as all dependencies has been updated to stable versions.
