### ISSUE TITLE
In README, configuration linuxRuntime tag not enclosed correctly

### ISSUE THREAD

**Issue by sophiaso** [Microsoft/azure-maven-plugins#521]
On webapp maven plugin [README page](https://github.com/Microsoft/azure-maven-plugins/blob/develop/azure-webapp-maven-plugin/README.md), `Web App on Linux` section:

```
 <linuxRuntime>tomcat 8.5-jre8</javaVersion>
```

 Tag name linuxRuntime does not match.

**Comment by Flanker32** [comment]
Fixed in PR #523
