### ISSUE TITLE
[Functions]Validate resource group name

### ISSUE THREAD

**Issue by JohnReeson** [microsoft/azure-maven-plugins#537]
### Plugin name and version
Maven Plugin for Azure Functions 1.2.1
### Plugin configuration in your `pom.xml`
Omit irrelated content
```
<properties>
    <functionResourceGroup>johnreeson@funcjava</functionResourceGroup>
</properties>
```
### Expected behavior
Validate the group name and offer error message like contain invalid character
### Actual behavior
[ERROR] Failed to execute goal com.microsoft.azure:azure-functions-maven-plugin:1.2.1:deploy (default-cli) on project com.func1: Status code 400 -> [Help 1]

**Comment by Flanker32** [comment]
Fixed in #676
