### ISSUE TITLE
After run azure-webapp:config, there is no <deployment> element in pom.xml

### ISSUE THREAD

**Issue by sallyur** [Microsoft/azure-maven-plugins#548]
### Plugin name and version
```
Maven plugin for azure webapps
ID: 2832
Version: 1.5.2
```

### Plugin configuration in your `pom.xml`

```
<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">  
  <modelVersion>4.0.0</modelVersion>  
  <groupId>com.ms.webapp</groupId>  
  <artifactId>webapp0</artifactId>  
  <packaging>war</packaging>  
  <version>1.0-SNAPSHOT</version>  
  <name>webapp0 Maven Webapp</name>  
  <url>http://maven.apache.org</url>  
  <dependencies> 
    <dependency> 
      <groupId>junit</groupId>  
      <artifactId>junit</artifactId>  
      <version>3.8.1</version>  
      <scope>test</scope> 
    </dependency> 
  </dependencies>  
  <pluginRepositories> 
    <pluginRepository> 
      <id>commicrosoftazure-2832</id>  
      <name>commicrosoftazure-2832</name>  
      <url>https://oss.sonatype.org/content/repositories/commicrosoftazure-2832/</url> 
    </pluginRepository> 
  </pluginRepositories>  
  <build> 
    <finalName>webapp0</finalName>  
    <plugins> 
      <plugin> 
        <groupId>com.microsoft.azure</groupId>  
        <artifactId>azure-webapp-maven-plugin</artifactId>  
        <version>1.5.2</version>  
        
      </plugin> 
    </plugins> 
  </build> 
</project>

```
### Expected behavior
There should have deployment element in pom.xml 
### Actual behavior
There is no deployment element in pom.xml 
![image](https://user-images.githubusercontent.com/28860891/50895213-68c95c00-1440-11e9-9466-a9377fae9db8.png)

### Steps to reproduce the problem

1. Prepare a webapp maven project with neweast maven plugin version
2. Set the pom file as above
3. Run "mvn clean package"
4. Run "mvn azure-webapp:config"
5. Os and Runtime Stack can choose any value
6. The confirm step Input "N" 
7. The next steps can all set to default until the end

**Comment by sallyur** [comment]
The issue also repro when V1 configuration with container settings convert to V2
V1:
![image](https://user-images.githubusercontent.com/28860891/50953980-ffa12180-14ef-11e9-843a-d4063b23a199.png)
Convert to V2: there is no deployment element
![image](https://user-images.githubusercontent.com/28860891/50953961-ee581500-14ef-11e9-8b35-56d61245ab76.png)

**Comment by Flanker32** [comment]
Yes, it's an issue with V1Configuration Parser, we will resolve it later and disable convert function in this release

**Comment by Flanker32** [comment]
Close this issue as we don't support `config` to  V1 schema now.
