### ISSUE TITLE
[Functions] Add support for CustomBinding

### ISSUE THREAD

**Issue by pragnagopa** [Microsoft/azure-maven-plugins#559]
PR https://github.com/Azure/azure-functions-java-library/pull/76 adds CustomBinding annotation.
Plugin needs to be updated to generate function.json for the customBinding annotation.
Sample code:
```
@CustomBinding(direction = "in", name = "customInput", type = "customTrigger") String customTriggerInput
```
should generated function.json
```
"type" : "customTrigger",
"direction" : "in",
"name" : "customInput",
 ```

**Comment by pragnagopa** [comment]
@Flanker32 / @jdneo - This is a tracking item. Will update the issue once snapshot version of library is released.

**Comment by pragnagopa** [comment]
azure-functions-java-library version 1.3.0-SNAPSHOT is now available in snapshot repository. 
Following function
```java
public void CustomBinding_Valid(@HttpTrigger(name = "req", methods = { HttpMethod.GET,
      HttpMethod.POST }, authLevel = AuthorizationLevel.FUNCTION) HttpRequestMessage<String> request,
      @TestCustomBinding(index = "testIndex", path = "testPath") String customInput) {
  }
```
TestCustomBinding is defined
```
@Target(ElementType.PARAMETER)
@Retention(RetentionPolicy.RUNTIME)
@CustomBinding(direction = "in", name = "message", type = "customBinding")
public @interface TestCustomBinding {
   String index();
   String path();
}
```

should generate
```
"type" : "customBinding",
"direction" : "in",
"name" : "message",
"index " : "testIndex",
"path" : "testPath"
```

**Comment by Flanker32** [comment]
@pragnagopa  i just find `CustomBinding` in function java lib with `name`,'type' and 'direction', i didn't find `TestCustomBinding `, is there anything wrong with the version?

**Comment by pragnagopa** [comment]
TestCustomBinding Is user defined.

**Comment by pragnagopa** [comment]
Here is sample code for invoking methods on a user defined annotation
```java
for (Method annotationMethod : annotation.annotationType().getDeclaredMethods()) {
						try {
							if (Modifier.isPublic(annotationMethod.getModifiers())) {
								Object invokeResult = annotationMethod.invoke(annotation);
								System.out.println(annotationMethod.getName() + "=" + invokeResult);
							}
						} catch (Exception ex) {
							// ignore
						}
					}
```

Generate key value pairs in function.json. No validation required.
