### ISSUE TITLE
[Functions] Eclipse usage

### ISSUE THREAD

**Issue by JohnReeson** [Microsoft/azure-maven-plugins#563]
### Plugin name and version
azure-functions-maven-plugin 1.2.1

Just a question, is there any way to work with function mvn plugin easily in Eclipse? The Console is read-only for azure function related operation. For example, `azure-functions:run`, we can't use `Ctrl+C` or any button there to terminate function host. `azure-fucntions:add` not able to input and see failed directly. 

Find a workaround, run the mvn command in terminal plugin as we do without IDE. It seems an Eclipse side problem, but I just check here in case someone has some insights.

**Comment by Flanker32** [comment]
@JohnReeson You may consider using shell plugins in Eclipse to execute function plugin goals.

**Comment by JohnReeson** [comment]
@Flanker32 @jdneo Thank you guys, I have been playing with TF terminal. So I just close it since it's an external issue and we have a useful workaround.
