### ISSUE TITLE
[Functions] Print function URLs on publish

### ISSUE THREAD

**Issue by asavaritayal** [microsoft/azure-maven-plugins#571]
(This has been a common piece of feedback, especially for HTTP triggered functions. )

**Problem statement:** 
Once the user deploys their Java project using the `azure-functions:deploy` target, they have no clue how to call the function without navigating to the portal to "Get function URL <>". This requires prior knowledge of the portal UI. Also creates an additional step in the E2E experience. 

**Options:** 
The Core Tools recently introduced an update to publish the function URLs to the CLI once the deployment completes: 

![image](https://user-images.githubusercontent.com/8435148/51772297-7ddcf680-20a0-11e9-9535-6755b80c8a70.png)

It'll be great to have a similar experience in the Maven CLI as well. 

/cc @hexiaokai @selvasingh

**Comment by Flanker32** [comment]
@asavaritayal 
Yes, it do values and i will try to implement it with HTTP trigers.

**Comment by Flanker32** [comment]
@asavaritayal Sorry for reply late, this was implemented in pr #596, for now we use azure java sdk to implement it as list function of a function app is not supported with mgmt sdk.

**Comment by asavaritayal** [comment]
@Flanker32 thanks for the update. Know that @mathewc and @divyagandhi01 made some improvements on the ARM layer to enable the same scenario. Calling the APIs directly may be an option if the management SDK doesn't work out.

**Comment by ggailey777** [comment]
Just an FYI...Visual Studio Code extension doesn't do this automatically, but they provide UI to get the URL of individual HTTP endpoints, which is very useful when function keys are used. I have requested a similar feature for the VS Functions tools.

**Comment by Flanker32** [comment]
Done in https://github.com/microsoft/azure-maven-plugins/pull/1106
