### ISSUE TITLE
[Functions] Enable Application Insights by default

### ISSUE THREAD

**Issue by asavaritayal** [microsoft/azure-maven-plugins#574]
Enable Application Insights logging by default on `azure-functions:deploy`.

/cc @hexiaokai

**Comment by asavaritayal** [comment]
Portal already does this. We should enable AI in the same region or the closest location to the function app.

**Comment by ggailey777** [comment]
As a data point, both Core Tools and VS Code now both create the Application Insights resource with the other function app resources.

**Comment by Flanker32** [comment]
Done in function plugin 1.5.0
