### ISSUE TITLE
How to add Apache TomEE as new javawebcontainer or webcontainer?

### ISSUE THREAD

**Issue by cesarhernandezgt** [Microsoft/azure-maven-plugins#579]
### Plugin name and version
azure-webapp-maven-plugin v1.5.3

By looking at these lines of code: 
https://github.com/Microsoft/azure-maven-plugins/blob/9ad9b941c95ffbefd1215ac0b7c42f0879c1eafe/azure-webapp-maven-plugin/src/main/java/com/microsoft/azure/maven/webapp/parser/V1ConfigurationParser.java#L25-L31
https://github.com/Microsoft/azure-maven-plugins/blob/dd26f2b5cfd062492030e2f488dd6ecef6570fd3/azure-webapp-maven-plugin/src/main/java/com/microsoft/azure/maven/webapp/configuration/RuntimeSetting.java#L24-L27

I would like to know where I can contribute to add Apache TomEE as another   SUPPORTED_LINUX_RUNTIMES this azure-maven-plugin usses?

**Comment by Flanker32** [comment]
@cesarhernandezgt 
Thanks for your report, but for now linux app service only support jre, tomcat and wildfly as runtime stack.

**Comment by cesarhernandezgt** [comment]
@Flanker32 Thaks for your reply. 
I realize that these supported app services are out of the scope of this repository and I provided feedback in the Azure feedback forum: https://feedback.azure.com/forums/169385-web-apps/suggestions/36760519-why-apache-tomee-is-not-avialable-under-app-servic
I think this can be closed now.
