### ISSUE TITLE
Besides maven plugins(like Findbugs/PMD/CheckStyle),  how Microsoft do SAST?

### ISSUE THREAD

**Issue by dreaminplus** [microsoft/azure-maven-plugins#584]
Hi, 
As I learned from the internet, Microsoft may use  Roslyn/Semmel/BinSkim/Tslint/Credential Scanner etc. to scan the code, where can I get the exact practice about Microsoft-SAST-Practice~? Among some of the using tools, have any plan to develop the extensions to support on Azure DevOps?

**Comment by Flanker32** [comment]
@dreaminplus Sorry for the delay, `azure-maven-plugins` is a repository contains all Maven plugins for Microsoft Azure services.  All of the plugins are java projects and we use tools like CheckStyle to do SAST, for Azure DevOps, we have Security Risk Detection services, please refer [here](https://www.microsoft.com/en-us/security-risk-detection/) for more information.
