### ISSUE TITLE
The position where the underline appears is not accurate when the cursor hovers on the URL

### ISSUE THREAD

**Issue by ZhengJun003** [Microsoft/azure-maven-plugins#591]
### Plugin name and version

```
Maven Plugin for Azure Functions: 1.3.0
Operation system: Mac
```

### Actual behavior

![image](https://user-images.githubusercontent.com/41051257/53614125-af9f2b00-3c13-11e9-9262-a82f7bfde26c.png)

**Comment by jdneo** [comment]
This is not in the Maven plugin scope, the output is generated by `Function CLI`, closing it.
