### ISSUE TITLE
The default functions has wrong behave to handle param given in url

### ISSUE THREAD

**Issue by zmqcherish** [Microsoft/azure-maven-plugins#60]
### Plugin name and version
Maven Plugin for Azure Functions

### Plugin configuration in your `pom.xml`
[pom.txt](https://github.com/Microsoft/azure-maven-plugins/files/1443875/pom.txt)(the default maven create)

### Expected behavior
when running the function,and excute the command "curl http://localhost:7071/api/hello?req=world", it should return "Hello, world"

### Actual behavior
get the 400 response

### Steps to reproduce the problem
with the guideline [https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-java-maven](url) , the default function created by maven is below:
`@FunctionName("hello")
    public HttpResponseMessage hello(@HttpTrigger(name = "req", methods = {"get", "post"}, authLevel = AuthorizationLevel.ANONYMOUS) HttpRequestMessage request,
                                     final ExecutionContext context) {
        context.getLogger().info("Java HTTP trigger processed a request.");

        // Parse query parameter
        String name = request.getQueryParameters().get("name");

        if (name == null) {
            // Get request body
            Object body = request.getBody();
            if (body != null) {
                name = body.toString();
            }
        }

        if (name == null) {
            return request.createResponse(400, "Please pass a name on the query string or in the request body");
        } else {
            return request.createResponse(200, "Hello, " + name);
        }
    }`

1. there is a confuse: why the parameter key is named "name" in code rather than“req”
`String name = request.getQueryParameters().get("name");"`

2. If I change the code "String name = request.getQueryParameters().get("name");" to be "String name = request.getQueryParameters().get("req");"
and excute the command "curl http://localhost:7071/api/hello?req=world", then it get 400 response,that is it can not get the parameter "req".That is, the function can only handle the "name" param

**Comment by xscript** [comment]
@JunyiYi  Above code is coming from Azure Functions Java templates. Could you help explain more about this issue?

**Comment by JunyiYi** [comment]
We are upgrading to BETA-2 runtime now, so the sample above is somehow out-of-dated, we will update the templates soon. But for your questions:
1. `"req"` is the name of HttpTrigger that represents the whole **http request message**, while `"name"` is the **query parameter** within that http request message; which is to say, `"req"` contains a query parameter called `"name"`. So the URL to trigger it should be "curl http://localhost:7071/api/hello?name=world".
2. This should work. At least in BETA-2.

**Comment by zmqcherish** [comment]
@JunyiYi thanks.
but it still cannot work well in  version 2.0.1-beta.21. 
below I restate the steps:
change the default templates line 21 the "name" string to "param" : 
`String name = request.getQueryParameters().get("param");`
then execute the command: curl http://localhost:7071/api/hello?param=a
it get 400 response,while execute  curl http://localhost:7071/api/hello?name=a, it get "right" response

**Comment by JunyiYi** [comment]
Did you rerun the whole mvn clean package and then mvn azure-functions:run after you change the code from "name" to "param"?

**Comment by zmqcherish** [comment]
@JunyiYi yes. I have rerun the command.and today it work well while date 11-12 can not work.
Now,I still confuse the code: name="req" in  @HttpTrigger . 
As you say:
> "req" is the name of HttpTrigger that represents the whole http request message 

But what is the "req" use for? Since there is a HttpRequestMessage parameter named "request".
Would you mind show me an example? thanks.

**Comment by JunyiYi** [comment]
Sure. So first let me explain about the whole maven plugin:
1. You write *.java code as functions
2. After you run `mvn clean package`, it will generate 3 things in target/azure-functions/**/*.*:
  - *.jar which contains your logic
  - **function.json** which used to declare all bindings
  - **host.json** which used to declare the host configuration
3. `mvn azure-functions:run` will invoke NodeJS Azure Functions Runtime you installed globally, which only recognizes host.json and functions.json, it doesn't care about anything in Java.

So `"req"` is used as the binding name in **function.json** mentioned above.  You do not directly use it, but Azure Functions Runtime cares about it. And the HTTP parameters are metadata in the `"req"` binding.

**Comment by zmqcherish** [comment]
@JunyiYi thank you for you reply

**Comment by getmckenzie** [comment]
@JunyiYi  Can you please let me know how to update azure-functions-java-core to the latest.  My current version in the POM shows [1.0.0-beta-1,1.0.0)

**Comment by JunyiYi** [comment]
Just update `<version>1.0.0-beta-2</version>` section of the `azure-functions-java-core` dependency in your `POM.xml`.

**Comment by jdneo** [comment]
Close it since the problem looks to have been solved.
