### ISSUE TITLE
azure-functions-maven-plugin not replacing connectionString in function.json

### ISSUE THREAD

**Issue by panneerpst** [microsoft/azure-maven-plugins#601]
while running mvn azure-functions:deploy, function.json is not generating connection string for event hub trigger
pom.xml
        <azure.functions.maven.plugin.version>1.3.0</azure.functions.maven.plugin.version>
        <azure.functions.java.library.version>1.2.2</azure.functions.java.library.version>
         <plugin>
                <groupId>com.microsoft.azure</groupId>
                <artifactId>azure-functions-maven-plugin</artifactId>
                <configuration>
                    <resourceGroup>${functionResourceGroup}</resourceGroup>
                    <appName>${functionAppName}</appName>
                    <region>${functionAppRegion}</region>
                    <appSettings>
                        
							<property>
								<name>WEBSITE_RUN_FROM_PACKAGE</name>
								<value>1</value>
							</property>
                        <property>
                            <name>FUNCTIONS_EXTENSION_VERSION</name>
                            <value>~2</value>
                        </property>
                        <property>
                            <name>FUNCTIONS_WORKER_RUNTIME</name>
                            <value>java</value>
                        </property>	
                    </appSettings>
                </configuration>
                <executions>
                    <execution>
                        <id>package-functions</id>
                        <goals>
                            <goal>package</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

function.json
{
  "scriptFile" : "..\\eventhubfunc-functions-1.0-SNAPSHOT.jar",
  "entryPoint" : "com.eventhub.trigger.Eventhub_test_trigger_func.run",
  "bindings" : [ {
    "type" : "eventHubTrigger",
    "direction" : "in",
    "name" : "message",
    "connection" : "**connection**",
    "eventHubName" : "mylearningeventhub",
    "cardinality" : "MANY"
  } ]
}

Due to this appsettings connection string is not getting populated in azure function app. The same is working in local.

**Comment by Flanker32** [comment]
@panneerpst Maven plugin will not generate connection string to function.json, instead, it will save the app setting name which contains connection string. So please create an eventhub and set its connection string to [appSettings](https://github.com/Microsoft/azure-maven-plugins/tree/develop/azure-functions-maven-plugin#configurations) first and try deploy again.

**Comment by panneerpst** [comment]
I am using azure- function: add client to create function.if I am creating through cli ,I was not able to update the appsettings in through console. function turns read only.please confirm,
first I need to create using azure console and set the appsettings?

**Comment by Flanker32** [comment]
@panneerpst  No need to create functions first, you may set the appSetting in pom and maven plugin will help you set all attributes.
``` xml
<build>
        <plugins>
            <plugin>
                <groupId>com.microsoft.azure</groupId>
                <artifactId>azure-functions-maven-plugin</artifactId>
                <configuration>
                   ...
                    <appSettings>
                        <property>
                            <name> <!--Connection String Property --> </name>
                            <value><!-- Connection String --></value>
                        </property>
```

You may use azure cli command to update application setting, you may get more infos [here](https://docs.microsoft.com/en-us/cli/azure/functionapp/config/appsettings?view=azure-cli-latest)

**Comment by josh-roberts-phision** [comment]
I am having this issue as well, but referencing an App Setting (TRANSACTIONS_EVENT_HUB_CONNECTION_STRING). The function.json is created as expected with the entry "connection" : "TRANSACTIONS_EVENT_HUB_CONNECTION_STRING"

However, upon deploy, it erases the setting value in my app settings.

**Comment by Flanker32** [comment]
@josh-roberts-phision Could you please share the full pom file? I tried to deploy a function with attributes with the same name and the value was set to Azure successfully.

**Comment by ekazaltzis** [comment]
I seem to have the same problem. In azure portal I can however select the correct connection string but wrong cardinality is shown it is set to ONE instead of MANY which is defined in the original function.json?

This obviously is a problem because my function expects a List of items instead of 1 item
