### ISSUE TITLE
Failed to check update for Azure Functions Core Tools on Mac

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-maven-plugins#603]
### Plugin name and version
Maven Plugin for Azure Functions: 1.3.1

### Actual behavior
Failed to check update for Azure Functions Core Tools
![image](https://user-images.githubusercontent.com/22470312/54742316-0937bb80-4bfc-11e9-946f-54b0183dc2a5.png)

I use homebrew to install functions core tools on MacOS
https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local#brew
### Steps to reproduce the problem

1. Generate a maven function project with plugin version 1.3.1
2. Run command: `mvn clean package`

**Comment by pomverte** [comment]
I've also reproduce the bug with `com.microsoft.azure:azure-functions-maven-plugin:1.4.1` using a `@BlobTrigger` but not with `@HttpTrigger`
