### ISSUE TITLE
[Functions] Set app settings on deployment via zip deployment

### ISSUE THREAD

**Issue by anky2209** [Microsoft/azure-maven-plugins#605]
### Plugin name and version
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-functions-maven-plugin</artifactId>
    <version>1.2.2</version>

### Expected behavior
We set appsettings in pom.xml in azure-functions-maven-plugin like this.
```
            <plugin>
                <groupId>com.microsoft.azure</groupId>
                <artifactId>azure-functions-maven-plugin</artifactId>
                <configuration>
                    <resourceGroup>${functionResourceGroup}</resourceGroup>
                    <appName>${functionAppName}</appName>
                    <region>${functionAppRegion}</region>
                    <appSettings>
                        <!-- Run Azure EventServerResponseReceiver from package file by default -->
                        <property>
                            <name>test</name>
                            <value>123</value>
                        </property>
                    </appSettings>
                </configuration>
            </plugin>
```

So, these app settings are set in Functions App Settings in Portal when i deploy function via` mvn azure-functions:deploy`.
The same behavior is not happening when i do ZIP deployment(we do `mvn clean package` before zip deploy).

### Actual behavior
App settings should get reflected in Portal application settings when deployment is done via zip deployment

**Comment by jeffhollan** [comment]
Behind the scenes I though that `mvn azure-functions:deploy` was leveraging zip deploy.  So when you say you do `zip deploy` can you be specific on what or how you are doing that?

**Comment by jasonfreebergtest** [comment]
@jeffhollan I think it's a complaint that the features are not as parity.

@anky2209, if you use Zip deploy you need to set the application settings separately.

**Comment by Flanker32** [comment]
@anky2209 @jasonfreebergtest For now function plugin has supported set the application setting while deployment.

@anky2209 Could you please share the pom file or the output of `mvn azure-function:deploy -X`, i tried to deploy an function with appsetting by maven plugin and it work well.

**Comment by JasonFreeberg** [comment]
@Flanker32 I am aware of what the Maven plugins support. This user is talking about Zip Deploy. He is sad that Zip Deploy does not support app settings.

**Comment by jeffhollan** [comment]
That clears it up.  I imagine the work to make this work in zip deploy would potentially be on Kudu (the code that is on the receiving end of the zip deploy API) to potentially extract the POM.xml file from the zip, parse out the app settings, and then update them as part of the publish process.  It doesn't sound ideal to me but it's something that could be put on the Kudu backlog and get feedback.  For now I think the recommended action would be either use `mvn azure-functions:deploy` if at all you can, and if you can't or choose to use zip deploy you'd need to update app settings separately

That's also assuming that the POM.xml even lives in the eventual zip file.  If not I don't know where zip deploy would know what app settings to set.

**Comment by Flanker32** [comment]
@JasonFreeberg  Thanks for your explanation.
Seems the issue is clear, zip deploy will not set the application setting, but user could achieve this through maven plugin, @anky2209 you may raise issue in [kudu repo](https://github.com/projectkudu/kudu) if you have some requests on zip deploy.

**Comment by brunoborges** [comment]
@jeffhollan instead of pulling information from `pom.xml` inside the ZIP, the API should instead accept settings in a different, very tool agnostic way. HTTP headers come to mind. 

Developers may use different tools to build the ZIP (Gradle) or simply not have `pom.xml`  inside the ZIP.

**Comment by jeffhollan** [comment]
Potentially - It's a fair discussion for any issue that may / may not get created on the kudu repo
