### ISSUE TITLE
The zip deploy error for Spring boot deployment 

### ISSUE THREAD

**Issue by ggthename** [microsoft/azure-maven-plugins#608]
### Plugin name and version
azure-webapp-maven-plugin 1.4.0
### Plugin configuration in your `pom.xml`

```
<plugin>
				<groupId>com.microsoft.azure</groupId>
				<artifactId>azure-webapp-maven-plugin</artifactId>
				<version>1.4.0</version>
				<configuration>
					<deploymentType>jar</deploymentType>


					<appSettings>
						<property>
							<name>JAVA_OPTS</name>
							<value>-Dserver.port=80</value>
						</property>
					</appSettings>


					<resourceGroup>${resource.group.name}</resourceGroup>
					<appName>${webapp.name}</appName>
					<region>${region}</region>

					<linuxRuntime>jre8</linuxRuntime>
				</configuration>
			</plugin>
```

### Expected behavior
Deployment to Azure webapp
### Actual behavior
The zip deploy failed after 3 times of retry
### Steps to reproduce the problem
https://docs.microsoft.com/ko-kr/java/azure/spring-framework/deploy-spring-boot-java-app-with-maven-plugin?view=azure-java-stable

[INFO] --> POST https://sktiotportaldev.azurewebsites.net/api/zipdeploy
[INFO] Accept-Encoding: gzip
[INFO] Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ik4tbEMwbi05REFMcXdodUhZbkhRNjNHZUNYYyIsImtpZCI6Ik4tbEMwbi05REFMcXdodUhZbkhRNjNHZUNYYyJ9.eyJhdWQiOiJodHRwczovL21hbmFnZW1lbnQuY29yZS53aW5kb3dzLm5ldC8iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8xZGZmNzhkMS0yODdjLTRjYmUtOWNkYS0yNDBiYjFmNTRjNDYvIiwiaWF0IjoxNTU0MDc4ODU2LCJuYmYiOjE1NTQwNzg4NTYsImV4cCI6MTU1NDA4Mjc1NiwiYWNyIjoiMSIsImFpbyI6IkFVUUF1LzhLQUFBQTNRQ1BFUWNOVnN5cXNvcDRkYjZtZ29RdGE4Qy9TZE1jTXZvVG5hODZ5YnVORFJHdmNHMXZEMGNqbXJLWnJ4YmNYUWMvOWxoVDZPNnhrNmhrSVVpa0hnPT0iLCJhbHRzZWNpZCI6IjU6OjEwMDMyMDAwMzhBOTQzQTQiLCJhbXIiOlsicHdkIl0sImFwcGlkIjoiMDRiMDc3OTUtOGRkYi00NjFhLWJiZWUtMDJmOWUxYmY3YjQ2IiwiYXBwaWRhY3IiOiIwIiwiZW1haWwiOiJ5b29ud29uLmtvQHNrLmNvbSIsImZhbWlseV9uYW1lIjoieW9vbndvbi5rb19zay5jb20jRVhUIyIsImdpdmVuX25hbWUiOiJ5b29ud29uLmtvQHNrLmNvbSIsImdyb3VwcyI6WyI3YmU3Njc3MC1kNmFiLTRlOWMtOTYwNy02NzRkNmYxZTgyZjAiLCI2MDQyMzFhYS02NjE1LTQwMTgtODMxYS04YWFkODFiMTA2ZmMiXSwiaWRwIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvN2Q0OWU5N2EtMWI5Yi00OTA3LTgxYWEtMjRmZjFkZGYwYmRhLyIsImlwYWRkciI6IjIwMy4yMzYuMy4yMjciLCJuYW1lIjoieW9vbndvbi5rbyIsIm9pZCI6ImM1OTlhZjA2LTcyMjgtNDJmNi1hNjQ0LThiYmIyMzY2OWJiYSIsInB1aWQiOiIxMDAzMjAwMDM4QjA4Qjc2Iiwic2NwIjoidXNlcl9pbXBlcnNvbmF0aW9uIiwic3ViIjoiSy1TX2pIbEdFaXJvRlNGdzdqTzNCb0hVdTdzM0VFdkZFMVZmWl9xOGFHZyIsInRpZCI6IjFkZmY3OGQxLTI4N2MtNGNiZS05Y2RhLTI0MGJiMWY1NGM0NiIsInVuaXF1ZV9uYW1lIjoieW9vbndvbi5rb0Bzay5jb20iLCJ1dGkiOiI2N2VKR05ZZVFFQzBBaFRZeG14SUFBIiwidmVyIjoiMS4wIiwid2lkcyI6WyI5Yjg5NWQ5Mi0yY2QzLTQ0YzctOWQwMi1hNmFjMmQ1ZWE1YzMiLCJjZjFjMzhlNS0zNjIxLTQwMDQtYTdjYi04Nzk2MjRkY2VkN2MiXX0.qNQ9utzSzUS8k93Z1EJjpU4JiHmRw_fa8aQ5T1LoGL9PF4uoIhMvX9UMpb_bQn6HbEUQ4JMAdmFokhcalHr2U3FhIvtPX5NyAo9GnuJ9Sn33hFXVboDjJbzATblJUUKhtqfBMGJ9bVEiFBOiMj34ovdj2T3qHIff7nR2Xqcmb6NhLWsWpjGMiy_v9cylps5ZFVgMiffnLOpS7Ygcjejkl6Tn1M5w-UEBP5oqF2Kll97lmeq1eWqvOFp6N6TOk1nG-Q_aq4645SCwaa1hlCgSYC82FX8RCroXXBrq-xvdf0OXw4Aa6lgCaaDAHYT8bfS7EvrYK-StBjMfAtNZiM7sDA
[INFO] Connection: Keep-Alive
[INFO] Content-Length: 41705793
[INFO] Content-Type: application/octet-stream
[INFO] Cookie: ARRAffinity=34a11421b10b8f6544dbd210eb4451344ffc58fd58c6c25307ae22ecb7ba506c
[INFO] Host: sktiotportaldev.azurewebsites.net
[INFO] User-Agent: azure-webapp-maven-plugin/1.4.0 installationId:6c9d2bc8f91b89624add29c0abeae7fb42bf539fa1cdb2e3e57cd668fa9bcead sessionId:7c10fd23-ec8d-4a7b-bb0f-32f82e818325
[INFO] x-ms-body-logging: false
[INFO] x-ms-client-request-id: 32a7de1c-6559-4a50-a13b-c63ba50c3a62
[INFO] <-- 404   https://sktiotportaldev.azurewebsites.net/api/zipdeploy (3286 ms, unknown-length body)
[INFO] Content-Type: application/json;charset=UTF-8
[INFO] Date: Mon, 01 Apr 2019 00:48:10 GMT
[INFO] Transfer-Encoding: chunked
[DEBUG] Exception occurred when deploying the zip package: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `com.microsoft.azure.CloudError` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('Not Found')
 at [Source: (String)""Not Found""; line: 1, column: 1], retrying immediately (3/3)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:36 min
[INFO] Finished at: 2019-04-01T09:48:10+09:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.microsoft.azure:azure-webapp-maven-plugin:1.4.0:deploy (default-cli) on project iot-portal: The zip deploy failed after 3 times of retry. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.microsoft.azure:azure-webapp-maven-plugin:1.4.0:deploy (default-cli) on project iot-portal: The zip deploy failed after 3 times of retry.

**Comment by Flanker32** [comment]
@ggthename Thanks for your report, but i can't repro this issue, could you please share the project you meet this issue? Or you may try schema V2 to see whether the issue exist, you may refer [here](https://github.com/Microsoft/azure-maven-plugins/blob/develop/docs/web-app-samples.md) for V2 schema information.

**Comment by JasonFreeberg** [comment]
This could be related to recent issue. Hard to tell because you are using an older version of the plugin. The newer versions have improved logging.

# Mitigation Instructions

Hi everyone, our engineering team is aware of the problem and we are actively working on a fix. To mitigate the problem, please deploy your JAR or WAR using ZIP-deploy or WAR-deploy respectively ([documentation here](https://docs.microsoft.com/en-us/azure/app-service/deploy-zip
)).

We do **not** advise deploying JARs or WARs via FTP.

**Comment by ggthename** [comment]
@Flanker32 Thank you, I solved the problem in a different way [spring guide](https://spring.io/guides/gs/spring-boot-for-azure/)

I'm not sure about the exact cause but I guess it is probably related to "Configure Maven to use your Azure service principal"
