### ISSUE TITLE
Error occurs when triggering triggers after the local run within JDK 11

### ISSUE THREAD

**Issue by ZhengJun003** [microsoft/azure-maven-plugins#613]
### Plugin name and version
```
JDK 11
Maven Plugin for Azure functions 1.3.2-SNAPSHOT
```
### Actual behavior
On the Mac platform, the error occurs when triggering thiese triggers

- Http Trigger
- Blob Trigger
- Eventhub Trigger
- ServiceBusQueue Trigger
- ServiceBusTopic Trigger
- Cosmos DB Trigger

On the Windows platform, the error occurs when triggering **blob trigger**

![image](https://user-images.githubusercontent.com/41051257/55547231-70c52f00-5703-11e9-9b8c-f6e82b74c066.png)

### Steps to reproduce the problem

1. Generate an Azure Functions archetype
2. Add the corresponding trigger function
3. Run function host locally
4. Trigger functions

**Comment by Flanker32** [comment]
Trace in https://github.com/Azure/azure-functions-core-tools/issues/1303

**Comment by Flanker32** [comment]
Function core tools has released the java 11 support, close this issue.
