### ISSUE TITLE
Wrong Java version prompt message

### ISSUE THREAD

**Issue by ZhengJun003** [Microsoft/azure-maven-plugins#614]
### Plugin name and version
```
JDK 11
Maven Plugin for Azure functions 1.3.2-SNAPSHOT
```
### Actual behavior
There is a JDK version warning when running maven plugin for Azure Functions goals.
The actual situation is that we support JDK 11 now.

![image](https://user-images.githubusercontent.com/41051257/55548765-c9e29200-5706-11e9-9b73-50102ba662ae.png)

**Comment by JasonFreeberg** [comment]
Hi @ZhengJun003, you are seeing this message because Azure Functions does not currently support Java 11. (@jeffhollan @asavaritayal)

**Comment by ZhengJun003** [comment]
Maven Plugin for Azure functions does not support Java 11 now, so close issue.
