### ISSUE TITLE
Provide JDK 11 Support for Azure Function Apps

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/azure-maven-plugins#617]
_originally filed by @cheenamalhotra in https://github.com/Microsoft/vscode-azurefunctions/issues/1181_

Azure Functions do not compile with JDK 11, please provide support for the same.

Repro steps:1.2.Action: azureFunctions.createFunctionError type: ErrorError Message: Failed to run mvn command. Check output window for more details.Version: 0.16.0OS: win32VS Code Version: 1.33.1<details><summary>Call Stack</summary>```Object.<anonymous> (dist/extension.bundle.js:1:532851)Generator.next (<anonymous>)o (dist/extension.bundle.js:1:531293)```</details>

Maven Error: Failed to execute goal com.microsoft.azure:azure-functions-maven-plugin:1.3.1:add (default-cli) on project Start_JDBC_DW: Local JDK version 11.0.2 does not meet the requirement of the Maven plugin for Azure Functions. The supported version is JDK 8 -> [Help 1]

**Comment by Flanker32** [comment]
@EricJizbaMSFT  This has been fixed in #610, now maven plugin will show a warning instead of throw exception when invoked with Java11.

**Comment by Flanker32** [comment]
Function plugin 1.3.2 has released, which could work with Java 11.
