### ISSUE TITLE
Deploy with existing app setting overwrites value in portal with blank

### ISSUE THREAD

**Issue by josh-roberts-phision** [microsoft/azure-maven-plugins#618]
azure-functions-maven-plugin - 1.3.1

`
        <configuration>
          <resourceGroup>${functionResourceGroup}</resourceGroup>
          <appName>${functionAppName}</appName>
          <region>${functionAppRegion}</region>
          <appSettings>
            <property>
              <name>FUNCTIONS_EXTENSION_VERSION</name>
              <value>beta</value>
            </property>
            <property>
              <name>MSDEPLOY_RENAME_LOCKED_FILES</name>
              <value>1</value>
            </property>
            <property>
              <name>TRANSACTIONS_EVENT_HUB_CONNECTION_STRING</name>
              <value>${TRANSACTIONS_EVENT_HUB_CONNECTION_STRING}</value>
            </property>
          </appSettings>
        </configuration>
        <executions>
          <execution>
            <id>package-functions</id>
            <goals>
              <goal>package</goal>
            </goals>
          </execution>
        </executions>
`

`
@FunctionName("myFunction")
public Object run(@EventHubTrigger(name = "myEvent",
eventHubName = "myEventHub",
connection = "TRANSACTIONS_EVENT_HUB_CONNECTION_STRING",
cardinality= Cardinality.ONE,
dataType="binary")
`
### Expected behavior
App setting TRANSACTIONS_EVENT_HUB_CONNECTION_STRING is set in the portal, value of EventHub Connection on function should remain the name of the environment variable

### Actual behavior
The EventHub Connection is blank, the value of TRANSACTIONS_EVENT_HUB_CONNECTION_STRING in App Settings is also blank after a deploy

### Steps to reproduce the problem
mvn clean package
mvn azure-functions:deploy

**Comment by Flanker32** [comment]
@josh-roberts-phision Thanks for your report and sorry for the delay. I tried with function plugin 1.3.2 and it works, I could see TRANSACTIONS_EVENT_HUB_CONNECTION_STRING  after deployed with value. Is the property set properly? Or cloud you please share the pom file?
