### ISSUE TITLE
azure-webapp:config with default choices creates bad config

### ISSUE THREAD

**Issue by JasonFreeberg** [Microsoft/azure-maven-plugins#627]
### Plugin name and version
Azure Webapp Maven Plugin v1.5.3

### Plugin configuration in your `pom.xml`
Starting config:

```xml
<plugin> 
        <groupId>com.microsoft.azure</groupId>  
        <artifactId>azure-webapp-maven-plugin</artifactId>  
        <!-- check Maven Central for the latest version -->  
        <version>1.5.3</version>  
</plugin>
```

### Expected behavior

I ran the `mvn azure-webapp:config` command with the default options (did not enter an index, I just hit the return key on each prompt). It should create a Linux app with JRE 8. 

### Actual behavior

This is the config generated by the `mvn azure-webapp:config` command.  When I later run `mvn azure-webapp:deploy` with this config, it creates an App Service that has a Tomcat `webapps/ROOT/` directory. When I later deploy my `app.jar`, the app does not start and I get a 500 error.

```xml
<plugin> 
  <groupId>com.microsoft.azure</groupId>  
  <artifactId>azure-webapp-maven-plugin</artifactId>  
  <!-- check Maven Central for the latest version -->  
  <version>1.5.3</version>  
  <configuration>
    <schemaVersion>V2</schemaVersion>
    <resourceGroup>maven-deployment-1555456770537-rg</resourceGroup>
    <appName>maven-deployment-1555456770537</appName>
    <region>westeurope</region>
    <pricingTier>P1V2</pricingTier>
    <runtime>
      <os>linux</os>
      <javaVersion>jre8</javaVersion>
      <webContainer>jre8</webContainer>
    </runtime>
    <deployment>
      <resources>
        <resource>
          <directory>${project.basedir}/target</directory>
          <includes>
            <include>*.jar</include>
          </includes>
        </resource>
      </resources>
    </deployment>
  </configuration>
</plugin>
```

I think the problem is the `<webContainer>` tag. It should probably be blank (or even better--not there).

### Steps to reproduce the problem

I was working on a tutorial for App Service. [Instructions are here.](https://github.com/Azure-Samples/java-on-app-service/tree/master/maven-deployment)

**Comment by JasonFreeberg** [comment]
Here is the terminal output that generated the XML above.

```terminal
PS C:\Users\jafreebe\Desktop\java-on-app-service\maven-deployment\initial> mvn azure-webapp:config-deployment\initial>
PS C:\Users\jafreebe\Desktop\java-on-app-service\maven-deployment\initial> mvn azure-webapp:config          vice:maven-deployment >--
[INFO] Scanning for projects...
[INFO]
[INFO] --< com.microsoft.azure.samples.java-on-app-service:maven-deployment >--[INFO] Building maven-deployment 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO][INFO] --- azure-webapp-maven-plugin:1.5.3:config (default-cli) @ maven-deployment ---
[WARNING] The plugin may not work if you change the os of an existing webapp.
Define value for OS(Default: Linux):
1. linux [*]
2. windows
3. docker
Enter index to use:
Define value for runtimeStack(Default: jre8):
1. tomcat 8.5
2. tomcat 9.0
3. jre8 [*]
4. wildfly 14
Enter index to use:
Please confirm webapp properties
AppName : maven-deployment-1555456770537
ResourceGroup : maven-deployment-1555456770537-rg
Region : westeurope
PricingTier : Premium_P1V2
OS : Linux
RuntimeStack : JAVA 8-jre8
Deploy to slot : false
Confirm (Y/N)? :
[INFO] Saving configuration to pom.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 59.459 s
[INFO] Finished at: 2019-04-16T16:19:55-07:00
[INFO] ------------------------------------------------------------------------
```

**Comment by JasonFreeberg** [comment]
Notice in the image below that the site has a `default.jar` for the JRE parking page, **and** the Tomcat parking page JSP's under `webapps/ROOT/`. The site config confirms that the site is a Java 8 SE image (from the config: `"linuxFxVersion": "JAVA|8-jre8"`) Very strange!

![image](https://user-images.githubusercontent.com/18747768/56251074-f8496100-6066-11e9-80f3-17b2ece86026.png)

**Comment by JasonFreeberg** [comment]
If I use this configuration I get the same issue.

```xml
<runtime>
    <os>Linux</os>
    <javaVersion>jre8</javaVersion>
    <webContainer></webContainer>
</runtime> 
```

**Comment by Flanker32** [comment]
@JasonFreeberg App service JavaSE image do contains folder `webapps/ROOT/` and `default.jar`, the `default.jar` will be execute when user didn't upload their applications, here is a snapshot of an empty linux app service.
![image](https://user-images.githubusercontent.com/12445236/56261404-782a0680-610d-11e9-99d8-dec822221a66.png)

To run jar application like spring-boot project, please also set port forwarding in configuration, as app service only open port 80 for webapp, here is an example 
```
<build> 
    <finalName>app</finalName> <!-- Set name to app.jar -->
    <plugins> 
      <plugin> 
        <groupId>com.microsoft.azure</groupId>  
        <artifactId>azure-webapp-maven-plugin</artifactId>  
        <version>1.5.4</version>  
        <configuration>
          ...
          <appSettings>
              <!-- Set port for app service-->
              <property>
                  <name>PORT</name>
                  <value>8080</value>
              </property>
          </appSettings>
          ...
      </plugin>  
```

Besides, app service will take some time to recycle old web container and run new upload artifact, it will take about 5 minutes, and app service team is working on this issue, you may run `ps -al` in ssh to see whether `app.jar` is executed

**Comment by Flanker32** [comment]
Today every time we publish a new jar, the container in App Service will be recycled. It will take some time and then the web app could be reached. Ideally, only the JVM should be restarted without recycling the whole container. This functionality is expected to arrive by the end of Jun.

**Comment by JasonFreeberg** [comment]
@Flanker32 -- We can close this. Thanks Hanxiao
