### ISSUE TITLE
deployment will not be conducted in the current, active, default subscription using Cloud Shell

### ISSUE THREAD

**Issue by yucwan** [microsoft/azure-maven-plugins#628]
### Plugin name and version
Maven Plugin for Azure Web Apps 1.5.4

### Plugin configuration in your `pom.xml`
<plugins>
    
    
    
    <plugin>
        <groupId>com.microsoft.azure</groupId>
        <artifactId>azure-webapp-maven-plugin</artifactId>
        <version>1.5.4</version>
        <configuration>
            
            <schemaVersion>v2</schemaVersion>
            
            <resourceGroup>${RESOURCEGROUP_NAME}</resourceGroup>
            <appName>${WEBAPP_NAME}</appName>
            <region>${REGION}</region>
   
            
            <runtime>
                <os>linux</os>
                <javaVersion>jre8</javaVersion>
                <webContainer>tomcat 8.5</webContainer>
            </runtime> 
            <deployment>
                <resources>
                    <resource>
                        <directory>${project.basedir}/target</directory>
                        <includes>
                            <include>*.war</include>
                        </includes>
                    </resource>
                </resources>
            </deployment>
        </configuration>
    </plugin>
</plugins>

### Expected behavior
Deploy web app in the current subscription that is set up in **az account show**.

### Actual behavior
Tying to deploy in the subscription at the top of **az account list**.

### Steps to reproduce the problem
follow the Quickstart at:
https://docs.microsoft.com/en-us/azure/app-service/containers/quickstart-java
deployment will not be conducted in the right subscription using Cloud Shell if you have multiple subscriptions.

### Workaround
in plugin configuration, add:
``` xml
<subscriptionId>${SUBSCRIPTIONID}</subscriptionId>
```

**Comment by yucwan** [comment]
#289

**Comment by Flanker32** [comment]
Fixed om #665
