### ISSUE TITLE
Document for deploymentslot is confusing

### ISSUE THREAD

**Issue by jdneo** [microsoft/azure-maven-plugins#648]
There is a setting: `configurationSource`. But it's not covered in README.

The explaination could be found here: https://github.com/microsoft/azure-maven-plugins/blob/f6d98df6fd9259400cc3727cc48916a32a77c460/azure-webapp-maven-plugin/src/main/java/com/microsoft/azure/maven/webapp/configuration/ConfigurationSourceType.java#L13-L18

**Comment by wangmingliang-ms** [comment]
it's covered in the help doc, available by
`mvn azure-webapp:help -Ddetail=true -Dgoal=config`
