### ISSUE TITLE
azure-webapp:config, can't generate configuration

### ISSUE THREAD

**Issue by sallyur** [microsoft/azure-maven-plugins#655]
### Plugin name and version
```
Maven plugin for Azure webapps
Version: 1.6.1-SNAPSHOT
```
### Plugin configuration in your `pom.xml`
```
<plugin> 
        <groupId>com.microsoft.azure</groupId>  
        <artifactId>azure-webapp-maven-plugin</artifactId>  
        <version>1.6.1-SNAPSHOT</version>  
</plugin>
```
### Expected behavior
It can generate successfully.
### Actual behavior
Build failer: java.lang.NullPointerException
![image](https://user-images.githubusercontent.com/28860891/58157098-37905080-7caa-11e9-822e-59b97134ee66.png)

### Steps to reproduce the problem

1. Prepare a webapp maven project with neweast maven plugin version
2. Set the pom file as above
3. Run "mvn azure-webapp:config"
4. Type "Y" to confirm

**Comment by Flanker32** [comment]
Fixed in #656
