### ISSUE TITLE
[Functions] Use azure-functions-java-library from extension bundles

### ISSUE THREAD

**Issue by pragnagopa** [microsoft/azure-maven-plugins#658]
### Plugin name and version
Azure Functions

[azure-functions-extension-bundles](https://github.com/Azure/azure-functions-extension-bundles) will start including azure-functions-java-library that is compatible with a version of extension bundle.

If `host.json`  includes extension bundles, maven plugin should use java library that is part of the bundle to ensure compatibility with the extensions functions host uses.

cc: @soninaren @jeffhollan @mattchenderson

**Comment by Flanker32** [comment]
@pragnagopa  So functions-extension-bundles will release to maven central and the maven plugin could change dependency from java-library to extension bundles? Besides, shall we change the dependency of archetype?

**Comment by pragnagopa** [comment]
@Flanker32  - we do not have the design for this yet. Idea is to include version mapping information in the extension bundles, for example [1.0.0,2.0.0) for extension bundle will map to 1.* of azure-functions-java-library

maven plugin needs to be updated to pull the right version of the azure-functions-java-library depending on the extension bundle version specified by the user in `host.json` file

**Comment by Flanker32** [comment]
@pragnagopa Do you mean we should remove the dependency from function project and maven plugin will read the `host.json` and add the dependency? Does maven support this feature and what could use benefit from it?

**Comment by pragnagopa** [comment]
cc @amamounelsayed
@soninaren will share design on how to support version of extension bundles  across multiple languages. Idea here is to ship bundles for each binding that will include packages for each language.

Note: This is a future work item and design is not ready yet.
