### ISSUE TITLE
The hint for webapp:config is confusing

### ISSUE THREAD

**Issue by andxu** [microsoft/azure-maven-plugins#667]
Define value for javaVersion(Default: jre8):
1. jre8 [*]
2. java11
Enter index to use:
Define value for runtimeStack(Default: TOMCAT 8.5):
1. TOMCAT 9.0
2. jre8
3. TOMCAT 8.5 [*]
4. WILDFLY 14

javaVersion : jre8 and java 11? why not **Java 8 and Java 11**?
runtimeStack: the order should be sorted, so TOMCAT 9.5 and 8.5 will be conjunct, and all the value should be case consistent: jre8 and TOMCAT is weird , and you should also have some description about these options, user will **NOT** know what does jre8 runtime mean.

**Comment by Flanker32** [comment]
Fixed in #675
