### ISSUE TITLE
Provide an Azure Functions plugin for Gradle

### ISSUE THREAD

**Issue by OlgaMaciaszek** [microsoft/azure-maven-plugins#671]
### Gradle equivalent of Azure Functions Maven plugin

Please consider providing a gradle equivalent of your Azure Functions plugin to allow easily deploying and running Gradle-built function projects (such as Spring Cloud Function projects) on Azure.

**Comment by Flanker32** [comment]
@OlgaMaciaszek Thanks for your advice, Gradle is an import java package manager and but it is not in our plan as the lack of resources, it would be better if the community could contribute the codes and we are willing to offer helps.

**Comment by opticyclic** [comment]
There is this https://github.com/lenala/azure-gradle-plugins

**Comment by yucwan** [comment]
@OlgaMaciaszek Thanks for your advice! As product team owning 3rd party java tooling for Azure, we are indeed considering this. Would you mind provide us more detail about your scenario or specific feature request using Maven/Gradle plugin with Azure Functions? We do need to understand user's need in the first place. You can also reach us directly at: azure-java-tools@microsoft.com

**Comment by OlgaMaciaszek** [comment]
Hi @yucwan Thanks, will discuss it with the team and get back to you.

**Comment by Tetradeus** [comment]
Hello guys, any news on this one?

**Comment by andxu** [comment]
I am working on gradle plugin for functions and make some progresses these days, you may expect it soon(1 month or longer,  I cannot guarantee when it will be released ), send an email to azure-java-tools@microsoft.com if you want to try our early beta version.

**Comment by gmvg** [comment]
Hi guys, Its been a month from last update, any news on this?

**Comment by Flanker32** [comment]
@gmvy Thanks for your support, please follow this [document](https://github.com/microsoft/azure-maven-plugins/wiki/Azure-Functions-Gradle-Plugin-(Preview)) to get the latest version.

**Comment by spdeepak** [comment]
@Flanker32 Can this be made compatible for Java 11?

**Comment by Flanker32** [comment]
> @Flanker32 Can this be made compatible for Java 11?

Java function still not support Java 11 for now, our service team is working on this item, will update you once there are updates.

**Comment by andxu** [comment]
Done, 
see https://plugins.gradle.org/plugin/com.microsoft.azure.azurefunctions and  https://github.com/microsoft/azure-maven-plugins/wiki/Azure-Functions-Gradle-Plugin-(Preview)

**Comment by yucwan** [comment]
Checkout the latest doc at: https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-java-maven?pivots=java-build-tools-gradle

and it's opensourced at: https://github.com/microsoft/azure-gradle-plugins

**Comment by spdeepak** [comment]
@andxu I guess it would not work for JDK 11, right?

**Comment by yucwan** [comment]
@spdeepak, Azure Functions does not support Java 11 for now, they are working on it. Once supported, we will enable it on Azure Plugins for Maven/Gradle, VS Code and IntelliJ.
