### ISSUE TITLE
Cannot show warning for some errors in the configuration when "webapp:config" 

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-maven-plugins#681]
### Plugin name and version
azure-webapp-maven-plugin 1.7.0

### Expected behavior
This kind of warning behavior should be unified.

- For the necessary configuration:
 region-  should have a warning if it has an error
- For deployment slots:
 If there is a slot configuration in the pom file, should check the configuration and report an error if it has an error

### Actual behavior
Some of the necessary configurations can display warnings, some can't when webapp:config
1. Application:
   - appname - Y
   - resourcegroup - Y
   - **region - N**

2. Runtime
   - Miss all runtime configurations - N (make sense)
   - Miss one of the Runtime setting - Y

3. Deployment
   - Miss all slot configurations - N (make sense)
   -  **Miss one of the slot setting - N**

Y - have warning
N - don't have warning

**Comment by bsaby** [comment]
@Flanker32 

- Test passed in deployment slot setting validation.
- Test **failed** in Application-region validation.

When deploying to a web app with a new plan, the region is required in the pom file.
![image](https://user-images.githubusercontent.com/22470312/60070795-8f5b2500-974a-11e9-85a3-db3016a96077.png)

**Comment by Flanker32** [comment]
> @Flanker32
> 
> * Test passed in deployment slot setting validation.
> * Test **failed** in Application-region validation.
> 
> When deploying to a web app with a new plan, the region is required in the pom file.
> ![image](https://user-images.githubusercontent.com/22470312/60070795-8f5b2500-974a-11e9-85a3-db3016a96077.png)

@bsaby Users could deploy their app service with to existing app service plan with no region configuration, so `<region>` could be miss in configuration and there is no warning about it.

**Comment by bsaby** [comment]
Close this issue since that no warning for the missing region is by design.
