### ISSUE TITLE
Help for update version of dependencies azure-functions-maven-plugin

### ISSUE THREAD

**Issue by hung1806vn** [microsoft/azure-maven-plugins#687]
### Plugin name and version
azure-functions-maven-plugin
### Plugin configuration in your `pom.xml`
           <plugin>
                <groupId>com.microsoft.azure</groupId>
                <artifactId>azure-functions-maven-plugin</artifactId>
                <configuration>
                    <resourceGroup>${functionResourceGroup}</resourceGroup>
                    <appName>${functionAppName}</appName>
                    <region>${functionAppRegion}</region>
                    <appSettings>
                        
                        <property>
                            <name>WEBSITE_RUN_FROM_PACKAGE</name>
                            <value>1</value>
                        </property>
                        <property>
                            <name>FUNCTIONS_EXTENSION_VERSION</name>
                            <value>~1</value>
                        </property>
                        <property>
                            <name>FUNCTIONS_WORKER_RUNTIME</name>
                            <value>java</value>
                        </property>
                    </appSettings>
                </configuration>
                <executions>
                    <execution>
                        <id>package-functions</id>
                        <goals>
                            <goal>package</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
### Expected behavior
I want to update version of dependencies of this plugins used
### Actual behavior
Old dependencies that violate CVE dependencies check

**Comment by Flanker32** [comment]
@hung1806vn Thanks for your feedback, could you please tell us the version of the function plugin and which dependency violate CVE check?

**Comment by hung1806vn** [comment]
@Flanker32 Thanks in advance for your support. There's my dependencies check report help me review it
![Capture](https://user-images.githubusercontent.com/35421442/60008212-da6b2e80-969d-11e9-91d1-c53c8825bf24.PNG)

**Comment by Flanker32** [comment]
@hung1806vn Here is the dependency tree of function maven plugin
``` log
[INFO] |  +- com.microsoft.azure:azure:jar:1.21.0:compile
[INFO] |  |  +- com.microsoft.azure:azure-client-runtime:jar:1.6.4:compile
[INFO] |  |  |  \- com.microsoft.rest:client-runtime:jar:1.6.4:compile
[INFO] |  |  |     +- com.squareup.retrofit2:retrofit:jar:2.4.0:compile
[INFO] |  |  |     +- com.squareup.okhttp3:okhttp:jar:3.11.0:compile
[INFO] |  |  |     |  \- com.squareup.okio:okio:jar:1.14.0:compile
[INFO] |  |  |     +- com.squareup.okhttp3:logging-interceptor:jar:3.11.0:compile
[INFO] |  |  |     +- com.squareup.okhttp3:okhttp-urlconnection:jar:3.11.0:compile
[INFO] |  |  |     +- com.squareup.retrofit2:converter-jackson:jar:2.4.0:compile
[INFO] |  |  |     |  \- com.fasterxml.jackson.core:jackson-databind:jar:2.9.4:compile
[INFO] |  |  |     +- com.fasterxml.jackson.datatype:jackson-datatype-joda:jar:2.9.4:compile
[INFO] |  |  |     |  \- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.0:compile
[INFO] |  |  |     \- com.squareup.retrofit2:adapter-rxjava:jar:2.4.0:compile
```
It seems that all dependencies violate CVE checks belongs to [azure-client-runtime](https://github.com/Azure/autorest-clientruntime-for-java), and these dependencies didn't update in their latest release([link of pom](https://github.com/Azure/autorest-clientruntime-for-java/blob/v1.6.9/pom.xml)), please open an issue there and we will tract it.

**Comment by hung1806vn** [comment]
Thank you for your support. Waiting the update

**Comment by andxu** [comment]
Invalid since we upgraded to track2
