### ISSUE TITLE
[WebApp] Consider a 2.x branch for v2 config cheme

### ISSUE THREAD

**Issue by brunoborges** [microsoft/azure-maven-plugins#688]
### Plugin name and version
azure-webapp

### Description
Currently, the 1.x branch supports both V1 and V2 config schemes.

It would be better to branch out a 2.x version of the plugin to only support V2 config scheme, and stop the development of 1.x with only bug fixes. 

A complete rewrite of the plugin should also be considered.

**Comment by andxu** [comment]
v1 is already deprecated
