### ISSUE TITLE
Document error display label <region>

### ISSUE THREAD

**Issue by EricZhangzf** [microsoft/azure-maven-plugins#689]
### Plugin name 
azure-webapp-maven-plugin
### Expected behavior
The Required of <region> is false and the default value is west_europe in Description.
### Actual behavior
The Required of <region> is true and the default value is westus in Description.
![image](https://user-images.githubusercontent.com/44559777/60071604-4eb0db00-974d-11e9-9abe-0973dfa39ab3.png)

### Steps to reproduce the problem
https://github.com/microsoft/azure-maven-plugins/blob/master/azure-webapp-maven-plugin/README.md#azure-webappdeploy

**Comment by andxu** [comment]
@Flanker32 Please take a look at this issue.

**Comment by Flanker32** [comment]
FIxed in #841
