### ISSUE TITLE
mvn azure-webapp:deploy does not generate the war file after a mvn clean - deployment fails

### ISSUE THREAD

**Issue by kazosman** [microsoft/azure-maven-plugins#719]
### Plugin name and version
com.microsoft.azure azure-webapp-maven-plugin 1.6

### Plugin configuration in your `pom.xml`
<plugin>
        <groupId>com.microsoft.azure</groupId>
        <artifactId>azure-webapp-maven-plugin</artifactId>
        <version>1.6.0</version>
        <configuration>
          <schemaVersion>v2</schemaVersion>
          <resourceGroup>${RESOURCEGROUP_NAME}</resourceGroup>
          <appName>${project.artifactId}</appName>
          <region>East US 2</region>
          <pricingTier>B1</pricingTier>
          <runtime>
            <os>linux</os>
            <javaVersion>jre8</javaVersion>
            <webContainer>tomcat 8.5</webContainer>
          </runtime>
          
          <appSettings>
            <property>
              <name>JAVA_OPTS</name>
              <value>-Dserver.port=8080</value>
            </property>
            
            <property>
              <name>JAVA_OPTS</name>
              <value>-Xmx512m -Xms512m</value>
            </property>
          </appSettings>
          <deployment>
            <resources>
              <resource>
                <directory>${project.basedir}/target</directory>
                <includes>
                  <include>*.war</include>
                </includes>
              </resource>
            </resources>
          </deployment>
        </configuration>
      </plugin>

### Expected behavior
After running mvn clean and mvn azure-webapp:deploy it should generate the war file in:
/target/azure-webapp/... before deploying the war file to Azure App Service

### Actual behavior
running mvn azure-webapp:deploy after a mvn clean does not regenerate the war so the deployment fails:
There is no artifact to deploy in staging directory: '/opt/ML/workspace2/mw-spring-boot/target/azure-webapp/
It generates the war file the first time and tries to update it for subsequent builds but if a change is made to the codebase such as deleting a Java class then you need to run a mvn clean which removes the azure-webapp directory and azure-webapp:deploy does not rebuild the war file.

### Steps to reproduce the problem
Create a spring boot war project
deploy to azure using the azure-webapp:deploy command - deploys successfully
Remove a java class from the project 
Run a mvn clean
Run the azure-webapp:deploy - it does not generate the output directory "azure-webapp" in target so the deployment will fail.

I also tried with mvn clean, followed by mvn package followed by azure-webapp:deploy
Also tried with mvn clean install before deploy

At present the only way to get around this is to manually make changes to the war file

I followed the steps at the following link:
https://docs.microsoft.com/en-gb/java/azure/spring-framework/deploy-spring-boot-java-app-with-maven-plugin?view=azure-java-stable

Am I missing a step which is not in the above link?

**Comment by Flanker32** [comment]
@kazosman Thanks for your report, `mvn azure-webapp:deploy` will not generate war files, you need to  execute `mvn package` (usually we use `mvn clean package`) before deploy.

**Comment by Flanker32** [comment]
> I also tried with mvn clean, followed by mvn package followed by azure-webapp:deploy
Also tried with mvn clean install before deploy
DId you means you execute `mvn package` but no war file was generated? If so, is there any error message print on console? Or could you please share the project?

**Comment by kazosman** [comment]
Hi
Thanks for your quick reply

mvn package does generates the war file in target dir but the azure deploy process is looking for the war file in:
/target/azure-webapp/.../mw.war
That war file is not generated by the mvn package command

The error I get is:
There is no artifact to deploy in staging directory: '/opt/ML/workspace2/mw-spring-boot/target/azure-webapp/
So this is not using the generated war file in the target directory.

I have attached a screenshot which shows the "azure-webapp" directory the azure deploy process is looking in but when you run clean and package this directory does not get created so the azure deploy task cannot find the war file in there.  
Is there a way to get the azure deploy to use the war file that is directly in the target dir?

![azure](https://user-images.githubusercontent.com/38760282/62696404-3f6db000-b9d0-11e9-8513-0376abf8850a.png)

**Comment by kazosman** [comment]
I have managed to get it working - I deleted the whole project and checked it out of GIT and now the azure-webapp directory is being created during the azure deploy mvn task

Thank you
