### ISSUE TITLE
Cryptic Maven null pointer error when deploying function with configured Azure principal

### ISSUE THREAD

**Issue by yveszoundi** [Microsoft/azure-maven-plugins#73]
### Plugin name and version
I'm using the _azure-functions-maven-plugin_ , version _0.1.9-SNAPSHOT_ (cloned from github).

### Plugin configuration in your `pom.xml`
The main "non-standard" section is the _authentication_ tag for picking up Azure principal credentials from Maven settings (settings.xml). 
```xml
<plugin>
  <groupId>com.microsoft.azure</groupId>
  <artifactId>azure-functions-maven-plugin</artifactId>
  <configuration>
   <authentication>
     <serverId>azure-auth</serverId>
    </authentication>
    <resourceGroup>MY_CONFIGURED_RESOURCE_GROUP_IN_AZURE</resourceGroup>
    <appName>${functionAppName}</appName>
    <region>${functionAppRegion}</region>
    <appSettings>
      <property>
        <name>FUNCTIONS_EXTENSION_VERSION</name>
        <value>beta</value>
      </property>
    </appSettings>
  </configuration>
  <executions>
    <execution>
      <id>package-functions</id>
      <goals>
        <goal>package</goal>
      </goals>
    </execution>
  </executions>
</plugin>
```
### Expected behavior
1. In a previously working Azure function project (deployed with Maven), switch from Azure CLI login (_az login_) to a configured Azure principal (https://docs.microsoft.com/en-us/java/azure/spring-framework/deploy-spring-boot-java-app-with-maven-plugin#configure-maven-to-use-your-azure-service-principal).
2. The deployment of the java function should be successful after required changes(_pom.xml_ and user _settings.xml_ changes). This should behave the same as after using the Azure CLI tools (_az login_ followed by _mvn azure-functions:deploy_)

### Actual behavior
The deployment fails using _mvn azure-functions:deploy_, with a cryptic null pointer exception

![screenshot from 2017-12-28 11-04-17](https://user-images.githubusercontent.com/5206067/34415879-f1046714-ebbe-11e7-9ea8-1bf1fdb09e4d.png)

### Steps to reproduce the problem
1. Create a simple java function Maven project by following the official tutorial: https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-java-maven
2. Create a service principal per official tutorial, for Maven usage
https://docs.microsoft.com/en-us/java/azure/spring-framework/deploy-spring-boot-java-app-with-maven-plugin#configure-maven-to-use-your-azure-service-principal
3. Notice that there's a cryptic null pointer exception (same exception as per first comment for the article at https://docs.microsoft.com/en-us/java/azure/spring-framework/deploy-spring-boot-java-app-with-maven-plugin)

**Comment by jdneo** [comment]
Hi @yveszoundi.

This issue is caused by a bug in one lib we used in the  dependency. We have added a work-around into the plugin. You can have a try if you want. The following command might help:
```
git clone https://github.com/Microsoft/azure-maven-plugins.git

cd azure-maven-plugins

mvn clean install -DskipTests
```
Then change your function plugin version to 0.1.10-SNAPSHOT.

Thanks.

**Comment by yveszoundi** [comment]
Thanks @jdneo
