### ISSUE TITLE
Config does not support lowercase characters

### ISSUE THREAD

**Issue by EricZhangzf** [microsoft/azure-maven-plugins#745]
### Plugin name and version
`Maven plugin for azure webapps`
`Version: 1.7.0`
### Plugin configuration in your `pom.xml`
```
  <build>
    <finalName>helloworld2</finalName>
    <plugins>
    <plugin>
        <groupId>com.microsoft.azure</groupId>
        <artifactId>azure-webapp-maven-plugin</artifactId>
        <version>1.7.0</version>
        <configuration>
            <schemaVersion>v2</schemaVersion>
            <resourceGroup>eric816gp</resourceGroup>
            <appName>eric816webapp</appName>
            <region>eastus</region>
   
            <runtime>
                <os>linux</os>
                <javaVersion>jre8</javaVersion>
                <webContainer>tomcat 8.5</webContainer>
            </runtime> 
            <deployment>
                <resources>
                    <resource>
                        <directory>${project.basedir}/target</directory>
                        <includes>
                            <include>*.war</include>
                        </includes>
                    </resource>
                </resources>
            </deployment>
        </configuration>
    </plugin>
</plugins>
  </build>
```
### Expected behavior
Can config successfully without no warning.
### Actual behavior
Show a warning"Config only support V2 schema"
### Steps to reproduce the problem
1. Run: mvn archetype:generate -DgroupId=example.demo -DartifactId=helloworld -DarchetypeArtifactId=maven-archetype-webapp 
2. Set the pom file as above
3. Run: mvn azure-webapp:config

**Comment by andxu** [comment]
@EricZhangzf can you verify if this issue is resolved?

**Comment by EricZhangzf** [comment]
@andxu I have tested it, but found an issue.
When v2 is uppercase in `<schemaVersion>V2</schemaVersion>`, config success, 
![image](https://user-images.githubusercontent.com/44559777/65743358-c57fba80-e126-11e9-9bd7-a201640f8a37.png)

when v2 in `<schemaVersion>V2</schemaVersion>` is lowercase, show warning.
![image](https://user-images.githubusercontent.com/44559777/65743391-ed6f1e00-e126-11e9-9d1b-2bc1677b6221.png)

**Comment by Flanker32** [comment]
@EricZhangzf Please verify this issue with webapp plugin 1.7.1-SNAPSHOT, you may clone the repo and `mvn install` to get the build

**Comment by EricZhangzf** [comment]
After change version 1.7.1-SNAPSHOT, Test pass.
Thanks.
