### ISSUE TITLE
Error message is incorrect

### ISSUE THREAD

**Issue by ZhengJun003** [microsoft/azure-maven-plugins#753]
### Plugin name and version
```
azure spring maven plugin
0.0.1-SNAPSHOT
```
### Plugin configuration in your `pom.xml`
```
      <plugin>
        <groupId>com.microsoft.azure</groupId>
        <artifactId>azure-spring-maven-plugin</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <configuration>
          <subscriptionId>b46590cb-a111-4b84-935f-c305aaf1f424</subscriptionId>
          <clusterName>hanli-spring-cluster</clusterName>
          <appName>harry-pet-1</appName>
          <isPublic>true</isPublic>
          <deployment>
            <deploymentName>deploy2</deploymentName>
            <cpu>1</cpu>
            <memoryInGB>2</memoryInGB>
            <instanceCount>1</instanceCount>
            <jvmOptions>-Xmx1G</jvmOptions>
          </deployment>
        </configuration>
      </plugin>
```

### Actual behavior
![image](https://user-images.githubusercontent.com/41051257/63411173-92f7e900-c427-11e9-9789-fd59ad6b8605.png)

### Steps to reproduce the problem
1. Clone and open spring-petclinic project: https://github.com/spring-projects/spring-petclinic.git
2. Run mvn azure-spring:deploy after config to create an inactive deployment
3. Give a non-exist deployment's name and run mvn azure-spring:deploy
4. Verify error message is incorrect

**Comment by Flanker32** [comment]
Close it as we remove the check of existing deployments.
