### ISSUE TITLE
azure-spring:config warning message is incorrect

### ISSUE THREAD

**Issue by ZhengJun003** [microsoft/azure-maven-plugins#765]
### Plugin name and version
```
azure spring maven plugin
0.0.1-SNAPSHOT
```
### Plugin configuration in your `pom.xml`
```
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.springframework.samples</groupId>
  <artifactId>spring-petclinic</artifactId>
  <version>2.1.0.BUILD-SNAPSHOT</version>
  <packaging>pom</packaging>
```

```
  <build>
    <plugins>
      <plugin>
        <groupId>com.microsoft.azure</groupId>
        <artifactId>azure-spring-maven-plugin</artifactId>
        <version>0.0.1-SNAPSHOT</version>
      </plugin> 
```

### Actual behavior
This is a single project, there are no projects in the current folder need config after config `<packaging>pom</packaging>` in pom.xml
![image](https://user-images.githubusercontent.com/41051257/63757071-13b55a00-c8ec-11e9-875f-a039dd1d6cdb.png)

### Steps to reproduce the problem

1. Clone https://github.com/spring-projects/spring-petclinic.git
2. Config `<packaging>pom</packaging>` and `declare azure-spring-maven-plugin` in pom.xml
3. Run `mvn azure-spring:config`

**Comment by andxu** [comment]
Fixed at https://github.com/microsoft/azure-maven-plugins/pull/768

**Comment by ZhengJun003** [comment]
Fixed
Test in the branch feature-spring
![image](https://user-images.githubusercontent.com/41051257/63998688-4356a300-cb34-11e9-9c7e-d743ef33cd36.png)
