### ISSUE TITLE
The parameter 'column' overflows when run azure-spring:config goal in multiple project 

### ISSUE THREAD

**Issue by ZhengJun003** [microsoft/azure-maven-plugins#774]
### Plugin name and version
```
azure spring maven plugin
0.0.1-SNAPSHOT
```

### Plugin configuration in your `pom.xml`
```
  <build>
    <plugins>
      <plugin>
        <groupId>com.microsoft.azure</groupId>
        <artifactId>azure-spring-maven-plugin</artifactId>
        <version>0.0.1-SNAPSHOT</version>
      </plugin> 
```

### Actual behavior
![image](https://user-images.githubusercontent.com/41051257/63990572-0c25c900-cb17-11e9-8904-81fe56bcb52b.png)

### Steps to reproduce the problem
1. Prepare a multiple modulemaven project(eg:https://github.com/mfriedenhagen/multi-module-sample)
2. Add the plugin at project/build/plugins
3. run mvn azure-spring:config at root folder and login if the browser is started
4. verify config goal can be launched with the project list of jar modules.
5. select the first project using index 1
6. select subscription
7. select a cluster
8. confirm this app to public (y/n option, default to no)
9. choose 'y' and check the select project is updated with all values from your input.

**Comment by andxu** [comment]
https://github.com/microsoft/azure-maven-plugins/pull/775

**Comment by ZhengJun003** [comment]
Fixed
Test in the branch feature-spring
