### ISSUE TITLE
The confirm message of com.microsoft.azure:azure-spring-maven-plugin:0.0.1-SNAPSHOT:deploy is not complete

### ISSUE THREAD

**Issue by Elvira-sxr** [microsoft/azure-maven-plugins#796]
### Plugin name and version
azure spring maven plugin
0.0.1-SNAPSHOT
### Expected behavior
![image](https://user-images.githubusercontent.com/51812626/64407152-3139af00-d0b6-11e9-8245-3f66166f6780.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/51812626/64407895-094b4b00-d0b8-11e9-9a91-5796ef6212de.png)

### Steps to reproduce the problem
1.mvn com.microsoft.azure:azure-spring-maven-plugin:0.0.1-SNAPSHOT:config
2.Select module gateway,auth-service and account-service
3.Select your subscription and spring cloud service cluster
4.Expose public access to gateway
5.mvn clean package -DskipTests
6.mvn com.microsoft.azure:azure-spring-maven-plugin:0.0.1-SNAPSHOT:deploy

**Comment by Flanker32** [comment]
Fixed in #825
