### ISSUE TITLE
The parent's pom.xml does not form the corresponding plugin configuration.

### ISSUE THREAD

**Issue by Elvira-sxr** [microsoft/azure-maven-plugins#800]
### Plugin name and version
azure spring maven plugin
0.0.1-SNAPSHOT
### Expected behavior
![image](https://user-images.githubusercontent.com/51812626/64500157-a394d400-d2ee-11e9-93e6-20c054b5ac52.png)
### Actual behavior
![image](https://user-images.githubusercontent.com/51812626/64500118-7811e980-d2ee-11e9-8ba4-d02c556b48ee.png)
### Steps to reproduce the problem
1.mvn clean package -DskipTests
2.run mvn com.microsoft.azure:azure-spring-maven-plugin:0.0.1-SNAPSHOT:config
3.Select module gateway,auth-service and account-service
4.Select your subscription and spring cloud service cluster
5.Expose public access to gateway

**Comment by andxu** [comment]
Fixed at https://github.com/microsoft/azure-maven-plugins/pull/802/files#diff-1bc70feaa86d5da60d8d6fda30da28e6L238

**Comment by andxu** [comment]
Code merged in develop.

**Comment by ZhengJun003** [comment]
Test in develop branch, this issue is fixed.

![图片](https://user-images.githubusercontent.com/41051257/64679727-e6050f00-d4ae-11e9-9ea6-1b27f22fea9f.png)
