### ISSUE TITLE
Cannot login using a SP with cert

### ISSUE THREAD

**Issue by ZhengJun003** [microsoft/azure-maven-plugins#835]
### Plugin name and version
```
azure spring cloud maven plugin
0.1.0-SNAPSHOT
```
### Plugin configuration in your `pom.xml`
```
<plugin>
  <groupId>com.microsoft.azure</groupId>
  <artifactId>azure-spring-cloud-maven-plugin</artifactId>
  <version>0.1.0-SNAPSHOT</version>
</plugin>
```
### Actual behavior
![图片](https://user-images.githubusercontent.com/41051257/65592848-f1cdf680-dfc1-11e9-94de-735b03b2d33a.png)

**Comment by andxu** [comment]
fixed at https://github.com/microsoft/azure-maven-plugins/pull/837/files

**Comment by andxu** [comment]
https://github.com/microsoft/azure-maven-plugins/pull/837

**Comment by ZhengJun003** [comment]
Fixed
Test in develop branch
