### ISSUE TITLE
There is a space before the option input

### ISSUE THREAD

**Issue by Elvira-sxr** [microsoft/azure-maven-plugins#836]
### Plugin name and version

azure spring cloud maven plugin
0.1.0-SNAPSHOT
### Plugin configuration in your `pom.xml`

<plugin>
  <groupId>com.microsoft.azure</groupId>
  <artifactId>azure-spring-cloud-maven-plugin</artifactId>
  <version>0.1.0-SNAPSHOT</version>
</plugin>

### Actual behavior

![image](https://user-images.githubusercontent.com/51812626/65652286-cf7cbd00-e043-11e9-8e37-876cb5b95e2d.png)

![image](https://user-images.githubusercontent.com/51812626/65652849-c5f45480-e045-11e9-8e80-7065bf83b8f6.png)

### Steps to reproduce the problem

mvn azure-spring-cloud:config

**Comment by andxu** [comment]
Cannot repro:
![image](https://user-images.githubusercontent.com/17075863/65734627-7fb2fa00-e106-11e9-8961-
cc79dcf72ae1.png)

**Comment by Elvira-sxr** [comment]
Operating environment: maven version 3.3.3
The test has the following problems
1、When running mvn azure-spring-cloud:config in local cmd and powershell, the result is garbled
![image](https://user-images.githubusercontent.com/51812626/65744345-ac790880-e12a-11e9-97c8-b91f83c3fc1d.png)

2、When running mvn azure-spring-cloud:config in the terminal of vs code, there are spaces in front of the option in the subscription and cluster option modules.
![image](https://user-images.githubusercontent.com/51812626/65744383-c61a5000-e12a-11e9-8ee3-9a4743609c1e.png)

Conclusion: This question is still exist
