### ISSUE TITLE
including msssql driver needs weird code otherwise you get a class not found exception.

### ISSUE THREAD

**Issue by nicenemo** [Microsoft/azure-maven-plugins#85]
### Expected behavior
Not having to add:

```
  @SuppressWarnings("unchecked")
      Class< com.microsoft.sqlserver.jdbc.SQLServerDriver> clazz = (Class<SQLServerDriver>) Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
      logger.log(Level.FINE,clazz.getName() +" loaded");
```
Or have something like this documented.
### Actual behavior
If I do not add the above code I get a ClassNotFoundException if I run this code via
`mvn package azure-functions:run`
When database access is done from the integration tests it works fine without.
See also comments in: https://github.com/Azure/azure-functions-java-worker/issues/35 

### Steps to reproduce the problem
try to access a msssql database in azure in an integration test withouth and with this `Class.forName(..)`.
Then try to run the same from within a function in the function runtime.

**Comment by jdneo** [comment]
Seems fixed in v0.2.0.

@nicenemo Please feel free to reopen it if you find this issue is still blocking you after using 0.2.0 plugin.
