### ISSUE TITLE
Deploy to Azure using HTTPS

### ISSUE THREAD

**Issue by gminog** [microsoft/azure-maven-plugins#864]
I attempt to perform a deployment in a Java-based Azure Function but I receive an error while trying to execute the below maven command via Powershell:
```
mvn clean install -DskipTests -Pdeploy
```
Below you may find the error:
```
[ERROR] Failed to execute goal com.microsoft.azure:azure-functions-maven-plugin:1.3.3:deploy (default) on project foo: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyE
xception: Unrecognized field "evaluationDetails" (class com.microsoft.azure.PolicyViolationErrorInfo), not marked as ignorable (13 known properties: "policyDefinitionId", "policyDefinitionRefe
renceId", "policyDefinitionDisplayName", "policyAssignmentParameters", "policyAssignmentName", "policySetDefinitionName", "policyDefinitionName", "policyAssignmentScope", "policyDefinitionEffe
ct", "policyAssignmentId", "policySetDefinitionId", "policySetDefinitionDisplayName", "policyAssignmentDisplayName"])
[ERROR]  at [Source: (String)"{"policyDefinitionDisplayName":"Secure transfer to storage accounts should be enabled","policySetDefinitionDisplayName":"[Preview]: Enable Monitoring in Azure Sec
urity Center","evaluationDetails":{"evaluatedExpressions":[{"result":"True","expressionKind":"Field","expression":"type","path":"type","expressionValue":"Microsoft.Storage/storageAccounts","ta
rgetValue":"Microsoft.Storage/storageAccounts","operator":"Equals"},{"result":"False","expressionKind":"Field","expression":"Microsoft.Storage/sto"[truncated 1941 chars]; line: 1, column: 198]
 (through reference chain: com.microsoft.azure.CloudError["additionalInfo"]->java.util.ArrayList[0]->com.microsoft.azure.PolicyViolationErrorInfo["evaluationDetails"])
```
The error points to a Security Policy that has been applied by the tenant admins whereby deployments must be performed over a secure transfer protocol (i.e. HTTP over SSL).
Obviously, the admins must be having good reasons to apply that policy and we need to comply.

Assuming I'm not misinterpreting the error message, is there a way for the azure-functions-maven-plugin to perform a deployment over HTTPS?

**Comment by Flanker32** [comment]
@gminog Thanks for your feedback and sorry for the late response, could you please share a bit more information like what kind of Triggers did you use in this function? And it could be better if you could share the full log here, you may get it by `mvn -X`
Besides, the error message shows "Secure transfer to storage accounts should be enabled", is this feature enabled in correspond storage account related to this function? Please refer [here ](https://docs.microsoft.com/en-us/azure/storage/common/storage-require-secure-transfer)for more details

**Comment by gminog** [comment]
@Flanker32 Yes, the `Secure Transfer required` option of the relevant Storage Account is set to enabled (we cannot change that).
The only trigger type for this Azure Function is `blobTrigger`

Note that ignoring the error and proceeding with `func azure functionapp publish $FUNC_NAME` allows us to perform the deployment.
However, that approach seems sub-optimal.

**Comment by Flanker32** [comment]
@gminog Thanks for your information, i tried to create a function with blobTrigger and it seems works well with maven plugin no matter the Secure Transfer configuraiton, could you please share the project or the full log so that we could better investigate this issue, thanks a lot for the help

**Comment by gminog** [comment]
Recreating the storage account resolved the issue.
There is no clear indication on what caused it in the first place.
