### ISSUE TITLE
Unable to deploy App Service artifact due to policy restriction 

### ISSUE THREAD

**Issue by devil5** [microsoft/azure-maven-plugins#878]
### Plugin name and version
azure-webapp-maven-plugin 1.7.0

### Plugin configuration in your `pom.xml`
<plugin>
   <groupId>com.microsoft.azure</groupId>
   <artifactId>azure-webapp-maven-plugin</artifactId>
   <version>1.7.0</version>
   <configuration>
      <schemaVersion>V2</schemaVersion>
      <resourceGroup>app-dev-syd-rg</resourceGroup>
      <appName>app</appName>

      <region>australiaeast</region>
      <pricingTier>P1V2</pricingTier>
      <runtime>
         <os>linux</os>
         <javaVersion>jre8</javaVersion>
         <webContainer>jre8</webContainer>
      </runtime>
      <appsettings>
         <property>
            <name>JAVA_OPTS</name>
            <value>-Dserver.port=80</value>
         </property>
         <property>
            <name>--tags</name>
            <value>team-pod=enterprise-platforms</value>
         </property>
      </appsettings>
      <deployment>
         <resources>
            <resource>
               <directory>${project.basedir}/target</directory>
               <includes>
                  <include>*.jar</include>
               </includes>
            </resource>
         </resources>
      </deployment>
   </configuration>
</plugin>

### Expected behavior
No documentation available on How to add tags to the artifact being deployed.

### Actual behavior
Unable to push due to policy restrictions. 
Error when running: mvn azure-webapp:deploy

[ERROR] Failed to execute goal com.microsoft.azure:azure-webapp-maven-plugin:1.7.0:deploy (default-cli) on project gs-spring-boot: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyExce
ption: Unrecognized field "evaluationDetails" (class com.microsoft.azure.PolicyViolationErrorInfo), not marked as ignorable (13 known properties: "policyDefinitionId", "policyDefinitionRefer
enceId", "policyDefinitionDisplayName", "policyAssignmentParameters", "policyAssignmentName", "policySetDefinitionName", "policyDefinitionName", "policyAssignmentScope", "policyDefinitionEff
ect", "policyAssignmentId", "policySetDefinitionId", "policySetDefinitionDisplayName", "policyAssignmentDisplayName"])
[ERROR]  at [Source: (String)"{"policyDefinitionDisplayName":"Custom - Enforce 'team-pod' Tag","policySetDefinitionDisplayName":"Custom - Resource Tagging Initiative","evaluationDeta
ils":{"evaluatedExpressions":[{"result":"True","expressionKind":"Field","expression":"type","path":"type","expressionValue":"Microsoft.Web/serverfarms","targetValue":"Microsoft.Compute/virtu
alMachines/extensions","operator":"NotEquals"},{"result":"True","expressionKind":"Field","expression":"type","path":"type","expressionValue":"Microsof"[truncated 1803 chars]; line: 1, column
: 167] (through reference chain: com.microsoft.azure.CloudError["additionalInfo"]->java.util.ArrayList[0]->com.microsoft.azure.PolicyViolationErrorInfo["evaluationDetails"])

### Steps to reproduce the problem
Add a policy restriction to the Azure subscription which only allows App Services with certain predefined tags.

Then try to deploy an app service as described in the article:
https://docs.microsoft.com/en-gb/java/azure/spring-framework/deploy-spring-boot-java-app-with-maven-plugin?view=azure-java-stable

**Comment by Flanker32** [comment]
@devil5 Thanks for your feedback, and sorry for the late reply. For now function maven plugin didn't support set tags in deployment, we will add this feature in later releases.
