### ISSUE TITLE
Docker image name should honor shorthand syntax

### ISSUE THREAD

**Issue by mnriem** [microsoft/azure-maven-plugins#904]
### Plugin name and version

azure-webapp-maven-plugin:1.8.0

### Plugin configuration in your `pom.xml`

```
<runtime>
  <os>docker</os>
  <image>myimage</image>
</runtime>
```

### Expected behavior

Deployment succeeds

### Actual behavior

Deployment fails because it does not honor the shorthand name

### Steps to reproduce the problem

Use an image name as shown above and deployment fails. Change it to myimage:latest and it works

**Comment by Flanker32** [comment]
@mnriem Thanks for your report, investigating this issue

**Comment by Flanker32** [comment]
@mnriem Thanks for your report and really sorry for the late reply, maven plugin directly called [WithDockerContainerImage.withPublicDockerHubImage](https://github.com/Azure/azure-libraries-for-java/blob/master/azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/WebApp.java) in java fluent sdk, and we checked with SDK team that sdk just pass the parameters to the server side. So it seems more like a app service server issue, i'll check with service team later and update here.
