### ISSUE TITLE
A required class was missing while executing azure-functions-maven-plugin:0.1.10:package

### ISSUE THREAD

**Issue by JunyiYi** [Microsoft/azure-maven-plugins#91]
### Plugin name and version

azure-functions-maven-plugin

### Plugin configuration in your `pom.xml`

```xml
<plugin>
  <groupId>com.microsoft.azure</groupId>
  <artifactId>azure-functions-maven-plugin</artifactId>
  <configuration>
    <resourceGroup>java-functions-group</resourceGroup>
    <appName>${functionAppName}</appName>
    <region>${functionAppRegion}</region>
    <appSettings>
      <property>
        <name>FUNCTIONS_EXTENSION_VERSION</name>
        <value>beta</value>
      </property>
    </appSettings>
  </configuration>
  <executions>
    <execution>
      <id>package-functions</id>
      <goals>
        <goal>package</goal>
      </goals>
    </execution>
  </executions>
</plugin>
```

### Expected behavior

Build Succeeded.

### Actual behavior

Build Failed.

### Steps to reproduce the problem

I'm facing the error A required class was missing while executing com.microsoft.azure:azure-functions-maven-plugin:0.1.10:package: org/springframework/context/ApplicationContext when using Spring framework in my functions.

[Reproducer.zip](https://github.com/Azure/azure-functions-java-worker/files/1764654/Reproducer.zip)
The error happens on mvn clean package and seems to be related to class scanning for annotations.

A reproducer is attached.

Full log bellow:
[Reproducer.zip](https://github.com/Azure/azure-functions-java-worker/files/1764657/Reproducer.zip)

**Comment by damadei** [comment]
I believe we can close this one as this is the same as #90. I opened in the wrong place.
