### ISSUE TITLE
Problems of portal support for Linux function app

### ISSUE THREAD

**Issue by ZhengJun003** [microsoft/azure-maven-plugins#915]
### Plugin name and version
azure-functions-maven-plugin 1.3.5-SNAPSHOT
### Plugin configuration in your pom.xml
```
            <plugin>
                <groupId>com.microsoft.azure</groupId>
                <artifactId>azure-functions-maven-plugin</artifactId>
                <configuration>
                    <resourceGroup>${functionResourceGroup}</resourceGroup>
                    <appName>${functionAppName}</appName>
                    <region>${functionAppRegion}</region>
                    <pricingTier>B3</pricingTier>
                    <deploymentType>RUN_FROM_ZIP</deploymentType>
                    <runtime>
                        <os>linux</os>
                    </runtime>
                    <appSettings>
                        <!-- Run Azure Function from package file by default -->
                        <property>
                            <name>FUNCTIONS_EXTENSION_VERSION</name>
                            <value>~3</value>
                        </property>
                        <property>
                            <name>AzureWebJobsStorage</name>
                            <value>xxxxx</value>
                        </property>
                        ......
                    </appSettings>
                </configuration>
                <executions>
                    <execution>
                        <id>package-functions</id>
                        <goals>
                            <goal>package</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```
### Expected behavior
1. Function app logs 
![image](https://user-images.githubusercontent.com/41051257/70107205-d0078480-1680-11ea-8365-b8fac7124293.png)

2. Function app integrate show trigger resource information
![image](https://user-images.githubusercontent.com/41051257/70107110-9898d800-1680-11ea-9d9d-dde512e056d5.png)

### Actual behavior
1. Function app logs render error and garbled code
![image](https://user-images.githubusercontent.com/41051257/70023646-10102e00-15d3-11ea-9509-400abb94ce5f.png)

2. Function app integrate not show trigger resource information
![image](https://user-images.githubusercontent.com/41051257/70107044-5f606800-1680-11ea-98d5-b7c8e1638ec3.png)

**Comment by Elvira-sxr** [comment]
### Plugin name and version
azure-functions-maven-plugin 1.3.5-SNAPSHOT
###  Runtime
 docker
### Function app integrate  can not show trigger resource information
![image](https://user-images.githubusercontent.com/51812626/70526562-d4520700-1b84-11ea-95c5-1073649338ea.png)
