### ISSUE TITLE
Can't trigger function app after deploying to the portal

### ISSUE THREAD

**Issue by ZhengJun003** [microsoft/azure-maven-plugins#918]
### Plugin name and version
azure-functions-maven-plugin 1.3.5-SNAPSHOT
### Plugin configuration in your pom.xml
```
            <plugin>
                <groupId>com.microsoft.azure</groupId>
                <artifactId>azure-functions-maven-plugin</artifactId>
                <configuration>
                    <resourceGroup>${functionResourceGroup}</resourceGroup>
                    <appName>${functionAppName}</appName>
                    <region>${functionAppRegion}</region>
                    <pricingTier>xxx</pricingTier>
                    <deploymentType>RUN_FROM_ZIP</deploymentType>
                    <runtime>
                        <os>linux</os>
                    </runtime>
                    <appSettings>
                        <!-- Run Azure Function from package file by default -->
                        <property>
                            <name>FUNCTIONS_EXTENSION_VERSION</name>
                            <value>~3</value>
                        </property>
                        <property>
                            <name>AzureWebJobsStorage</name>
                            <value>xxxxx</value>
                        </property>
                        ......
                    </appSettings>
                </configuration>
                <executions>
                    <execution>
                        <id>package-functions</id>
                        <goals>
                            <goal>package</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```
### Actual behavior
1. When triggering the function app after deploying to the portal, there no trigger info shows in logs.
![image](https://user-images.githubusercontent.com/41051257/70030281-d98edf00-15e3-11ea-9b92-95d0294896e9.png)

2. Can triggering the function app after updating function app
![image](https://user-images.githubusercontent.com/41051257/70030939-35a63300-15e5-11ea-8b8b-5f0eac2ec86d.png)

**Comment by Flanker32** [comment]
@ZhengJun003 This should be the portal issue, which same as #915, the function is triggered but portal didn't show the log in time, please verify it and check the trigger logs with ssh.

**Comment by ZhengJun003** [comment]
verify in branch hanxiao/fixImage.
It can trigger the function app after deploy, but the logs format is not correct. this issue is the same as #915
![image](https://user-images.githubusercontent.com/41051257/70421577-fd02cf80-1aa4-11ea-809c-ee7dba86cdc8.png)
