### ISSUE TITLE
Deploy function app using low pricing tier is not available

### ISSUE THREAD

**Issue by ZhengJun003** [microsoft/azure-maven-plugins#919]
### Plugin name and version
azure-functions-maven-plugin 1.3.5-SNAPSHOT
### Plugin configuration in your pom.xml
```
            <plugin>
                <groupId>com.microsoft.azure</groupId>
                <artifactId>azure-functions-maven-plugin</artifactId>
                <configuration>
                    <resourceGroup>${functionResourceGroup}</resourceGroup>
                    <appName>${functionAppName}</appName>
                    <region>${functionAppRegion}</region>
                    <pricingTier>Consumption</pricingTier>
                    <deploymentType>RUN_FROM_BLOB</deploymentType>
                    <runtime>
                        <os>linux</os>
                    </runtime>
                    <appSettings>
                        <!-- Run Azure Function from package file by default -->
                        <property>
                            <name>FUNCTIONS_EXTENSION_VERSION</name>
                            <value>~3</value>
                        </property>
                        <property>
                            <name>AzureWebJobsStorage</name>
                            <value>xxxxx</value>
                        </property>
                        ......
                    </appSettings>
                </configuration>
                <executions>
                    <execution>
                        <id>package-functions</id>
                        <goals>
                            <goal>package</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```
### Actual behavior
1. Use `Consumption/Dedicated` pricing tier to deploy, function app is not available. Refresh later, the function app with the `Dedicated` pricing tier is available. but the function app with the `Consumption` pricing tier always isn't available.
![image](https://user-images.githubusercontent.com/41051257/70034687-8c633b00-15ec-11ea-8df4-f1e8b048a60c.png)

2. Use `Consumption` pricing tier to deploy function app. some times, it can show functions, but the logs show like below.
![image](https://user-images.githubusercontent.com/41051257/70036399-af431e80-15ef-11ea-8f5f-cc434f0aae75.png)
![image](https://user-images.githubusercontent.com/41051257/70035513-ef090680-15ed-11ea-8aae-2e34055dd9c9.png)

**Comment by Elvira-sxr** [comment]
### Plugin name and version
azure-functions-maven-plugin 1.4.1-SNAPSHOT
### Actual behavior
Use Dedicated / Premium pricing tier to deploy under windows runtime, function app is not available. When updating the pricing tier of function app, function app is available
![image](https://user-images.githubusercontent.com/51812626/72413048-da518e00-37a9-11ea-904e-e89830e7a54e.png)
