### ISSUE TITLE
Azure Functions Maven Plugin requires CLI authentication every time a new console session is open

### ISSUE THREAD

**Issue by damadei** [Microsoft/azure-maven-plugins#92]
Every time a console session is started, even though the CLI V2 (az) is authenticated, I get the following error:

Execution default-cli of goal com.microsoft.azure:azure-functions-maven-plugin:0.1.10:deploy failed: An API incompatibility was encountered while executing com.microsoft.azure:azure-functions-maven-plugin:0.1.10:deploy: java.lang.NoSuchMethodError: com.microsoft.aad.adal4j.AuthenticationResult.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;JLjava/lang/String;Lcom/microsoft/aad/adal4j/UserInfo;Z)V

First it's worth mentioning that this is not a friendly error and it's hard to figure the reason out. The other thing is that it makes no sense having to authenticate every time a console session (cmd) is started. The CLI v2 API holds the authentication for a couple of days and the maven plugin should support that.

### Plugin name and version
com.microsoft.azure:azure-functions-maven-plugin:0.1.10

### Plugin configuration in your `pom.xml`
		<plugins>
			<plugin>
				<groupId>com.microsoft.azure</groupId>
				<artifactId>azure-functions-maven-plugin</artifactId>
				<configuration>
					<resourceGroup>xxxxxx</resourceGroup>
					<appName>${functionAppName}</appName>
					<region>${functionAppRegion}</region>
					<appSettings>
						<property>
							<name>FUNCTIONS_EXTENSION_VERSION</name>
							<value>beta</value>
						</property>
					</appSettings>
				</configuration>
				<executions>
					<execution>
						<id>package-functions</id>
						<goals>
							<goal>package</goal>
						</goals>
					</execution>
				</executions>

				<dependencies>
					<dependency>
						<groupId>org.apache.poi</groupId>
						<artifactId>poi</artifactId>
						<version>${apache.poi.version}</version>
					</dependency>

					<dependency>
						<groupId>org.apache.poi</groupId>
						<artifactId>poi-ooxml</artifactId>
						<version>${apache.poi.version}</version>
					</dependency>

					<dependency>
						<groupId>org.springframework</groupId>
						<artifactId>spring-jdbc</artifactId>
						<version>${spring.components.version}</version>
					</dependency>

					<dependency>
						<groupId>com.microsoft.sqlserver</groupId>
						<artifactId>mssql-jdbc</artifactId>
						<version>${mssql-jdbc.version}</version>
					</dependency>

					<dependency>
						<groupId>org.springframework</groupId>
						<artifactId>spring-beans</artifactId>
						<version>${spring.components.version}</version>
					</dependency>

					<dependency>
						<groupId>org.springframework</groupId>
						<artifactId>spring-context</artifactId>
						<version>${spring.components.version}</version>
					</dependency>

					<dependency>
						<groupId>org.springframework</groupId>
						<artifactId>spring-web</artifactId>
						<version>${spring.components.version}</version>
					</dependency>

					<dependency>
						<groupId>commons-dbcp</groupId>
						<artifactId>commons-dbcp</artifactId>
						<version>${commons.dbcp.version}</version>
					</dependency>
				</dependencies>
			</plugin>

### Steps to reproduce the problem
Authenticate using az login, deploy an Azure function using Maven plugin. Close the CMD window and open another one, check that az is still authenticated however if you try to deploy your function, an error is shown. If you authenticate again via az login in the same CMD session, it works.

**Comment by jdneo** [comment]
Hi @damadei Could you provide full logs?

**Comment by damadei** [comment]
Hi Sheng, I'm attaching the logs after I removed my token because of security reasons. 
[logs.txt](https://github.com/Microsoft/azure-maven-plugins/files/2225314/logs.txt)

The issue persists even on the new version of the maven plugin.

**Comment by jdneo** [comment]
Closing since the thread is inactive for a long time. Please feel free to reopen it if you still need help.
