### ISSUE TITLE
[Auth] Confusing error message when credential outdated

### ISSUE THREAD

**Issue by yucwan** [microsoft/azure-maven-plugins#924]
PS C:\Users\yucwan\Documents\vswroks\piggymetrics> mvn com.microsoft.azure:azure-spring-cloud-maven-plugin:1.0.0:config
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] piggymetrics                                                       [pom]
[INFO] config                                                             [jar]
[INFO] monitoring                                                         [jar]
[INFO] registry                                                           [jar]
[INFO] gateway                                                            [jar]
[INFO] auth-service                                                       [jar]
[INFO] account-service                                                    [jar]
[INFO] statistics-service                                                 [jar]
[INFO] notification-service                                               [jar]
[INFO] turbine-stream-service                                             [jar]
[INFO] 
[INFO] -------------------< com.piggymetrics:piggymetrics >--------------------
[INFO] Building piggymetrics 1.0-SNAPSHOT                                [1/10]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- azure-spring-cloud-maven-plugin:1.0.0:config (default-cli) @ piggymetrics ---
The following child modules are not configured:
 1. config
 2. monitoring
 3. registry
 4. gateway
 5. auth-service
 6. account-service
 7. statistics-service
 8. notification-service
 9. turbine-stream-service
Select child modules to configure(input numbers separated by comma, eg: [1-2,4,6], ENTER to select ALL): 4 - 6
The input value('4 - 6') is invalid.
Select child modules to configure(input numbers separated by comma, eg: [1-2,4,6], ENTER to select ALL): 4-6
[INFO] [Correlation ID: 1e0bd521-ae25-4a98-b11c-9f79001e3482] Instance discovery was successful
[ERROR] [Correlation ID: 1e0bd521-ae25-4a98-b11c-9f79001e3482] Execution of class com.microsoft.aad.adal4j.AcquireTokenCallable failed.
com.microsoft.aad.adal4j.AuthenticationException: {"error_description":"AADSTS700082: The refresh token has expired due to inactivity.? The token was issued on 2019-08-29T04:44:11.7776364Z and was inactive for 90.00:00:00.\r\nTrace ID: fe425d71-0770-4593-b2ee-fca916f07900\r\nCorrelation ID: 1e0bd521-ae25-4a98-b11c-9f79001e3482\r\nTimestamp: 2019-12-04 09:05:18Z","error":"invalid_grant","error_uri":"https:\/\/login.microsoftonline.com\/error?code=700082"}
    at com.microsoft.aad.adal4j.AdalTokenRequest.executeOAuthRequestAndProcessResponse (AdalTokenRequest.java:128)
    at com.microsoft.aad.adal4j.AuthenticationContext.acquireTokenCommon (AuthenticationContext.java:928)
    at com.microsoft.aad.adal4j.AcquireTokenCallable.execute (AcquireTokenCallable.java:70)
    at com.microsoft.aad.adal4j.AcquireTokenCallable.execute (AcquireTokenCallable.java:38)
    at com.microsoft.aad.adal4j.AdalCallable.call (AdalCallable.java:47)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
    at java.lang.Thread.run (Thread.java:748)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] piggymetrics 1.0-SNAPSHOT .......................... FAILURE [ 17.169 s]
[INFO] config 1.0.0-SNAPSHOT .............................. SKIPPED
[INFO] monitoring 0.0.1-SNAPSHOT .......................... SKIPPED
[INFO] registry 0.0.1-SNAPSHOT ............................ SKIPPED
[INFO] gateway 1.0-SNAPSHOT ............................... SKIPPED
[INFO] auth-service 1.0-SNAPSHOT .......................... SKIPPED
[INFO] account-service 1.0-SNAPSHOT ....................... SKIPPED
[INFO] notification-service 1.0.0-SNAPSHOT ................ SKIPPED
[INFO] turbine-stream-service 0.0.1-SNAPSHOT .............. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  17.742 s
[INFO] Finished at: 2019-12-04T17:05:18+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.microsoft.azure:azure-spring-cloud-maven-plugin:1.0.0:config (default-cli) on project piggymetrics: {"error_description":"AADSTS700082: The refresh token has expired due to inactivity.? The token was issued on 2019-08-29T04:44:11.7776364Z and was inactive for 90.00:00:00.\r\nTrace ID: fe425d71-0770-4593-b2ee-fca916f07900\r\nCorrelation ID: 1e0bd521-ae25-4a98-b11c-9f79001e3482\r\nTimestamp: 2019-12-04 09:05:18Z","error":"invalid_grant","error_uri":"https:\/\/login.microsoftonline.com\/error?code=700082"} -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by yucwan** [comment]
1. If possible, should consider checking auth before selecting modules.
2. Should inform user which auth method is used.

**Comment by wangmingliang-ms** [comment]
![image](https://user-images.githubusercontent.com/69189193/191160596-57cb42d4-57d2-4983-9f41-0f610696e305.png)
