### ISSUE TITLE
Java Azure Functions - The function runtime is unable to start - Could not load type 'Microsoft.Azure.ServiceBus.Management.ManagementClient

### ISSUE THREAD

**Issue by amamounelsayed** [microsoft/azure-maven-plugins#929]
https://github.com/Azure/azure-functions-host/issues/5317

Please can we check if there anything from the deploy side need to take care of this issue?

**Comment by Flanker32** [comment]
@amamounelsayed Maven plugin will check function bundle since 1.3.4 and will skip func install after that. Besides, we will release new archetype which will copy host.json before package, so func host could check it and avoid this issue.
