### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-maven-plugins#93]
### Plugin name and version
com.microsoft.azure.azure-functions-maven-plugin:0.1.10-SNAPSHOT
### Steps to reproduce the problem

1. Generate a scaffolding through the Azure Functions Maven Archetype
mvn archetype:generate -DarchetypeGroupId=com.microsoft.azure -DarchetypeArtifactId=azure-functions-archetype
3. mvn package azure-functions:package
4. mvn azure-functions:run
5. Ctrl-C to exist
6. Run mvn azure-functions:run again

![image](https://user-images.githubusercontent.com/22470312/36884536-a6209fe8-1e1c-11e8-821f-37d209fe104b.png)

**Comment by jdneo** [comment]
Looks like this is an issue related with the function cli.

**Comment by jdneo** [comment]
Hi @bsaby I cannot repro this bug within the newest azure-functions-core-tools-2.0.1-beta.28.

Could you please check if this issue still occurs on your side?

**Comment by bsaby** [comment]
Version: azure-functions-core-tools:2.0.1-beta.28
On my side, repro in git bash, but it works on my PowerShell. It doesn't seem to be our plugin's bug,  close it.
