### ISSUE TITLE
can't run “mvn azure-functions:run -Dfunctions.target=...  ”successfully 

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-maven-plugins#95]
### Plugin name and version
com.microsoft.azure.azure-functions-maven-plugin:0.1.10-SNAPSHOT
### Actual behavior
According to the doc: https://github.com/Microsoft/azure-maven-plugins/blob/master/azure-functions-maven-plugin/README.md#run-a-single-azure-function
![image](https://user-images.githubusercontent.com/22470312/36894405-2a48d550-1e46-11e8-8634-e8f253e27872.png)

**Comment by jdneo** [comment]
Per conformation from the function-cli team. `func function run` has been removed from v2 cli.

We need to change the code and docs accordingly.
