### ISSUE TITLE
Can not use the existing "app service plan" to deploy under docker runtime if you don't set pricingTier

### ISSUE THREAD

**Issue by Elvira-sxr** [microsoft/azure-maven-plugins#966]
### Plugin name and version
1.4.1-SNAPSHOT Azure Functions
### Plugin configuration in your `pom.xml`
![image](https://user-images.githubusercontent.com/51812626/71407088-08452600-2675-11ea-99a9-6f2bc046914a.png)
### Actual behavior
![image](https://user-images.githubusercontent.com/51812626/71407113-1a26c900-2675-11ea-8268-39dc582ddfb1.png)

### Steps to reproduce the problem
1.Configure pom.xml
2.mvn clean package
3.mvn azure-functions:deploy

**Comment by Flanker32** [comment]
FIxed in #1017
