### ISSUE TITLE
When updating the function, there is a problem with the UI display: it should not be "app.", But "app:"

### ISSUE THREAD

**Issue by Elvira-sxr** [microsoft/azure-maven-plugins#976]
### Plugin name and version
1.4.1-SNAPSHOT Azure Functions
### Expected behavior
![image](https://user-images.githubusercontent.com/51812626/71715599-e7d35380-2e4c-11ea-991a-844d59d7512a.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/51812626/71715707-4ef10800-2e4d-11ea-8dc3-924874be68d4.png)

### Steps to reproduce the problem
1.mvn clean package
2.mvn azure-functions:deploy

**Comment by Flanker32** [comment]
FIxed in #978, @Elvira-sxr Please help us verify and close this issue, thanks.

**Comment by Elvira-sxr** [comment]
This issue has been fixed under develop branch
![image](https://user-images.githubusercontent.com/51812626/72056220-2b273980-3307-11ea-9229-304daa27464c.png)
