### ISSUE TITLE
Strange error message "The  only allow alphanumeric characters"

### ISSUE THREAD

**Issue by yucwan** [microsoft/azure-maven-plugins#977]
### Plugin name and version
webapp 1.8.0

### Actual behavior

on running command mvn package azure-webapp:deploy
I encountered error:-
RROR] Failed to execute goal com.microsoft.azure:azure-webapp-maven-plugin:1.8.0:deploy (default-cli) on project HelloWorld: The  only allow alphanumeric characters, hyphens and cannot start or end in a hyphen. -> [Help 1]

**Comment by yucwan** [comment]
Found out that `<appName>` will be escaped by our survey site. it is not a bug from product side.

**Comment by NakioNakamu** [comment]
For those in the future that have this same issue, I found out this command didn't like the appName in my application's pom file (unrelated to this project), listed under configurations. 

Hopefully, this will save time for others!

**Comment by Flanker32** [comment]
@PhoenixGrad Thanks for your report, do you mean the webapp maven plugin throw validation exception for values in other pom file? Could you pleas help share us a demo project to reproduce this issue?

**Comment by NakioNakamu** [comment]
@Flanker32 

https://spring.io/guides/gs/spring-boot-for-azure/

I was following the example listed above to deploy a spring application to the web app service of Azure. [Option 2 -> Step 3] There is a way to open the pom.xml file to view the configuration written. Under [plugin->configuration->appName] my application had a "." in the name, which threw this error. 

Prior to finding this error, this issue page was the only area that I had found someone else having the same problem. Once I found out, I responded to this thread in case others were looking for a potential solution as well.

I, unfortunately, do not have the example on hand, but hopefully, this description would suffice for the explanation.

**Comment by Flanker32** [comment]
@PhoenixGrad Thanks a lot for your response! Maven plugin will check the <appName> before deploy resources to Azure, and will throw exception once the validation is not passed. The error message may not be clear before and sorry for the confusing. We have refactor our error notification in later version to make it more clear, hope this could help you in later deployment, here is an example.

```
[ERROR] Failed to execute goal com.microsoft.azure:azure-webapp-maven-plugin:2.2.0:deploy (default-cli) on project spring-boot-complete: deploy to Azure Web App with resource creation or updating: Invalid values found in configuration, please correct the value with messages below:
[ERROR] configuration.appName: does not match the regex pattern ^[a-zA-Z0-9\-]+$
```
